# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-03 10:23

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_db_logger", "0002_auto_20190109_0052"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedNotification",
            fields=[
                (
                    "statuslog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_db_logger.StatusLog",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        help_text="Status code received from the Notifications API.",
                        verbose_name="status_code",
                    ),
                ),
                (
                    "message",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="Content of the notification that was attempted to send.",
                        verbose_name="notification message",
                    ),
                ),
                (
                    "retried_at",
                    models.DateTimeField(
                        editable=False,
                        help_text="Timestamp logging if/when this message was retried.",
                        null=True,
                        verbose_name="retried at",
                    ),
                ),
            ],
            options={
                "verbose_name": "failed notification",
                "verbose_name_plural": "failed notifications",
            },
            bases=("django_db_logger.statuslog",),
        ),
    ]
