# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-07-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_log", "0001_initial"),
        ("notifications", "0009_auto_20190729_0427"),
        ("vng_api_common", "0005_auto_20190614_1346"),
        ("zgw_consumers", "0009_auto_20200401_0829"),
    ]

    operations = []
