# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_log", "0003_alter_failednotification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failednotification",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                help_text="Status code received from the Notifications API.",
                null=True,
                verbose_name="status_code",
            ),
        ),
    ]
