# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 5.2.15 on 2026-07-09 14:28

from django.db import migrations
from django.db.migrations import RunPython

SIZE = 500
def migrate_failed_notifications(apps, schema_editor):
    OldFailedNotification = apps.get_model('notifications_log', 'FailedNotification')
    NewFailedNotification = apps.get_model('notifications_api_common', 'FailedNotification')
    NotificationResponse = apps.get_model('notifications_api_common', 'NotificationResponse')

    notifications = []
    notification_responses = []
    for ofn in OldFailedNotification.objects.iterator(chunk_size=SIZE):
        # cloudevents where never caught in the logging filter
        nfn = NewFailedNotification(message=ofn.message,  type="notification")

        # status_code & response_status are both an integer field that allow null
        # msg is a textfield and could be larger than exception max length
        nr = NotificationResponse(failed_notification=nfn, exception=ofn.msg[:500], response_status=ofn.status_code)

        notifications.append(nfn)
        notification_responses.append(nr)

    NewFailedNotification.objects.bulk_create(notifications)
    NotificationResponse.objects.bulk_create(notification_responses)

    OldFailedNotification.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications_log', '0004_alter_failednotification_status_code'),
        ('notifications_api_common', '0011_failednotification_notificationresponse')
    ]

    operations = [
        RunPython(migrate_failed_notifications, migrations.RunPython.noop),
    ]
