# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 5.2.15 on 2026-07-09 14:28

from django.db import migrations
from django.db.migrations import RunPython


def migrate_failed_notifications(apps, schema_editor):
    FailedNotification = apps.get_model('notifications_log', 'FailedNotification')
    BaseNotification = apps.get_model('notifications_api_common', 'BaseNotification')

    BaseNotification.objects.bulk_create(
        (BaseNotification(
            message=fn.message,
            type="notification" # cloudevents where never caught in the logging filter
        )
            for fn in FailedNotification.objects.iterator(chunk_size=500)
        ),
        batch_size=500,
    )

    FailedNotification.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications_log', '0004_alter_failednotification_status_code'),
    ]

    operations = [
        RunPython(migrate_failed_notifications, migrations.RunPython.noop),
    ]
