# Generated by Django 5.2.15 on 2026-07-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_log', '0005_migrate_failednotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedNotification',
        ),
    ]
