# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referentielijstconfig",
            options={"verbose_name": "Selectielijstconfiguratie"},
        ),
        migrations.AlterField(
            model_name="referentielijstconfig",
            name="api_root",
            field=models.URLField(
                default="https://selectielijst.openzaak.nl/api/v1/",
                unique=True,
                verbose_name="api root",
            ),
        ),
    ]
