# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.10 on 2020-08-07 14:09

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0003_move_config_to_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="referentielijstconfig",
            name="allowed_years",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                default=[2017],
                help_text="De jaartallen waarvan er procestypen gebruikt mogen worden.",
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referentielijstconfig",
            name="default_year",
            field=models.PositiveIntegerField(
                default=2017,
                help_text="Het jaartal dat standaard geselecteerd is bij het kiezen van een procestype bij een zaaktype.",
            ),
            preserve_default=False,
        ),
    ]
