# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.10 on 2020-08-07 12:26

from django.db import migrations


def set_selectielijst_allowed_years(apps, _):
    ReferentieLijstConfig = apps.get_model("selectielijst", "ReferentieLijstConfig")

    config, _ = ReferentieLijstConfig.objects.get_or_create()
    config.allowed_years = [2017, 2020]
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0004_auto_20200807_1409"),
    ]

    operations = [
        migrations.RunPython(set_selectielijst_allowed_years, migrations.RunPython.noop)
    ]
