# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0006_auto_20200817_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referentielijstconfig",
            name="default_year",
            field=models.PositiveIntegerField(
                default=2020,
                help_text="Het jaartal dat standaard geselecteerd is bij het kiezen van een procestype bij een zaaktype.",
                null=True,
            ),
        ),
    ]
