# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 4.2.17 on 2025-02-11 12:52

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0008_remove_referentielijstconfig_api_root_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referentielijstconfig",
            name="allowed_years",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                default=list,
                help_text="The years from which procestypen may be used.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="referentielijstconfig",
            name="default_year",
            field=models.PositiveIntegerField(
                default=2020,
                help_text="The year that is selected by default when choosing a procestype for a zaaktype.",
                null=True,
            ),
        ),
    ]
