# Generated by Django 3.2.23 on 2024-04-16 13:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Openstaand"),
                            ("active", "Actief"),
                            ("success", "Voltooid"),
                            ("error", "Onderbroken"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[("documenten", "Enkelvoudige informatie objecten")],
                        max_length=30,
                        verbose_name="Type import",
                    ),
                ),
                (
                    "import_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Import metadata bestand",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Reportage bestand",
                    ),
                ),
                ("total", models.IntegerField(verbose_name="Totaal")),
                ("processed", models.IntegerField(default=0, verbose_name="Verwerkt")),
                (
                    "processed_succesfully",
                    models.IntegerField(default=0, verbose_name="Succesvol verwerkt"),
                ),
                (
                    "processed_invalid",
                    models.IntegerField(
                        default=0, verbose_name="Niet succesvol verwerkt"
                    ),
                ),
            ],
        ),
    ]
