# Generated by Django 3.2.23 on 2024-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_auto_20240417_1010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Openstaand"),
                    ("active", "Actief"),
                    ("finished", "Voltooid"),
                    ("error", "Onderbroken"),
                ],
                max_length=30,
            ),
        ),
    ]
