# Generated by Django 3.2.23 on 2024-04-17 10:22

from django.db import migrations

import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_alter_import_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="import_file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="import/import-files/",
                verbose_name="Import metadata bestand",
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="report_file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="import/report-files/",
                verbose_name="Reportage bestand",
            ),
        ),
    ]
