# Generated by Django 3.2.23 on 2024-05-08 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20240417_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Aangemaakt op'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='finished_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Voltooid op'),
        ),
        migrations.AddField(
            model_name='import',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gestart op'),
        ),
    ]
