# Generated by Django 3.2.23 on 2024-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20240508_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Opmerking'),
        ),
    ]
