# Generated by Django 3.2.23 on 2024-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_import_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="import", name="processed_succesfully",),
        migrations.AddField(
            model_name="import",
            name="processed_successfully",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Succesvol verwerkt"
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="processed",
            field=models.PositiveIntegerField(default=0, verbose_name="Verwerkt"),
        ),
        migrations.AlterField(
            model_name="import",
            name="processed_invalid",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Niet succesvol verwerkt"
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Totaal"),
        ),
    ]
