# This is a compose file inteded for trying out the project locally and absolutely
# not suitable for production usage. The configuration here contains non-safe defaults.
#
# If you want to try out CMIS with Alfresco, see docker-compose.alfresco.yml

version: '3.4'

services:
  web.local:
    volumes:
      - ./src/openzaak/components/autorisaties/tests:/app/src/openzaak/components/autorisaties/tests
      - ./src/openzaak/components/zaken/tests:/app/src/openzaak/components/zaken/tests
      - ./src/openzaak/components/documenten/tests:/app/src/openzaak/components/documenten/tests
      - ./src/openzaak/components/catalogi/tests:/app/src/openzaak/components/catalogi/tests
      - ./src/openzaak/components/besluiten/tests:/app/src/openzaak/components/besluiten/tests
      - ./src/openzaak/import_data/tests/:/app/src/openzaak/import_data/tests
      - ./src/openzaak/tests/:/app/src/openzaak/tests
