# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-03-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_load_default_groups"),
    ]

    operations = []
