# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-04-12 09:43
from django.db import migrations


class Migration(migrations.Migration):
    # migration is made no-op in the 1.8.x release series - on 1.7.x this copied
    # over the configuration from auth_adfs to mozilla_oidc.
    # This migration is kept for historical reasons to not mess with the migration
    # history of existing installs. See #1139 for more context.

    dependencies = [
        ("accounts", "0005_auto_20200924_1410"),
        ("mozilla_django_oidc_db", "0006_openidconnectconfig_unique_id_claim"),
    ]
    operations = []
