# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-04-12 13:08
#
# Generated by commenting out the model in the django-auth-adfs-db package, running
# ``makemigrations django_auth_adfs_db`` and then copying over the operation into this
# empty migration file.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_migrate_from_auth_adfs_db"),
        ("django_auth_adfs_db", "0003_auto_20210323_1441"),
    ]

    operations = [
        migrations.DeleteModel(name="ADFSConfig"),
    ]
