# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2024 Dimpact
# Generated by Django 3.2.23 on 2024-05-21 13:30

import uuid

from django.db import migrations, models

import privates.fields
import privates.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Openstaand"),
                            ("active", "Actief"),
                            ("finished", "Voltooid"),
                            ("error", "Onderbroken"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[("documenten", "Enkelvoudige informatie objecten")],
                        max_length=30,
                        verbose_name="Type import",
                    ),
                ),
                (
                    "import_file",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        null=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="import/import-files/",
                        verbose_name="Import metadata bestand",
                    ),
                ),
                (
                    "report_file",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        null=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="import/report-files/",
                        verbose_name="Reportage bestand",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Opmerking")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "started_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gestart op"
                    ),
                ),
                (
                    "finished_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Voltooid op"
                    ),
                ),
                ("total", models.PositiveIntegerField(verbose_name="Totaal")),
                (
                    "processed",
                    models.PositiveIntegerField(default=0, verbose_name="Verwerkt"),
                ),
                (
                    "processed_successfully",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Succesvol verwerkt"
                    ),
                ),
                (
                    "processed_invalid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Niet succesvol verwerkt"
                    ),
                ),
            ],
        ),
    ]
