# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.17 on 2026-08-11 11:19

import privates.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='import_file',
            field=privates.fields.PrivateMediaFileField(blank=True, null=True, upload_to='import/import-files/', verbose_name='Import metadata bestand'),
        ),
        migrations.AlterField(
            model_name='import',
            name='report_file',
            field=privates.fields.PrivateMediaFileField(blank=True, null=True, upload_to='import/report-files/', verbose_name='Reportage bestand'),
        ),
    ]
