# Generated by Django 2.2.2 on 2019-08-02 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.fields
import vng_api_common.models
import vng_api_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Besluit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Identificatie van het besluit binnen de organisatie die het besluit heeft vastgesteld. Indien deze niet opgegeven is, dan wordt die gegenereerd.",
                        max_length=50,
                        validators=[
                            vng_api_common.validators.AlphanumericExcludingDiacritic()
                        ],
                        verbose_name="identificatie",
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    vng_api_common.fields.RSINField(
                        help_text="Het RSIN van de niet-natuurlijk persoon zijnde de organisatie die het besluit heeft vastgesteld.",
                        max_length=9,
                        verbose_name="verantwoordelijke organisatie",
                    ),
                ),
                (
                    "besluittype",
                    models.URLField(
                        help_text="URL-referentie naar het BESLUITTYPE (in de Catalogi API).",
                        verbose_name="besluittype",
                    ),
                ),
                (
                    "zaak",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar de ZAAK (in de Zaken API) waarvan dit besluit uitkomst is.",
                        verbose_name="zaak",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        help_text="De beslisdatum (AWB) van het besluit.",
                        validators=[vng_api_common.validators.UntilTodayValidator()],
                        verbose_name="datum",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Toelichting bij het besluit.",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "bestuursorgaan",
                    models.CharField(
                        blank=True,
                        help_text="Een orgaan van een rechtspersoon krachtens publiekrecht ingesteld of een persoon of college, met enig openbaar gezag bekleed onder wiens verantwoordelijkheid het besluit vastgesteld is.",
                        max_length=50,
                        verbose_name="bestuursorgaan",
                    ),
                ),
                (
                    "ingangsdatum",
                    models.DateField(
                        help_text="Ingangsdatum van de werkingsperiode van het besluit.",
                        verbose_name="ingangsdatum",
                    ),
                ),
                (
                    "vervaldatum",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop de werkingsperiode van het besluit eindigt.",
                        null=True,
                        verbose_name="vervaldatum",
                    ),
                ),
                (
                    "vervalreden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tijdelijk", "Besluit met tijdelijke werking"),
                            (
                                "ingetrokken_overheid",
                                "Besluit ingetrokken door overheid",
                            ),
                            (
                                "ingetrokken_belanghebbende",
                                "Besluit ingetrokken o.v.v. belanghebbende",
                            ),
                        ],
                        help_text="De omschrijving die aangeeft op grond waarvan het besluit is of komt te vervallen.",
                        max_length=30,
                        verbose_name="vervalreden",
                    ),
                ),
                (
                    "publicatiedatum",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop het besluit gepubliceerd wordt.",
                        null=True,
                        verbose_name="publicatiedatum",
                    ),
                ),
                (
                    "verzenddatum",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop het besluit verzonden is.",
                        null=True,
                        verbose_name="verzenddatum",
                    ),
                ),
                (
                    "uiterlijke_reactiedatum",
                    models.DateField(
                        blank=True,
                        help_text="De datum tot wanneer verweer tegen het besluit mogelijk is.",
                        null=True,
                        verbose_name="uiterlijke reactiedatum",
                    ),
                ),
                (
                    "_zaakbesluit",
                    models.URLField(
                        blank=True,
                        help_text="Link to the related object in the ZRC API",
                        verbose_name="zaakbesluit",
                    ),
                ),
            ],
            options={
                "verbose_name": "besluit",
                "verbose_name_plural": "besluiten",
                "unique_together": {("identificatie", "verantwoordelijke_organisatie")},
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BesluitInformatieObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "informatieobject",
                    models.URLField(
                        help_text="URL-referentie naar het INFORMATIEOBJECT (in de Documenten API) waarin (een deel van) het besluit beschreven is.",
                        max_length=1000,
                        verbose_name="informatieobject",
                    ),
                ),
                (
                    "aard_relatie",
                    models.CharField(
                        choices=[
                            ("hoort_bij", "Hoort bij, omgekeerd: kent"),
                            (
                                "legt_vast",
                                "Legt vast, omgekeerd: kan vastgelegd zijn als",
                            ),
                        ],
                        max_length=20,
                        verbose_name="aard relatie",
                    ),
                ),
                (
                    "besluit",
                    models.ForeignKey(
                        help_text="URL-referentie naar het BESLUIT.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="besluiten.Besluit",
                    ),
                ),
            ],
            options={
                "verbose_name": "besluitinformatieobject",
                "verbose_name_plural": "besluitinformatieobjecten",
                "unique_together": {("besluit", "informatieobject")},
            },
        ),
    ]
