# Generated by Django 2.2.2 on 2019-08-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0001_initial'),
        ('documenten', '0001_initial'),
        ('catalogi', '0001_initial'),
        ('besluiten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besluit',
            name='besluittype',
        ),
        migrations.RemoveField(
            model_name='besluit',
            name='zaak',
        ),
        migrations.AddField(
            model_name='besluit',
            name='besluittype_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogi.BesluitType'),
        ),
        migrations.AddField(
            model_name='besluit',
            name='besluittype_remote',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='besluit',
            name='zaak_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaken.Zaak'),
        ),
        migrations.AddField(
            model_name='besluit',
            name='zaak_remote',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='informatieobject_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documenten.EnkelvoudigInformatieObjectCanonical'),
        ),
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='informatieobject_remote',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='besluitinformatieobject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='besluitinformatieobject',
            name='informatieobject',
        ),
    ]
