# Generated by Django 2.2.4 on 2019-08-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('besluiten', '0002_auto_20190809_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluit',
            name='besluittype',
            field=models.ForeignKey(help_text='URL-referentie naar het BESLUITTYPE (in de Catalogi API).', on_delete=django.db.models.deletion.CASCADE, to='catalogi.BesluitType'),
        ),
        migrations.AlterField(
            model_name='besluit',
            name='zaak',
            field=models.ForeignKey(blank=True, help_text='URL-referentie naar de ZAAK (in de Zaken API) waarvan dit besluit uitkomst is.', null=True, on_delete=django.db.models.deletion.PROTECT, to='zaken.Zaak'),
        ),
    ]
