# Generated by Django 2.2.2 on 2019-08-07 10:21

from django.db import migrations, models
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ('besluiten', '0002_auto_20190806_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluit',
            name='besluittype',
            field=django_loose_fk.fields.FkOrURLField(fk_field='besluittype_local', help_text='URL-referentie naar het BESLUITTYPE (in de Catalogi API).', url_field='besluittype_remote', verbose_name='besluittype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besluit',
            name='zaak',
            field=django_loose_fk.fields.FkOrURLField(fk_field='zaak_local', help_text='URL-referentie naar de ZAAK (in de Zaken API) waarvan dit besluit uitkomst is.', url_field='zaak_remote', verbose_name='zaak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='_objectinformatieobject',
            field=models.URLField(blank=True, help_text='Link to the related object in the DRC API', verbose_name='objectinformatieobject'),
        ),
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='informatieobject',
            field=django_loose_fk.fields.FkOrURLField(fk_field='informatieobject_local', help_text='URL-referentie naar het INFORMATIEOBJECT (in de Documenten API) waarin (een deel van) het besluit beschreven is.', url_field='informatieobject_remote', verbose_name='informatieobject'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='besluit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, besluittype_local__isnull=True), ('besluittype_remote', '')), models.Q(('besluittype_local__isnull', True), models.Q(_negated=True, besluittype_remote='')), _connector='OR'), name='fk_or_url_filled'),
        ),
        migrations.AddConstraint(
            model_name='besluit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, zaak_local__isnull=True), ('zaak_remote', '')), models.Q(('zaak_local__isnull', True), models.Q(_negated=True, zaak_remote='')), _connector='OR'), name='fk_or_url_filled_zaak'),
        ),
        migrations.AddConstraint(
            model_name='besluitinformatieobject',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, informatieobject_local__isnull=True), ('informatieobject_remote', '')), models.Q(('informatieobject_local__isnull', True), models.Q(_negated=True, informatieobject_remote='')), _connector='OR'), name='fk_or_url_filled'),
        ),
    ]
