# Generated by Django 2.2.4 on 2019-09-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0003_auto_20190820_0945")]

    operations = [
        migrations.RemoveField(
            model_name="besluitinformatieobject", name="aard_relatie"
        )
    ]
