# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.24 on 2021-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0003_auto_20200124_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="besluit",
            name="identificatie",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het besluit binnen de organisatie die het besluit heeft vastgesteld. Indien deze niet opgegeven is, dan wordt die gegenereerd.",
                max_length=50,
                verbose_name="identificatie",
            ),
        ),
    ]
