# Generated by Django 2.2.4 on 2019-09-18 08:31

from django.db import migrations, models
import uuid
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0004_remove_besluitinformatieobject_aard_relatie")]

    operations = [
        migrations.AlterField(
            model_name="besluit",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke resource identifier (UUID4)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="besluit",
            name="verantwoordelijke_organisatie",
            field=vng_api_common.fields.RSINField(
                db_index=True,
                help_text="Het RSIN van de niet-natuurlijk persoon zijnde de organisatie die het besluit heeft vastgesteld.",
                max_length=9,
                verbose_name="verantwoordelijke organisatie",
            ),
        ),
    ]
