# Generated by Django 2.2.4 on 2019-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0005_auto_20190918_0831")]

    operations = [
        migrations.RenameField(
            model_name="besluit", old_name="besluittype", new_name="_besluittype"
        ),
        migrations.AddField(
            model_name="besluit",
            name="_besluittype_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar extern BESLUITTYPE (in een andere Catalogi API).",
                max_length=1000,
                verbose_name="extern besluittype",
            ),
        ),
    ]
