# Generated by Django 2.2.4 on 2019-09-24 12:11

from django.db import migrations, models

import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0006_auto_20190924_1208")]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="besluittype",
            field=django_loose_fk.fields.FkOrURLField(
                fk_field="_besluittype", url_field="_besluittype_url"
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="besluit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_besluittype__isnull=True, _negated=True),
                        ("_besluittype_url", ""),
                    ),
                    models.Q(
                        ("_besluittype__isnull", True),
                        models.Q(_besluittype_url="", _negated=True),
                    ),
                    _connector="OR",
                ),
                name="_besluittype_or__besluittype_url_filled",
            ),
        ),
    ]
