# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("besluiten", "0006_alter_besluit__besluittype"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_besluittype_base_url",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis deel van URL-referentie naar het extern BESLUITTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="besluit_besluittypen",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="_besluittype_relative_url",
            field=models.CharField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar het extern BESLUITTYPE (in een andere Catalogi API).",
                max_length=200,
                null=True,
                verbose_name="besluittype relative url",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="_zaak_base_url",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis deel van URL-referentie naar de externe ZAAK (in een andere Zaken API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="besluit_zaken",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="_zaak_relative_url",
            field=models.CharField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar de externe ZAAK (in een andere Zaken API).",
                max_length=200,
                null=True,
                verbose_name="zaak relative url",
            ),
        ),
        migrations.AddField(
            model_name="besluitinformatieobject",
            name="_informatieobject_base_url",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis deel van URL-referentie naar de externe API",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="besluitinformatieobject",
            name="_informatieobject_relative_url",
            field=models.CharField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar de externe API",
                max_length=500,
                null=True,
                verbose_name="informatieobject relative url",
            ),
        ),
    ]
