# Generated by Django 2.2.4 on 2019-09-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0007_auto_20190924_1211")]

    operations = [
        migrations.AlterField(
            model_name="besluit",
            name="_besluittype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het BESLUITTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.BesluitType",
            ),
        )
    ]
