# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-04 15:23

from django.db import migrations, models
import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0008_fill_besluit_service_urls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="besluit",
            name="besluiten_besluit__besluittype_or__besluittype_url_filled",
        ),
        migrations.RemoveField(
            model_name="besluit",
            name="_besluittype_url",
        ),
        migrations.AddConstraint(
            model_name="besluit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("_besluittype__isnull", True), _negated=True),
                        ("_besluittype_base_url__isnull", True),
                    ),
                    models.Q(
                        ("_besluittype__isnull", True),
                        models.Q(
                            ("_besluittype_base_url__isnull", True), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="_besluittype_or__besluittype_base_url_filled",
            ),
        ),
        migrations.RemoveField(model_name="besluit", name="_zaak_url"),
        migrations.RemoveConstraint(
            model_name="besluitinformatieobject",
            name="unique_besluit_and_external_document",
        ),
        migrations.AddConstraint(
            model_name="besluitinformatieobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("_informatieobject_relative_url__isnull", True), _negated=True
                ),
                fields=(
                    "besluit",
                    "_informatieobject_base_url",
                    "_informatieobject_relative_url",
                ),
                name="unique_besluit_and_external_document",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="besluitinformatieobject",
            name="besluiten_besluitinformatieobject__informatieobject_or__informatieobject_url_filled",
        ),
        migrations.RemoveField(
            model_name="besluitinformatieobject",
            name="_informatieobject_url",
        ),
        migrations.AddConstraint(
            model_name="besluitinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("_informatieobject__isnull", True), _negated=True),
                        ("_informatieobject_base_url__isnull", True),
                    ),
                    models.Q(
                        ("_informatieobject__isnull", True),
                        models.Q(
                            ("_informatieobject_base_url__isnull", True), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="_informatieobject_or__informatieobject_base_url_filled",
            ),
        ),
    ]
