# Generated by Django 3.2.14 on 2022-08-04 15:23

from django.db import migrations, models
import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0008_fill_besluit_service_urls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="besluit",
            name="besluiten_besluit__besluittype_or__besluittype_url_filled",
        ),
        migrations.RemoveField(model_name="besluit", name="_besluittype_url",),
        migrations.AddConstraint(
            model_name="besluit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("_besluittype__isnull", True), _negated=True),
                        ("_besluittype_base_url__isnull", True),
                    ),
                    models.Q(
                        ("_besluittype__isnull", True),
                        models.Q(
                            ("_besluittype_base_url__isnull", True), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="_besluittype_or__besluittype_base_url_filled",
            ),
        ),
        migrations.RemoveField(model_name="besluit", name="_zaak_url"),
    ]
