# Generated by Django 2.2.4 on 2019-10-10 15:44

from django.db import migrations, models

import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [("besluiten", "0009_auto_20191010_1514")]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_zaak_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar de ZAAK (in de Zaken API) waarvan dit besluit uitkomst is.",
                max_length=1000,
                verbose_name="externe zaak",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="zaak",
            field=django_loose_fk.fields.FkOrURLField(
                blank=True, fk_field="_zaak", null=True, url_field="_zaak_url"
            ),
        ),
    ]
