# Generated by Django 2.2.4 on 2019-11-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0010_auto_20191122_1923'),
        ('besluiten', '0010_auto_20191010_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name="besluitinformatieobject",
            old_name="informatieobject",
            new_name="_informatieobject",
        ),
        migrations.AlterUniqueTogether(
            name='besluitinformatieobject',
            unique_together={('besluit', '_informatieobject')},
        ),
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='_informatieobject_url',
            field=models.URLField(blank=True, help_text='URL to the informatieobject in an external API',
                                  max_length=1000, verbose_name='External informatieobject'),
        ),
    ]
