# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-15 17:39

from django.db import migrations, models
import zgw_consumers.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0010_alter_besluit_besluittype"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_besluittype_url",
            field=zgw_consumers.models.fields.ServiceUrlField(
                base_field="_besluittype_base_url",
                blank=True,
                null=True,
                relative_field="_besluittype_relative_url",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="_zaak_url",
            field=zgw_consumers.models.fields.ServiceUrlField(
                base_field="_zaak_base_url",
                blank=True,
                null=True,
                relative_field="_zaak_relative_url",
            ),
        ),
        migrations.AddField(
            model_name="besluitinformatieobject",
            name="_informatieobject_url",
            field=zgw_consumers.models.fields.ServiceUrlField(
                base_field="_informatieobject_base_url",
                blank=True,
                null=True,
                relative_field="_informatieobject_relative_url",
            ),
        ),
    ]
