# Generated by Django 2.2.4 on 2019-11-28 15:36

from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ('besluiten', '0011_auto_20191128_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluitinformatieobject',
            name='informatieobject',
            field=django_loose_fk.fields.FkOrURLField(blank=False, fk_field='_informatieobject', null=False, url_field='_informatieobject_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluitinformatieobject',
            name='_informatieobject',
            field=models.ForeignKey(blank=True,
                                    help_text='URL-referentie naar het INFORMATIEOBJECT (in de Documenten API) waarin (een deel van) het besluit beschreven is.',
                                    null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='documenten.EnkelvoudigInformatieObjectCanonical'),
        ),
        migrations.AddConstraint(
            model_name='besluitinformatieobject',
            constraint=models.UniqueConstraint(condition=models.Q(_informatieobject_url='', _negated=True), fields=('besluit', '_informatieobject_url'), name='unique_besluit_and_external_document'),
        ),
        migrations.AddConstraint(
            model_name='besluitinformatieobject',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_informatieobject__isnull=True, _negated=True), ('_informatieobject_url', '')), models.Q(('_informatieobject__isnull', True), models.Q(_informatieobject_url='', _negated=True)), _connector='OR'), name='_informatieobject_or__informatieobject_url_filled'),
        ),
    ]
