# Generated by Django 2.2.4 on 2019-12-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0018_auto_20191205_1607"),
        ("besluiten", "0012_auto_20191128_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_previous_zaak",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="previous_zaak",
                to="zaken.Zaak",
            ),
        ),
        migrations.AddField(
            model_name="besluit",
            name="_previous_zaak_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="externe previous zaak"
            ),
        ),
    ]
