# Generated by Django 2.2.4 on 2019-12-05 16:39

from django.db import migrations
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0013_auto_20191205_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="previous_zaak",
            field=django_loose_fk.fields.FkOrURLField(
                blank=True,
                fk_field="_previous_zaak",
                null=True,
                url_field="_previous_zaak_url",
            ),
        ),
    ]
