# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    run_before = (("zaken", "0018_auto_20221214_1009"),)
    dependencies = [
        ("besluiten", "0014_auto_20221116_1437"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="besluit",
                    name="zaak",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="besluit",
            name="_zaak",
            field=models.IntegerField(db_column="_zaak_id", null=True),
        ),
    ]
