# Generated by Django 2.2.4 on 2019-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0014_besluit_previous_zaak"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_zaakbesluit_url",
            field=models.URLField(
                blank=True,
                help_text="URL of related ZaakBesluit object in the other API",
                max_length=1000,
            ),
        ),
    ]
