# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0016_auto_20221214_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="besluit",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identificatie van het besluit binnen de organisatie die het besluit heeft vastgesteld. Indien deze niet opgegeven is, dan wordt die gegenereerd.",
                max_length=50,
                verbose_name="identificatie",
            ),
        ),
    ]
