# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0017_alter_besluit_identificatie"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluit",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="besluitinformatieobject",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
    ]
