# Generated by Django 5.2.17 on 2026-09-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besluiten', '0020_alter_besluit_besluittype'),
        ('zaken', '0053_remove_zaakeigenschap_zaken_zaakeigenschap__eigenschap_or__eigenschap_base_url_filled_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='besluit',
            name='besluiten_besluit__zaak_base_url_and__zaak_relative_url_filled',
        ),
        migrations.RenameField(
            model_name='besluit',
            old_name='_zaak',
            new_name='zaak',
        ),
        migrations.AlterField(
            model_name='besluit',
            name='zaak',
            field=models.ForeignKey(
                blank=True,
                help_text='URL-referentie naar de ZAAK (in de Zaken API) waarvan dit besluit uitkomst is.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='zaken.zaak',
            ),
        ),
        migrations.RemoveField(
            model_name='besluit',
            name='_zaak_base_url',
        ),
        migrations.RemoveField(
            model_name='besluit',
            name='_zaak_relative_url',
        ),
        migrations.RemoveField(
            model_name='besluit',
            name='_zaak_url',
        ),
]
