# Generated by Django 2.2.2 on 2019-08-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkelvoudiginformatieobject',
            name='informatieobjecttype',
            field=models.ForeignKey(help_text='Referentie naar het INFORMATIEOBJECTTYPE (in de Catalogi API).', on_delete=django.db.models.deletion.CASCADE, to='catalogi.InformatieObjectType'),
        ),
    ]
