# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-24 10:21

from django.db import migrations
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0002_auto_20200124_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="informatieobjecttype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_informatieobjecttype",
                null=False,
                url_field="_informatieobjecttype_url",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="besluit",
            field=django_loose_fk.fields.FkOrURLField(
                blank=True, fk_field="_besluit", null=True, url_field="_besluit_url"
            ),
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="zaak",
            field=django_loose_fk.fields.FkOrURLField(
                blank=True, fk_field="_zaak", null=True, url_field="_zaak_url"
            ),
        ),
    ]
