# Generated by Django 2.2.2 on 2019-08-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0002_auto_20190814_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectInformatieObject',
        ),
    ]
