# Generated by Django 2.2.4 on 2019-08-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("documenten", "0003_delete_objectinformatieobject")]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="informatieobjecttype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het INFORMATIEOBJECTTYPE (in de Catalogi API).",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.InformatieObjectType",
            ),
        )
    ]
