# Generated by Django 2.2.4 on 2019-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documenten", "0005_auto_20190822_1325")]

    operations = [
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.UniqueConstraint(
                fields=("informatieobject", "zaak"), name="unique_io_zaak"
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.UniqueConstraint(
                fields=("informatieobject", "besluit"), name="unique_io_besluit"
            ),
        ),
    ]
