# Generated by Django 2.2.4 on 2019-08-22 14:38

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0006_auto_20190822_1327"),
    ]

    operations = [
        CreateExtension("uuid-ossp"),
    ]
