# Generated by Django 2.2.4 on 2019-09-18 08:42

from django.db import migrations, models
import vng_api_common.fields
import vng_api_common.validators


class Migration(migrations.Migration):

    dependencies = [("documenten", "0006_auto_20190822_1327")]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="begin_registratie",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Een datumtijd in ISO8601 formaat waarop deze versie van het INFORMATIEOBJECT is aangemaakt of gewijzigd.",
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(
                db_index=True,
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd.",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT.",
                max_length=40,
                validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()],
            ),
        ),
        migrations.AlterField(
            model_name="gebruiksrechten",
            name="einddatum",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Einddatum van de periode waarin de gebruiksrechtvoorwaarden van toepassing zijn.",
                null=True,
                verbose_name="startdatum",
            ),
        ),
        migrations.AlterField(
            model_name="gebruiksrechten",
            name="startdatum",
            field=models.DateTimeField(
                db_index=True,
                help_text="Begindatum van de periode waarin de gebruiksrechtvoorwaarden van toepassing zijn. Doorgaans is de datum van creatie van het informatieobject de startdatum.",
                verbose_name="startdatum",
            ),
        ),
    ]
