# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0007_bestandsdeel"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="bestandsomvang",
            field=models.PositiveIntegerField(
                help_text="Aantal bytes dat de inhoud van INFORMATIEOBJECT in beslag neemt.",
                null=True,
                verbose_name="bestandsomvang",
            ),
        ),
    ]
