# Generated by Django 2.2.4 on 2019-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documenten", "0007_auto_20190918_0842")]

    operations = [
        migrations.AlterModelOptions(
            name="enkelvoudiginformatieobject",
            options={
                "verbose_name": "Enkelvoudige informatie object",
                "verbose_name_plural": "Enkelvoudige informatie objecten",
            },
        ),
        migrations.AddIndex(
            model_name="enkelvoudiginformatieobject",
            index=models.Index(
                fields=["canonical", "-versie"], name="documenten__canonic_31cc4e_idx"
            ),
        ),
    ]
