# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-29 10:06

from django.db import migrations, models
import openzaak.utils.fields
import zgw_consumers.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0008_fill_documenten_service_urls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enkelvoudiginformatieobject",
            name="documenten_enkelvoudiginformatieobject__informatieobjecttype_or__informatieobjecttype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject", name="check_type",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject", name="unique_io_zaak_external",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject", name="unique_io_besluit_external",
        ),
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject", name="_informatieobjecttype_url",
        ),
        migrations.RemoveField(
            model_name="objectinformatieobject", name="_besluit_url",
        ),
        migrations.RemoveField(model_name="objectinformatieobject", name="_zaak_url",),
        migrations.AddConstraint(
            model_name="enkelvoudiginformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("_informatieobjecttype__isnull", True), _negated=True
                        ),
                        ("_informatieobjecttype_base_url__isnull", True),
                    ),
                    models.Q(
                        ("_informatieobjecttype__isnull", True),
                        models.Q(
                            ("_informatieobjecttype_base_url__isnull", True),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="documenten_enkelvoudiginformatieobject__informatieobjecttype_or__informatieobjecttype_base_url_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(
                                ("_zaak__isnull", False),
                                ("_zaak_base_url__isnull", True),
                            ),
                            models.Q(
                                ("_zaak__isnull", True),
                                ("_zaak_base_url__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        ("_besluit__isnull", True),
                        ("_besluit_base_url__isnull", True),
                        ("object_type", "zaak"),
                    ),
                    models.Q(
                        models.Q(
                            models.Q(
                                ("_besluit__isnull", False),
                                ("_besluit_base_url__isnull", True),
                            ),
                            models.Q(
                                ("_besluit__isnull", True),
                                ("_besluit_base_url__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        ("_zaak__isnull", True),
                        ("_zaak_base_url__isnull", True),
                        ("object_type", "besluit"),
                    ),
                    _connector="OR",
                ),
                name="check_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("_zaak_base_url__isnull", False)),
                fields=("informatieobject", "_zaak_base_url", "_zaak_relative_url"),
                name="unique_io_zaak_external",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("_besluit_base_url__isnull", False)),
                fields=(
                    "informatieobject",
                    "_besluit_base_url",
                    "_besluit_relative_url",
                ),
                name="unique_io_besluit_external",
            ),
        ),
    ]
