# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-07-27 15:17

from django.db import migrations


def rewrite_file_size(apps, schema_editor):
    EnkelvoudigInformatieObject = apps.get_model(
        "documenten.EnkelvoudigInformatieObject"
    )

    docs = EnkelvoudigInformatieObject.objects.all()
    for doc in docs:
        # file gone - don't crash the migration
        if not doc.inhoud.storage.exists(doc.inhoud.name):
            continue
        doc.bestandsomvang = doc.inhoud.size
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0008_enkelvoudiginformatieobject_bestandsomvang"),
    ]

    operations = [
        migrations.RunPython(rewrite_file_size, migrations.RunPython.noop),
    ]
