# Generated by Django 2.2.4 on 2019-11-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0008_auto_20191104_1644"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enkelvoudiginformatieobject",
            options={
                "ordering": ["canonical", "-versie"],
                "verbose_name": "Enkelvoudige informatie object",
                "verbose_name_plural": "Enkelvoudige informatie objecten",
            },
        ),
    ]
