# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-08-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0009_auto_20220727_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestandsdeel",
            name="informatieobject_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="De unieke identifier van het gerelateerde EnkelvoudigInformatieObject in het achterliggende Document Management Systeem.",
                null=True,
                verbose_name="EnkelvoudigInformatieObject UUID",
            ),
        ),
        migrations.AlterField(
            model_name="bestandsdeel",
            name="informatieobject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bestandsdelen",
                to="documenten.enkelvoudiginformatieobjectcanonical",
            ),
        ),
    ]
