# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0011_bestandsdeel_datetime_created"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bestandsdeel",
            constraint=models.CheckConstraint(
                check=models.Q(("omvang__gt", 0)), name="check_omvang"
            ),
        ),
    ]
