# Generated by Django 2.2.4 on 2019-11-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0010_auto_20191122_1923"),
        ("documenten", "0011_auto_20191126_1602"),
    ]

    operations = []
