# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0012_bestandsdeel_check_omvang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestandsdeel",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="datetime created"
            ),
        ),
    ]
