# Generated by Django 2.2.4 on 2019-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0012_merge_20191128_1125"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enkelvoudiginformatieobject",
            options={
                "ordering": ["canonical", "-versie"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documenten",
            },
        ),
    ]
