# Generated by Django 2.2.9 on 2020-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0013_auto_20191129_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gebruiksrechten",
            name="einddatum",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Einddatum van de periode waarin de gebruiksrechtvoorwaarden van toepassing zijn.",
                null=True,
                verbose_name="einddatum",
            ),
        ),
    ]
