# Generated by Django 2.2.4 on 2019-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0013_auto_20191129_1552"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectinformatieobject",
            old_name="besluit",
            new_name="_besluit",
        ),
        migrations.RenameField(
            model_name="objectinformatieobject", old_name="zaak", new_name="_zaak",
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="_besluit_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="extern besluit"
            ),
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="_zaak_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="extern zaak"
            ),
        ),
    ]
