# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0014_auto_20220901_0943"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="objectinformatieobject", name="check_type",
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="verzoek",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="extern verzoek"
            ),
        ),
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("besluit", "Besluit"),
                    ("zaak", "Zaak"),
                    ("verzoek", "Verzoek"),
                ],
                help_text="Het type van het gerelateerde OBJECT.",
                max_length=100,
                verbose_name="objecttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(("_zaak__isnull", False), ("_zaak_url", "")),
                            models.Q(
                                models.Q(("_zaak_url", ""), _negated=True),
                                ("_zaak__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        ("_besluit__isnull", True),
                        ("_besluit_url", ""),
                        ("object_type", "zaak"),
                        ("verzoek", ""),
                    ),
                    models.Q(
                        models.Q(
                            models.Q(("_besluit__isnull", False), ("_besluit_url", "")),
                            models.Q(
                                models.Q(("_besluit_url", ""), _negated=True),
                                ("_besluit__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        ("_zaak__isnull", True),
                        ("_zaak_url", ""),
                        ("object_type", "besluit"),
                        ("verzoek", ""),
                    ),
                    models.Q(
                        models.Q(("verzoek", ""), _negated=True),
                        ("_besluit__isnull", True),
                        ("_besluit_url", ""),
                        ("_zaak__isnull", True),
                        ("_zaak_url", ""),
                        ("object_type", "verzoek"),
                    ),
                    _connector="OR",
                ),
                name="check_type",
            ),
        ),
    ]
