# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-09-02 08:40

from django.db import migrations, models

import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0014_auto_20220901_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectinformatieobject",
            name="_object_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="extern object"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="objectinformatieobject",
                    name="besluit",
                    field=django_loose_fk.fields.FkOrURLField(
                        blank=True,
                        fk_field="_besluit",
                        null=True,
                        url_field="_object_url",
                    ),
                ),
            ]
        ),
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("besluit", "Besluit"),
                    ("zaak", "Zaak"),
                    ("verzoek", "Verzoek"),
                ],
                help_text="Het type van het gerelateerde OBJECT.",
                max_length=100,
                verbose_name="objecttype",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="objectinformatieobject",
                    name="zaak",
                    field=django_loose_fk.fields.FkOrURLField(
                        blank=True, fk_field="_zaak", null=True, url_field="_object_url"
                    ),
                ),
            ]
        ),
    ]
