# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-09-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("documenten", "0017_auto_20220902_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="_informatieobjecttype_base_url",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern INFORMATIEOBJECTTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="_informatieobjecttype_relative_url",
            field=models.CharField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern INFORMATIEOBJECTTYPE (in een andere Catalogi API).",
                max_length=200,
                null=True,
                verbose_name="informatieobjecttype relative url",
            ),
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="_object_base_url",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern API.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="objectinformatieobject",
            name="_object_relative_url",
            field=models.CharField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern API.",
                max_length=1000,
                null=True,
                verbose_name="besluit relative url",
            ),
        ),
    ]
