# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-09-06 15:42

from django.db import migrations, models
import openzaak.utils.fields
import zgw_consumers.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0019_fill_documenten_service_urls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enkelvoudiginformatieobject",
            name="documenten_enkelvoudiginformatieobject__informatieobjecttype_or__informatieobjecttype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject",
            name="object_reference_fields_mutex",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject",
            name="correct_field_set_for_object_type",
        ),
        migrations.RemoveConstraint(
            model_name="objectinformatieobject",
            name="unique_io_object_external",
        ),
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject",
            name="_informatieobjecttype_url",
        ),
        migrations.RemoveField(
            model_name="objectinformatieobject",
            name="_object_url",
        ),
        migrations.AddConstraint(
            model_name="enkelvoudiginformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("_informatieobjecttype__isnull", True), _negated=True
                        ),
                        ("_informatieobjecttype_base_url__isnull", True),
                    ),
                    models.Q(
                        ("_informatieobjecttype__isnull", True),
                        models.Q(
                            ("_informatieobjecttype_base_url__isnull", True),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="documenten_enkelvoudiginformatieobject__informatieobjecttype_or__informatieobjecttype_base_url_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("_besluit__isnull", True),
                        ("_object_base_url__isnull", True),
                        ("_zaak__isnull", False),
                    ),
                    models.Q(
                        ("_besluit__isnull", False),
                        ("_object_base_url__isnull", True),
                        ("_zaak__isnull", True),
                    ),
                    models.Q(
                        ("_besluit__isnull", True),
                        ("_object_base_url__isnull", False),
                        ("_zaak__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="object_reference_fields_mutex",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("_zaak__isnull", False),
                            ("_object_base_url__isnull", False),
                            _connector="OR",
                        ),
                        ("object_type", "zaak"),
                    ),
                    models.Q(
                        models.Q(
                            ("_besluit__isnull", False),
                            ("_object_base_url__isnull", False),
                            _connector="OR",
                        ),
                        ("object_type", "besluit"),
                    ),
                    models.Q(
                        models.Q(("_object_base_url__isnull", False)),
                        ("object_type", "verzoek"),
                    ),
                    _connector="OR",
                ),
                name="correct_field_set_for_object_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("_object_base_url__isnull", False)),
                fields=("informatieobject", "_object_base_url", "_object_relative_url"),
                name="unique_io_object_external",
            ),
        ),
    ]
