# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-11-01 09:52

from django.db import migrations
import django.db.models.deletion
import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("documenten", "0021_auto_20220906_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="_informatieobjecttype_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern INFORMATIEOBJECTTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="_informatieobjecttype_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern INFORMATIEOBJECTTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="informatieobjecttype relative url",
            ),
        ),
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="_object_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern API.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="_object_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern API.",
                max_length=1000,
                null=True,
                verbose_name="besluit relative url",
            ),
        ),
    ]
