# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0022_auto_20221101_0952"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enkelvoudiginformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("_informatieobjecttype_base_url__isnull", True),
                        models.Q(
                            ("_informatieobjecttype_relative_url__isnull", True),
                            ("_informatieobjecttype_relative_url", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(
                            ("_informatieobjecttype_base_url__isnull", True),
                            _negated=True,
                        ),
                        models.Q(
                            models.Q(
                                ("_informatieobjecttype_relative_url__isnull", True),
                                ("_informatieobjecttype_relative_url", ""),
                                _connector="OR",
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="documenten_enkelvoudiginformatieobject__informatieobjecttype_base_url_and__informatieobjecttype_relative_url_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("_object_base_url__isnull", True),
                        models.Q(
                            ("_object_relative_url__isnull", True),
                            ("_object_relative_url", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("_object_base_url__isnull", True), _negated=True),
                        models.Q(
                            models.Q(
                                ("_object_relative_url__isnull", True),
                                ("_object_relative_url", ""),
                                _connector="OR",
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="documenten_objectinformatieobject__object_base_url_and__object_relative_url_filled",
            ),
        ),
    ]
