# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 13:30

import django.db.models.deletion
from django.db import migrations, models

import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0020_auto_20221214_1259"),
        ("documenten", "0024_auto_20221214_1322"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="objectinformatieobject",
                    name="zaak",
                    field=openzaak.utils.fields.FkOrServiceUrlField(
                        blank=True, fk_field="_zaak", null=True, url_field="_object_url"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="_zaak",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.zaak",
            ),
        ),
    ]
