# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0025_auto_20221214_1330"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestandsdeel",
            name="_voltooid",
            field=models.BooleanField(default=False),
        ),
    ]
