# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0027_auto_20230417_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="taal",
            field=models.CharField(
                help_text="Een ISO 639-2/B taalcode waarin de inhoud van het INFORMATIEOBJECT is vastgelegd. Voorbeeld: `dut`. Zie: https://www.iso.org/standard/4767.html",
                max_length=3,
            ),
        ),
    ]
