# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0029_verzending"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="verschijningsvorm",
            field=models.TextField(
                blank=True,
                help_text="De essentiële opmaakaspecten van een INFORMATIEOBJECT.",
            ),
        ),
    ]
