# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 3.2.23 on 2024-01-22 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0030_enkelvoudiginformatieobject_verschijningsvorm"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="trefwoorden",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, verbose_name="trefwoord"),
                blank=True,
                db_index=True,
                default=list,
                help_text="Een lijst van trefwoorden gescheiden door comma's.",
                size=None,
            ),
        ),
    ]
