# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-07-26 10:12

from django.core.management import call_command
from django.db import migrations


def forward(apps, schema_editor):

    call_command("delete_empty_eioc", "--noinput")


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0033_alter_enkelvoudiginformatieobject_identificatie"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
