# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-07-26 10:12

from django.db import migrations
from ..management.commands.delete_empty_eioc import delete_eioc_and_relations
import logging

logger = logging.getLogger(__name__)


def forward(apps, schema_editor):
    EnkelvoudigInformatieObjectCanonical = apps.get_model(
        "documenten", "EnkelvoudigInformatieObjectCanonical"
    )
    BesluitInformatieObject = apps.get_model("besluiten", "BesluitInformatieObject")
    ZaakInformatieObject = apps.get_model("zaken", "ZaakInformatieObject")

    delete_eioc_and_relations(
        eioc_model=EnkelvoudigInformatieObjectCanonical,
        bio_model=BesluitInformatieObject,
        zio_model=ZaakInformatieObject,
        log_func=logger.info,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0033_alter_enkelvoudiginformatieobject_identificatie"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
