# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.15 on 2024-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0034_delete_empty_eioc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestandsdeel",
            name="omvang",
            field=models.PositiveBigIntegerField(
                help_text="De grootte van dit specifieke bestandsdeel."
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="bestandsomvang",
            field=models.PositiveBigIntegerField(
                help_text="Aantal bytes dat de inhoud van INFORMATIEOBJECT in beslag neemt.",
                null=True,
                verbose_name="bestandsomvang",
            ),
        ),
    ]
