# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.1 on 2025-05-22 12:36

import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0035_alter_bestandsdeel_omvang_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT.",
                        max_length=40,
                    ),
                ),
                (
                    "bronorganisatie",
                    vng_api_common.fields.RSINField(
                        db_index=True,
                        help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd.",
                        max_length=9,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum en tijd waarop het document werd gereserveerd.",
                    ),
                ),
            ],
            options={
                "verbose_name": "gereserveerd document",
                "verbose_name_plural": "gereserveerde documenten",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bronorganisatie", "identificatie"),
                        name="bronorganisatie_identificatie_unique_together",
                    )
                ],
            },
        ),
    ]
