# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.13 on 2026-05-12 15:41

import privates.fields
import privates.storages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0036_reserveddocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestandsdeel",
            name="inhoud",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="De (binaire) bestandsinhoud van dit specifieke bestandsdeel.",
                max_length=255,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="part-uploads/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="inhoud",
            field=privates.fields.PrivateMediaFileField(
                max_length=255,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="uploads/%Y/%m/",
            ),
        ),
    ]
