# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.2.8 on 2025-12-18 13:29

import django.db.models.deletion
from django.db import migrations, models, connection


def set_latest_version(apps, _):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE documenten_enkelvoudiginformatieobjectcanonical t "
            "SET latest_version_id = latest.latest_version_id "
            "FROM ("
                "SELECT DISTINCT ON(canonical_id) "
                "canonical_id, eio.id AS latest_version_id "
                "FROM documenten_enkelvoudiginformatieobject AS eio "
                "ORDER BY canonical_id, eio.versie DESC"
            ") AS latest "
            "WHERE t.id = latest.canonical_id "
        )

class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0036_reserveddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobjectcanonical',
            name='latest_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_version_of', to='documenten.enkelvoudiginformatieobject'),
        ),
        migrations.RunPython(set_latest_version, migrations.RunPython.noop),
    ]
