# Generated by Django 5.2.8 on 2025-12-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0036_reserveddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobjectcanonical',
            name='latest_version',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_version_of', to='documenten.enkelvoudiginformatieobject'),
        ),
    ]
