# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.17 on 2026-08-11 11:19

import privates.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0037_enkelvoudiginformatieobjectcanonical_latest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestandsdeel',
            name='inhoud',
            field=privates.fields.PrivateMediaFileField(blank=True, help_text='De (binaire) bestandsinhoud van dit specifieke bestandsdeel.', upload_to='part-uploads/%Y/%m/'),
        ),
    ]
