# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0037_enkelvoudiginformatieobjectcanonical_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='inhoud_is_vervallen',
            field=models.BooleanField(blank=True, default=None, help_text='Geeft aan of de inhoud van het INFORMATIEOBJECT al dan niet vervallen, dus niet langer geldig is.\n* `true` De inhoud van het INFORMATIEOBJECT is vervallen.\n* `false` De inhoud van het INFORMATIEOBJECT is niet vervallen.', null=True, verbose_name='inhoud is vervallen'),
        ),
    ]
