# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0038_alter_bestandsdeel_inhoud'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='inhoud_is_vervallen',
            field=models.BooleanField(blank=True, default=None, help_text='Geeft aan of de inhoud van het INFORMATIEOBJECT al dan niet vervallen, dus niet langer geldig is.\n* `true` De inhoud van het INFORMATIEOBJECT is vervallen.\n* `false` De inhoud van het INFORMATIEOBJECT is niet vervallen.\n* `null` Het is nog niet bekend of bepaald of het INFORMATIEOBJECT wel of niet vervallen is.', null=True, verbose_name='inhoud is vervallen'),
        ),
    ]
