# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documenten", "0039_enkelvoudiginformatieobject_inhoud_is_vervallen"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="tonen_aan_initiator",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of het INFORMATIEOBJECT getoond mag worden aan de initiator van de zaak waarin het INFORMATIEOBJECT is opgenomen.",
                verbose_name="tonen aan initiator",
            ),
        ),
    ]
