# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0039_enkelvoudiginformatieobject_inhoud_is_vervallen"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="tonen_aan_initiator",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of het INFORMATIEOBJECT getoond mag worden aan de initiator van de zaak waarin het INFORMATIEOBJECT is opgenomen.",
                verbose_name="tonen aan initiator",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="verzenddatum",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het INFORMATIEOBJECT verzonden is, zoals deze op het INFORMATIEOBJECT vermeld is. Dit geldt voor zowel inkomende als uitgaande INFORMATIEOBJECTen. Eenzelfde informatieobject kan niet tegelijk inkomend en uitgaand zijn. Ontvangst en verzending is voorbehouden aan documenten die van of naar andere personen ontvangen of verzonden zijn waarbij die personen niet deel uit maken van de behandeling van de zaak waarin het document een rol speelt. Vervangt het gelijknamige attribuut uit Informatieobject.",
                null=True,
                verbose_name="verzenddatum",
            ),
        ),
    ]
