# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-10-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0040_enkelvoudiginformatieobject_tonen_aan_initiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='is_gereed_voor_publicatie',
            field=models.BooleanField(blank=True, default=None, help_text='Geeft aan of het INFORMATIEOBJECT gereed is voor publicatie. Dit veld mag `null` zijn om aan te geven dat de gereedheid voor publicatie nog niet bekend is.', null=True, verbose_name='Is gereed voor publicatie'),
        ),
    ]
