# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-10-02 07:51

from openzaak.components.documenten.storage import get_private_media_storage
import openzaak.components.documenten.validators
import privates.fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('documenten', '0040_enkelvoudiginformatieobject_tonen_aan_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkelvoudiginformatieobject',
            name='inhoud',
            field=privates.fields.PrivateMediaFileField(
                max_length=276, 
                upload_to='uploads/%Y/%m/', 
                storage=get_private_media_storage(),
                validators=[openzaak.components.documenten.validators.validate_inhoud_filename]
            ),
        ),
    ]
