# Generated by Django 2.2.2 on 2019-08-02 08:57

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.fields
import vng_api_common.models
import vng_api_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Huishouden",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        help_text="Uniek identificerend administratienummer van een huishouden zoals toegekend door de gemeente waarin het huishouden woonachtig is.",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NatuurlijkPersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inp_bsn",
                    vng_api_common.fields.BSNField(
                        blank=True,
                        help_text="Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.",
                        max_length=9,
                    ),
                ),
                (
                    "anp_identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NATUURLIJK PERSOON",
                        max_length=17,
                    ),
                ),
                (
                    "inp_a_nummer",
                    models.CharField(
                        blank=True,
                        help_text="Het administratienummer van de persoon, bedoeld in de Wet BRP",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="a-nummer-incorrect-format",
                                message="inpA_nummer must consist of 10 digits",
                                regex="^[1-9][0-9]{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "geslachtsnaam",
                    models.CharField(
                        blank=True,
                        help_text="De stam van de geslachtsnaam.",
                        max_length=200,
                    ),
                ),
                (
                    "voorvoegsel_geslachtsnaam",
                    models.CharField(blank=True, max_length=80),
                ),
                (
                    "voorletters",
                    models.CharField(
                        blank=True,
                        help_text="De verzameling letters die gevormd wordt door de eerste letter van alle in volgorde voorkomende voornamen.",
                        max_length=20,
                    ),
                ),
                (
                    "voornamen",
                    models.CharField(
                        blank=True,
                        help_text="Voornamen bij de naam die de persoon wenst te voeren.",
                        max_length=200,
                    ),
                ),
                (
                    "geslachtsaanduiding",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Man"), ("v", "Vrouw"), ("o", "Onbekend")],
                        help_text="Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.",
                        max_length=1,
                    ),
                ),
                ("geboortedatum", models.CharField(blank=True, max_length=18)),
            ],
            options={"verbose_name": "natuurlijk persoon"},
        ),
        migrations.CreateModel(
            name="NietNatuurlijkPersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn_nnp_id",
                    vng_api_common.fields.RSINField(
                        blank=True,
                        help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON",
                        max_length=9,
                    ),
                ),
                (
                    "ann_identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NIET-NATUURLIJK PERSOON",
                        max_length=17,
                    ),
                ),
                (
                    "statutaire_naam",
                    models.TextField(
                        blank=True,
                        help_text="Naam van de niet-natuurlijke persoon zoals deze is vastgelegd in de statuten (rechtspersoon) of in de vennootschapsovereenkomst is overeengekomen (Vennootschap onder firma of Commanditaire vennootschap).",
                        max_length=500,
                    ),
                ),
                (
                    "inn_rechtsvorm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("besloten_vennootschap", "Besloten Vennootschap"),
                            (
                                "cooperatie_europees_economische_samenwerking",
                                "Cooperatie, Europees Economische Samenwerking",
                            ),
                            (
                                "europese_cooperatieve_venootschap",
                                "Europese Cooperatieve Venootschap",
                            ),
                            (
                                "europese_naamloze_vennootschap",
                                "Europese Naamloze Vennootschap",
                            ),
                            ("kerkelijke_organisatie", "Kerkelijke Organisatie"),
                            ("naamloze_vennootschap", "Naamloze Vennootschap"),
                            (
                                "onderlinge_waarborg_maatschappij",
                                "Onderlinge Waarborg Maatschappij",
                            ),
                            (
                                "overig_privaatrechtelijke_rechtspersoon",
                                "Overig privaatrechtelijke rechtspersoon",
                            ),
                            ("stichting", "Stichting"),
                            ("vereniging", "Vereniging"),
                            ("vereniging_van_eigenaars", "Vereniging van Eigenaars"),
                            (
                                "publiekrechtelijke_rechtspersoon",
                                "Publiekrechtelijke Rechtspersoon",
                            ),
                            ("vennootschap_onder_firma", "Vennootschap onder Firma"),
                            ("maatschap", "Maatschap"),
                            ("rederij", "Rederij"),
                            (
                                "commanditaire_vennootschap",
                                "Commanditaire vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_binnen_eer",
                                "Kapitaalvennootschap binnen EER",
                            ),
                            (
                                "overige_buitenlandse_rechtspersoon_vennootschap",
                                "Overige buitenlandse rechtspersoon vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_buiten_eer",
                                "Kapitaalvennootschap buiten EER",
                            ),
                        ],
                        help_text="De juridische vorm van de NIET-NATUURLIJK PERSOON.",
                        max_length=50,
                    ),
                ),
                (
                    "bezoekadres",
                    models.CharField(
                        blank=True,
                        help_text="De gegevens over het adres van de NIET-NATUURLIJK PERSOON",
                        max_length=1000,
                    ),
                ),
            ],
            options={"verbose_name": "niet-natuurlijk persoon"},
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "betrokkene",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar een betrokkene gerelateerd aan de ZAAK.",
                        max_length=1000,
                    ),
                ),
                (
                    "betrokkene_type",
                    models.CharField(
                        choices=[
                            ("natuurlijk_persoon", "Natuurlijk persoon"),
                            ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                            ("vestiging", "Vestiging"),
                            ("organisatorische_eenheid", "Organisatorische eenheid"),
                            ("medewerker", "Medewerker"),
                        ],
                        help_text="Type van de `betrokkene`.",
                        max_length=100,
                    ),
                ),
                (
                    "roltype",
                    models.URLField(
                        help_text="URL-referentie naar een roltype binnen het ZAAKTYPE van de ZAAK.",
                        max_length=1000,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        editable=False,
                        help_text="Omschrijving van de aard van de ROL, afgeleid uit het ROLTYPE.",
                        max_length=20,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "omschrijving_generiek",
                    models.CharField(
                        choices=[
                            ("adviseur", "Adviseur"),
                            ("behandelaar", "Behandelaar"),
                            ("belanghebbende", "Belanghebbende"),
                            ("beslisser", "Beslisser"),
                            ("initiator", "Initiator"),
                            ("klantcontacter", "Klantcontacter"),
                            ("zaakcoordinator", "Zaakcoördinator"),
                            ("mede_initiator", "Mede-initiator"),
                        ],
                        editable=False,
                        help_text="Algemeen gehanteerde benaming van de aard van de ROL, afgeleid uit het ROLTYPE.",
                        max_length=80,
                    ),
                ),
                ("roltoelichting", models.TextField(max_length=1000)),
                (
                    "registratiedatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop dit object is geregistreerd.",
                        verbose_name="registratiedatum",
                    ),
                ),
                (
                    "indicatie_machtiging",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "gemachtigde",
                                "De betrokkene in de rol bij de zaak is door een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen",
                            ),
                            (
                                "machtiginggever",
                                "De betrokkene in de rol bij de zaak heeft een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen",
                            ),
                        ],
                        help_text="Indicatie machtiging",
                        max_length=40,
                    ),
                ),
            ],
            options={"verbose_name": "Rol", "verbose_name_plural": "Rollen"},
        ),
        migrations.CreateModel(
            name="WozDeelobject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer_woz_deel_object",
                    models.CharField(
                        help_text="Uniek identificatienummer voor het deelobject binnen een WOZ-object.",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zaak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        help_text="De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.",
                        max_length=40,
                        validators=[
                            vng_api_common.validators.AlphanumericExcludingDiacritic()
                        ],
                    ),
                ),
                (
                    "bronorganisatie",
                    vng_api_common.fields.RSINField(
                        help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                        max_length=9,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Een korte omschrijving van de zaak.",
                        max_length=80,
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een toelichting op de zaak.",
                        max_length=1000,
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        help_text="URL-referentie naar het ZAAKTYPE (in de Catalogi API) in de CATALOGUS waar deze voorkomt",
                        max_length=1000,
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "registratiedatum",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd. Indien deze niet opgegeven wordt, wordt de datum van vandaag gebruikt.",
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    vng_api_common.fields.RSINField(
                        help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                        max_length=9,
                    ),
                ),
                (
                    "startdatum",
                    models.DateField(
                        help_text="De datum waarop met de uitvoering van de zaak is gestart"
                    ),
                ),
                (
                    "einddatum",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop de uitvoering van de zaak afgerond is.",
                        null=True,
                    ),
                ),
                (
                    "einddatum_gepland",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop volgens de planning verwacht wordt dat de zaak afgerond wordt.",
                        null=True,
                    ),
                ),
                (
                    "uiterlijke_einddatum_afdoening",
                    models.DateField(
                        blank=True,
                        help_text="De laatste datum waarop volgens wet- en regelgeving de zaak afgerond dient te zijn.",
                        null=True,
                    ),
                ),
                (
                    "publicatiedatum",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop (het starten van) de zaak gepubliceerd is of wordt.",
                        null=True,
                        verbose_name="publicatiedatum",
                    ),
                ),
                (
                    "producten_of_diensten",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="URL naar product/dienst"
                        ),
                        blank=True,
                        default=list,
                        help_text="De producten en/of diensten die door de zaak worden voortgebracht. Dit zijn URLs naar de resources zoals die door de producten- en dienstencatalogus-API wordt ontsloten. De producten/diensten moeten bij het zaaktype vermeld zijn.",
                        size=None,
                    ),
                ),
                (
                    "communicatiekanaal",
                    models.URLField(
                        blank=True,
                        help_text="Het medium waarlangs de aanleiding om een zaak te starten is ontvangen. URL naar een communicatiekanaal in de VNG-Referentielijst van communicatiekanalen.",
                        max_length=1000,
                        verbose_name="communicatiekanaal",
                    ),
                ),
                (
                    "vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Aanduiding van de mate waarin het zaakdossier van de ZAAK voor de openbaarheid bestemd is.",
                        max_length=20,
                        verbose_name="vertrouwlijkheidaanduiding",
                    ),
                ),
                (
                    "betalingsindicatie",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "nvt",
                                "Er is geen sprake van te betalen, met de zaak gemoeide, kosten.",
                            ),
                            (
                                "nog_niet",
                                "De met de zaak gemoeide kosten zijn (nog) niet betaald.",
                            ),
                            (
                                "gedeeltelijk",
                                "De met de zaak gemoeide kosten zijn gedeeltelijk betaald.",
                            ),
                            (
                                "geheel",
                                "De met de zaak gemoeide kosten zijn geheel betaald.",
                            ),
                        ],
                        help_text="Indicatie of de, met behandeling van de zaak gemoeide, kosten betaald zijn door de desbetreffende betrokkene.",
                        max_length=20,
                        verbose_name="betalingsindicatie",
                    ),
                ),
                (
                    "laatste_betaaldatum",
                    models.DateTimeField(
                        blank=True,
                        help_text="De datum waarop de meest recente betaling is verwerkt van kosten die gemoeid zijn met behandeling van de zaak.",
                        null=True,
                        verbose_name="laatste betaaldatum",
                    ),
                ),
                (
                    "zaakgeometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Punt, lijn of (multi-)vlak geometrie-informatie.",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "verlenging_reden",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de reden voor het verlengen van de behandeling van de zaak.",
                        max_length=200,
                        verbose_name="reden verlenging",
                    ),
                ),
                (
                    "verlenging_duur",
                    vng_api_common.fields.DaysDurationField(
                        blank=True,
                        help_text="Het aantal werkbare dagen waarmee de doorlooptijd van de behandeling van de ZAAK is verlengd (of verkort) ten opzichte van de eerder gecommuniceerde doorlooptijd.",
                        max_duration=999,
                        min_duration=1,
                        null=True,
                        verbose_name="duur verlenging",
                    ),
                ),
                (
                    "opschorting_indicatie",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Aanduiding of de behandeling van de ZAAK tijdelijk is opgeschort.",
                        verbose_name="indicatie opschorting",
                    ),
                ),
                (
                    "opschorting_reden",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de reden voor het opschorten van de behandeling van de zaak.",
                        max_length=200,
                        verbose_name="reden opschorting",
                    ),
                ),
                (
                    "selectielijstklasse",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar de categorie in de gehanteerde 'Selectielijst Archiefbescheiden' die, gezien het zaaktype en het resultaattype van de zaak, bepalend is voor het archiefregime van de zaak.",
                        max_length=1000,
                        verbose_name="selectielijstklasse",
                    ),
                ),
                (
                    "archiefnominatie",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "blijvend_bewaren",
                                "Het zaakdossier moet bewaard blijven en op de Archiefactiedatum overgedragen worden naar een archiefbewaarplaats.",
                            ),
                            (
                                "vernietigen",
                                "Het zaakdossier moet op of na de Archiefactiedatum vernietigd worden.",
                            ),
                        ],
                        help_text="Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.",
                        max_length=40,
                        null=True,
                        verbose_name="archiefnominatie",
                    ),
                ),
                (
                    "archiefstatus",
                    models.CharField(
                        choices=[
                            (
                                "nog_te_archiveren",
                                "De zaak cq. het zaakdossier is nog niet als geheel gearchiveerd.",
                            ),
                            (
                                "gearchiveerd",
                                "De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt.",
                            ),
                            (
                                "gearchiveerd_procestermijn_onbekend",
                                "De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt maar de vernietigingsdatum kan nog niet bepaald worden.",
                            ),
                            (
                                "overgedragen",
                                "De zaak cq. het zaakdossier is overgebracht naar een archiefbewaarplaats.",
                            ),
                        ],
                        default="nog_te_archiveren",
                        help_text="Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.",
                        max_length=40,
                        verbose_name="archiefstatus",
                    ),
                ),
                (
                    "archiefactiedatum",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop het gearchiveerde zaakdossier vernietigd moet worden dan wel overgebracht moet worden naar een archiefbewaarplaats. Wordt automatisch berekend bij het aanmaken of wijzigen van een RESULTAAT aan deze ZAAK indien nog leeg.",
                        null=True,
                        verbose_name="archiefactiedatum",
                    ),
                ),
                (
                    "hoofdzaak",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL-referentie naar de ZAAK, waarom verzocht is door de initiator daarvan, die behandeld wordt in twee of meer separate ZAAKen waarvan de onderhavige ZAAK er één is.",
                        limit_choices_to={"hoofdzaak__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deelzaken",
                        to="zaken.Zaak",
                        verbose_name="is deelzaak van",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaak",
                "verbose_name_plural": "zaken",
                "unique_together": {("bronorganisatie", "identificatie")},
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ZaakObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "object",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar de resource die het OBJECT beschrijft.",
                        max_length=1000,
                    ),
                ),
                (
                    "relatieomschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de betrekking tussen de ZAAK en het OBJECT.",
                        max_length=80,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("adres", "Adres"),
                            ("besluit", "Besluit"),
                            ("buurt", "Buurt"),
                            ("enkelvoudig_document", "Enkelvoudig document"),
                            ("gemeente", "Gemeente"),
                            (
                                "gemeentelijke_openbare_ruimte",
                                "Gemeentelijke openbare ruimte",
                            ),
                            ("huishouden", "Huishouden"),
                            ("inrichtingselement", "Inrichtingselement"),
                            (
                                "kadastrale_onroerende_zaak",
                                "Kadastrale onroerende zaak",
                            ),
                            ("kunstwerkdeel", "Kunstwerkdeel"),
                            (
                                "maatschappelijke_activiteit",
                                "Maatschappelijke activiteit",
                            ),
                            ("medewerker", "Medewerker"),
                            ("natuurlijk_persoon", "Natuurlijk persoon"),
                            ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                            ("openbare_ruimte", "Openbare ruimte"),
                            ("organisatorische_eenheid", "Organisatorische eenheid"),
                            ("pand", "Pand"),
                            ("spoorbaandeel", "Spoorbaandeel"),
                            ("status", "Status"),
                            ("terreindeel", "Terreindeel"),
                            ("terrein_gebouwd_object", "Terrein gebouwd object"),
                            ("vestiging", "Vestiging"),
                            ("waterdeel", "Waterdeel"),
                            ("wegdeel", "Wegdeel"),
                            ("wijk", "Wijk"),
                            ("woonplaats", "Woonplaats"),
                            ("woz_deelobject", "Woz deel object"),
                            ("woz_object", "Woz object"),
                            ("woz_waarde", "Woz waarde"),
                            ("zakelijk_recht", "Zakelijk recht"),
                            ("overige", "Overige"),
                        ],
                        help_text="Beschrijft het type OBJECT gerelateerd aan de ZAAK. Als er geen passend type is, dan moet het type worden opgegeven onder `objectTypeOverige`.",
                        max_length=100,
                    ),
                ),
                (
                    "object_type_overige",
                    models.CharField(
                        blank=True,
                        help_text='Beschrijft het type OBJECT als `objectType` de waarde "overige" heeft.',
                        max_length=100,
                        validators=[django.core.validators.RegexValidator("[a-z\\_]+")],
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakobject",
                "verbose_name_plural": "zaakobjecten",
            },
        ),
        migrations.CreateModel(
            name="ZakelijkRecht",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "avg_aard",
                    models.CharField(
                        help_text="aanduiding voor de aard van het recht",
                        max_length=1000,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZakelijkRechtHeeftAlsGerechtigde",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zakelijk_recht",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heeft_als_gerechtigde",
                        to="zaken.ZakelijkRecht",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZaakKenmerk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kenmerk",
                    models.CharField(
                        help_text="Identificeert uniek de zaak in een andere administratie.",
                        max_length=40,
                    ),
                ),
                (
                    "bron",
                    models.CharField(
                        help_text="De aanduiding van de administratie waar het kenmerk op slaat.",
                        max_length=40,
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zaken.Zaak"
                    ),
                ),
            ],
            options={
                "verbose_name": "zaak kenmerk",
                "verbose_name_plural": "zaak kenmerken",
            },
        ),
        migrations.CreateModel(
            name="ZaakEigenschap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "eigenschap",
                    models.URLField(
                        help_text="URL-referentie naar de EIGENSCHAP (in de Catalogi API).",
                        max_length=1000,
                    ),
                ),
                (
                    "_naam",
                    models.CharField(
                        help_text="De naam van de EIGENSCHAP (overgenomen uit de Catalogi API).",
                        max_length=20,
                    ),
                ),
                ("waarde", models.TextField()),
                (
                    "zaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zaken.Zaak"
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakeigenschap",
                "verbose_name_plural": "zaakeigenschappen",
            },
        ),
        migrations.CreateModel(
            name="WozWaarde",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waardepeildatum",
                    models.CharField(
                        help_text="De datum waarnaar de waarde van het WOZ-object wordt bepaald.",
                        max_length=9,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WozObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "woz_object_nummer",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "woz_deelobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_onderdeel_van",
                        to="zaken.WozDeelobject",
                    ),
                ),
                (
                    "woz_warde",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_voor",
                        to="zaken.WozWaarde",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wozdeelobject",
            name="zaakobject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="zaken.ZaakObject"
            ),
        ),
        migrations.CreateModel(
            name="Woonplaats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "woonplaats_naam",
                    models.CharField(
                        help_text="De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS toegekende benaming.",
                        max_length=80,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wijk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wijk_code",
                    models.CharField(
                        help_text="De code behorende bij de naam van de wijk.",
                        max_length=2,
                    ),
                ),
                (
                    "wijk_naam",
                    models.CharField(
                        help_text="De naam van de wijk, zoals die door het CBS wordt gebruikt.",
                        max_length=40,
                    ),
                ),
                (
                    "gem_gemeente_code",
                    models.CharField(
                        help_text="Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid",
                        max_length=4,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wegdeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "naam",
                    models.TextField(
                        blank=True,
                        help_text="De benaming van het OBJECT",
                        max_length=500,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Waterdeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_waterdeel",
                    models.CharField(
                        choices=[
                            ("zee", "Zee"),
                            ("waterloop", "Waterloop"),
                            ("watervlakte", "Watervlakte"),
                            ("greppel_droge_sloot", "Greppel, droge sloot"),
                        ],
                        help_text="Specificatie van het soort water",
                        max_length=50,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "naam",
                    models.TextField(
                        blank=True,
                        help_text="De benaming van het OBJECT",
                        max_length=500,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vestiging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vestigings_nummer",
                    models.CharField(
                        blank=True,
                        help_text="Een korte unieke aanduiding van de Vestiging.",
                        max_length=24,
                    ),
                ),
                (
                    "handelsnaam",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, max_length=625),
                        default=list,
                        help_text="De naam van de vestiging waaronder gehandeld wordt.",
                        size=None,
                    ),
                ),
                (
                    "rol",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Rol",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
            options={"verbose_name": "vestiging"},
        ),
        migrations.CreateModel(
            name="TerreinGebouwdObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "huishouden",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_gehuisvest_in",
                        to="zaken.Huishouden",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Terreindeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "naam",
                    models.TextField(
                        blank=True,
                        help_text="De benaming van het OBJECT",
                        max_length=500,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubVerblijfBuitenland",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lnd_landcode",
                    models.CharField(
                        help_text="De code, behorende bij de landnaam, zoals opgenomen in de Land/Gebied-tabel van de BRP.",
                        max_length=4,
                    ),
                ),
                (
                    "lnd_landnaam",
                    models.CharField(
                        help_text="De naam van het land, zoals opgenomen in de Land/Gebied-tabel van de BRP.",
                        max_length=40,
                    ),
                ),
                ("sub_adres_buitenland_1", models.CharField(blank=True, max_length=35)),
                ("sub_adres_buitenland_2", models.CharField(blank=True, max_length=35)),
                ("sub_adres_buitenland_3", models.CharField(blank=True, max_length=35)),
                (
                    "natuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="zaken.NatuurlijkPersoon",
                    ),
                ),
                (
                    "nietnatuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="zaken.NietNatuurlijkPersoon",
                    ),
                ),
                (
                    "vestiging",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="zaken.Vestiging",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spoorbaandeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("breedspoor", "breedspoor"),
                            ("normaalspoor", "normaalspoor"),
                            ("smalspoor", "smalspoor"),
                            ("spoorbaan", "spoorbaan"),
                        ],
                        help_text="Specificatie van het soort Spoorbaan",
                        max_length=40,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "naam",
                    models.TextField(
                        blank=True,
                        help_text="De benaming van het OBJECT",
                        max_length=500,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rol",
            name="zaak",
            field=models.ForeignKey(
                help_text="URL-referentie naar de ZAAK.",
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.Zaak",
            ),
        ),
        migrations.CreateModel(
            name="Resultaat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "resultaattype",
                    models.URLField(
                        help_text="URL-referentie naar het RESULTAATTYPE (in de Catalogi API).",
                        max_length=1000,
                        verbose_name="resultaattype",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een toelichting op wat het resultaat van de zaak inhoudt.",
                        max_length=1000,
                    ),
                ),
                (
                    "zaak",
                    models.OneToOneField(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={"verbose_name": "resultaat", "verbose_name_plural": "resultaten"},
        ),
        migrations.CreateModel(
            name="RelevanteZaakRelatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000, verbose_name="URL-referentie naar de ZAAK."
                    ),
                ),
                (
                    "aard_relatie",
                    models.CharField(
                        choices=[
                            (
                                "vervolg",
                                "De andere zaak gaf aanleiding tot het starten van de onderhanden zaak.",
                            ),
                            (
                                "onderwerp",
                                "De andere zaak is relevant voor cq. is onderwerp van de onderhanden zaak.",
                            ),
                            (
                                "bijdrage",
                                "Aan het bereiken van de uitkomst van de andere zaak levert de onderhanden zaak een bijdrage.",
                            ),
                        ],
                        help_text="Benamingen van de aard van de relaties van andere zaken tot (onderhanden) zaken.",
                        max_length=20,
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relevante_andere_zaken",
                        to="zaken.Zaak",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Overige",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overige_data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganisatorischeEenheid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Een korte identificatie van de organisatorische eenheid.",
                        max_length=24,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        blank=True,
                        help_text="De feitelijke naam van de organisatorische eenheid.",
                        max_length=50,
                    ),
                ),
                ("is_gehuisvest_in", models.CharField(blank=True, max_length=24)),
                (
                    "rol",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Rol",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
            options={"verbose_name": "organisatorische eenheid"},
        ),
        migrations.CreateModel(
            name="OpenbareRuimte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                ("wpl_woonplaats_naam", models.CharField(max_length=80)),
                (
                    "gor_openbare_ruimte_naam",
                    models.CharField(
                        help_text="Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming",
                        max_length=80,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nietnatuurlijkpersoon",
            name="rol",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zaken.Rol"
            ),
        ),
        migrations.AddField(
            model_name="nietnatuurlijkpersoon",
            name="zaakobject",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.ZaakObject",
            ),
        ),
        migrations.AddField(
            model_name="nietnatuurlijkpersoon",
            name="zakelijk_rechtHeeft_als_gerechtigde",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.ZakelijkRechtHeeftAlsGerechtigde",
            ),
        ),
        migrations.AddField(
            model_name="natuurlijkpersoon",
            name="rol",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zaken.Rol"
            ),
        ),
        migrations.AddField(
            model_name="natuurlijkpersoon",
            name="zaakobject",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.ZaakObject",
            ),
        ),
        migrations.AddField(
            model_name="natuurlijkpersoon",
            name="zakelijk_rechtHeeft_als_gerechtigde",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.ZakelijkRechtHeeftAlsGerechtigde",
            ),
        ),
        migrations.CreateModel(
            name="Medewerker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Een korte unieke aanduiding van de MEDEWERKER.",
                        max_length=24,
                    ),
                ),
                (
                    "achternaam",
                    models.CharField(
                        blank=True,
                        help_text="De achternaam zoals de MEDEWERKER die in het dagelijkse verkeer gebruikt.",
                        max_length=200,
                    ),
                ),
                (
                    "voorletters",
                    models.CharField(
                        blank=True,
                        help_text="De verzameling letters die gevormd wordt door de eerste letter van alle in volgorde voorkomende voornamen.",
                        max_length=20,
                    ),
                ),
                (
                    "voorvoegsel_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Dat deel van de geslachtsnaam dat voorkomt in Tabel 36 (GBA), voorvoegseltabel, en door een spatie van de geslachtsnaam is",
                        max_length=10,
                    ),
                ),
                (
                    "rol",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Rol",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
            options={"verbose_name": "medewerker"},
        ),
        migrations.CreateModel(
            name="MaatschappelijkeActiviteit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kvk_nummer",
                    models.CharField(
                        help_text="Landelijk uniek identificerend administratienummer van een MAATSCHAPPELIJKE ACTIVITEIT zoals toegewezen door de Kamer van Koophandel (KvK).",
                        max_length=8,
                    ),
                ),
                (
                    "handelsnaam",
                    models.CharField(
                        help_text="De naam waaronder de onderneming handelt.",
                        max_length=200,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kunstwerkdeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("keermuur", "Keermuur"),
                            ("overkluizing", "Overkluizing"),
                            ("duiker", "Duiker"),
                            ("faunavoorziening", "Faunavoorziening"),
                            ("vispassage", "Vispassage"),
                            ("bodemval", "Bodemval"),
                            ("coupure", "Coupure"),
                            ("ponton", "Ponton"),
                            ("voorde", "Voorde"),
                            ("hoogspanningsmast", "Hoogspanningsmast"),
                            ("gemaal", "Gemaal"),
                            ("perron", "Perron"),
                            ("sluis", "Sluis"),
                            ("strekdam", "Strekdam"),
                            ("steiger", "Steiger"),
                            ("stuw", "Stuw"),
                        ],
                        help_text="Specificatie van het soort Kunstwerk waartoe het kunstwerkdeel behoort.",
                        max_length=40,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                ("naam", models.CharField(max_length=80)),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KlantContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke aanduiding van een KLANTCONTACT",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "datumtijd",
                    models.DateTimeField(
                        help_text="De datum en het tijdstip waarop het KLANTCONTACT begint"
                    ),
                ),
                (
                    "kanaal",
                    models.CharField(
                        blank=True,
                        help_text="Het communicatiekanaal waarlangs het KLANTCONTACT gevoerd wordt",
                        max_length=20,
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "klantcontact",
                "verbose_name_plural": "klantcontacten",
            },
        ),
        migrations.CreateModel(
            name="KadastraleOnroerendeZaak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kadastrale_identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "kadastrale_aanduiding",
                    models.CharField(
                        help_text="De typering van de kadastrale aanduiding van een onroerende zaak conform Kadaster",
                        max_length=1000,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
                (
                    "zakelijk_recht",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heeft_betrekking_op",
                        to="zaken.ZakelijkRecht",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inrichtingselement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bak", "Bak"),
                            ("bord", "Bord"),
                            ("installatie", "Installatie"),
                            ("kast", "Kast"),
                            ("mast", "Mast"),
                            ("paal", "Paal"),
                            ("sensor", "Sensor"),
                            ("straatmeubilair", "Straatmeubilair"),
                            ("waterinrichtingselement", "Waterinrichtingselement"),
                            ("weginrichtingselement", "Weginrichtingselement"),
                        ],
                        help_text="Specificatie van de aard van het inrichtingselement.",
                        max_length=30,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "naam",
                    models.TextField(
                        blank=True,
                        help_text="De benaming van het OBJECT",
                        max_length=500,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="huishouden",
            name="zaakobject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="zaken.ZaakObject"
            ),
        ),
        migrations.CreateModel(
            name="GemeentelijkeOpenbareRuimte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "openbare_ruimte_naam",
                    models.CharField(
                        help_text="Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming",
                        max_length=80,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gemeente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemeente_naam",
                    models.CharField(
                        help_text="De officiële door de gemeente vastgestelde gemeentenaam.",
                        max_length=80,
                    ),
                ),
                (
                    "gemeente_code",
                    models.CharField(
                        help_text="Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid",
                        max_length=4,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                ("wpl_woonplaats_naam", models.CharField(max_length=80)),
                (
                    "gor_openbare_ruimte_naam",
                    models.CharField(
                        help_text="Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming",
                        max_length=80,
                    ),
                ),
                (
                    "huisnummer",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)]
                    ),
                ),
                ("huisletter", models.CharField(blank=True, max_length=1)),
                ("huisnummertoevoeging", models.CharField(blank=True, max_length=4)),
                ("postcode", models.CharField(blank=True, max_length=7)),
                ("num_identificatie", models.CharField(blank=True, max_length=100)),
                ("locatie_omschrijving", models.CharField(blank=True, max_length=1000)),
                ("locatie_aanduiding", models.CharField(blank=True, max_length=100)),
                (
                    "natuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verblijfsadres",
                        to="zaken.NatuurlijkPersoon",
                    ),
                ),
                (
                    "terreingebouwdobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adres_aanduiding_grp",
                        to="zaken.TerreinGebouwdObject",
                    ),
                ),
                (
                    "vestiging",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verblijfsadres",
                        to="zaken.Vestiging",
                    ),
                ),
                (
                    "wozobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aanduiding_woz_object",
                        to="zaken.WozObject",
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZaakInformatieObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "informatieobject",
                    models.URLField(
                        help_text="URL-referentie naar het INFORMATIEOBJECT (in de Documenten API), waar ook de relatieinformatie opgevraagd kan worden.",
                        max_length=1000,
                        verbose_name="informatieobject",
                    ),
                ),
                (
                    "aard_relatie",
                    models.CharField(
                        choices=[
                            ("hoort_bij", "Hoort bij, omgekeerd: kent"),
                            (
                                "legt_vast",
                                "Legt vast, omgekeerd: kan vastgelegd zijn als",
                            ),
                        ],
                        max_length=20,
                        verbose_name="aard relatie",
                    ),
                ),
                (
                    "titel",
                    models.CharField(
                        blank=True,
                        help_text="De naam waaronder het INFORMATIEOBJECT binnen het OBJECT bekend is.",
                        max_length=200,
                        verbose_name="titel",
                    ),
                ),
                (
                    "beschrijving",
                    models.TextField(
                        blank=True,
                        help_text="Een op het object gerichte beschrijving van de inhoud vanhet INFORMATIEOBJECT.",
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "registratiedatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop de behandelende organisatie het INFORMATIEOBJECT heeft geregistreerd bij het OBJECT. Geldige waardes zijn datumtijden gelegen op of voor de huidige datum en tijd.",
                        verbose_name="registratiedatum",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakinformatieobject",
                "verbose_name_plural": "zaakinformatieobjecten",
                "unique_together": {("zaak", "informatieobject")},
            },
        ),
        migrations.CreateModel(
            name="ZaakBesluit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "besluit",
                    models.URLField(
                        help_text="URL-referentie naar het BESLUIT (in de Besluiten API), waar ook de relatieinformatie opgevraagd kan worden.",
                        max_length=1000,
                        verbose_name="besluit",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zaken.Zaak"
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakbesluit",
                "verbose_name_plural": "zaakbesluiten",
                "unique_together": {("zaak", "besluit")},
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "statustype",
                    models.URLField(
                        help_text="URL-referentie naar het STATUSTYPE (in de Catalogi API).",
                        max_length=1000,
                        verbose_name="statustype",
                    ),
                ),
                (
                    "datum_status_gezet",
                    models.DateTimeField(
                        help_text="De datum waarop de ZAAK de status heeft verkregen."
                    ),
                ),
                (
                    "statustoelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een, voor de initiator van de zaak relevante, toelichting op de status van een zaak.",
                        max_length=1000,
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statussen",
                "unique_together": {("zaak", "datum_status_gezet")},
            },
        ),
        migrations.CreateModel(
            name="Buurt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buurt_code",
                    models.CharField(
                        help_text="De code behorende bij de naam van de buurt",
                        max_length=2,
                    ),
                ),
                (
                    "buurt_naam",
                    models.CharField(
                        help_text="De naam van de buurt, zoals die door het CBS wordt gebruikt.",
                        max_length=40,
                    ),
                ),
                (
                    "gem_gemeente_code",
                    models.CharField(
                        help_text="Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid",
                        max_length=4,
                    ),
                ),
                (
                    "wyk_wijk_code",
                    models.CharField(
                        help_text="De code behorende bij de naam van de wijk",
                        max_length=2,
                    ),
                ),
                (
                    "zaakobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.ZaakObject",
                    ),
                ),
            ],
            options={"unique_together": {("buurt_code", "wyk_wijk_code")}},
        ),
    ]
