# Generated by Django 2.2.2 on 2019-08-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='_objectinformatieobject',
            field=models.URLField(blank=True, help_text='Link to the related object in the DRC API', verbose_name='objectinformatieobject'),
        ),
    ]
