# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-24 10:39

from django.db import migrations
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevantezaakrelatie",
            name="url",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_relevant_zaak",
                null=False,
                url_field="_relevant_zaak_url",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultaat",
            name="resultaattype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_resultaattype",
                null=False,
                url_field="_resultaattype_url",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rol",
            name="roltype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False, fk_field="_roltype", null=False, url_field="_roltype_url"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="statustype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_statustype",
                null=False,
                url_field="_statustype_url",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaak",
            name="zaaktype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False, fk_field="_zaaktype", null=False, url_field="_zaaktype_url"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaakbesluit",
            name="besluit",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False, fk_field="_besluit", null=False, url_field="_besluit_url"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaakeigenschap",
            name="eigenschap",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_eigenschap",
                null=False,
                url_field="_eigenschap_url",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaakinformatieobject",
            name="informatieobject",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_informatieobject",
                null=False,
                url_field="_informatieobject_url",
            ),
            preserve_default=False,
        ),
    ]
