# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.10 on 2020-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0002_auto_20200124_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="omschrijving",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Omschrijving van de aard van de ROL, afgeleid uit het ROLTYPE.",
                max_length=100,
                verbose_name="omschrijving",
            ),
        ),
    ]
