# Generated by Django 2.2.2 on 2019-08-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zaken", "0002_auto_20190812_1418")]

    operations = [migrations.DeleteModel(name="ZaakBesluit")]
