# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 2.2.25 on 2022-02-01 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0004_auto_20210628_1514"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakContactMoment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "contactmoment",
                    models.URLField(
                        help_text="URL-referentie naar het CONTACTMOMENT (in de CMC API)",
                        max_length=1000,
                        verbose_name="contactmoment",
                    ),
                ),
                (
                    "_objectcontactmoment",
                    models.URLField(
                        blank=True,
                        help_text="Link to the related object in the CMC API",
                        verbose_name="objectcontactmoment",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "contactmoment",
                "verbose_name_plural": "contactmomenten",
                "unique_together": {("zaak", "contactmoment")},
            },
        ),
    ]
