# Generated by Django 2.2.24 on 2021-08-18 08:50
# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0004_auto_20210628_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaakobject",
            name="object_type_overige_definitie",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text='Verwijzing naar het schema van het type OBJECT als `objectType` de waarde "overige" heeft.',
                null=True,
                verbose_name="definitie object type overige",
            ),
        ),
    ]
