# Generated by Django 2.2.4 on 2019-09-18 08:26

import django.core.validators
from django.db import migrations, models
import vng_api_common.fields
import vng_api_common.validators


class Migration(migrations.Migration):

    dependencies = [("zaken", "0004_auto_20190820_0945")]

    operations = [
        migrations.AlterField(
            model_name="medewerker",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Een korte unieke aanduiding van de MEDEWERKER.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="natuurlijkpersoon",
            name="anp_identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NATUURLIJK PERSOON",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="natuurlijkpersoon",
            name="inp_a_nummer",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Het administratienummer van de persoon, bedoeld in de Wet BRP",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="a-nummer-incorrect-format",
                        message="inpA_nummer must consist of 10 digits",
                        regex="^[1-9][0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="natuurlijkpersoon",
            name="inp_bsn",
            field=vng_api_common.fields.BSNField(
                blank=True,
                db_index=True,
                help_text="Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="nietnatuurlijkpersoon",
            name="ann_identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NIET-NATUURLIJK PERSOON",
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="nietnatuurlijkpersoon",
            name="inn_nnp_id",
            field=vng_api_common.fields.RSINField(
                blank=True,
                db_index=True,
                help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Een korte identificatie van de organisatorische eenheid.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="betrokkene",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="URL-referentie naar een betrokkene gerelateerd aan de ZAAK.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="betrokkene_type",
            field=models.CharField(
                choices=[
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("vestiging", "Vestiging"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("medewerker", "Medewerker"),
                ],
                db_index=True,
                help_text="Type van de `betrokkene`.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="omschrijving",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Omschrijving van de aard van de ROL, afgeleid uit het ROLTYPE.",
                max_length=20,
                verbose_name="omschrijving",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="omschrijving_generiek",
            field=models.CharField(
                choices=[
                    ("adviseur", "Adviseur"),
                    ("behandelaar", "Behandelaar"),
                    ("belanghebbende", "Belanghebbende"),
                    ("beslisser", "Beslisser"),
                    ("initiator", "Initiator"),
                    ("klantcontacter", "Klantcontacter"),
                    ("zaakcoordinator", "Zaakcoördinator"),
                    ("mede_initiator", "Mede-initiator"),
                ],
                db_index=True,
                editable=False,
                help_text="Algemeen gehanteerde benaming van de aard van de ROL, afgeleid uit het ROLTYPE.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="vestiging",
            name="vestigings_nummer",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Een korte unieke aanduiding van de Vestiging.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="archiefactiedatum",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="De datum waarop het gearchiveerde zaakdossier vernietigd moet worden dan wel overgebracht moet worden naar een archiefbewaarplaats. Wordt automatisch berekend bij het aanmaken of wijzigen van een RESULTAAT aan deze ZAAK indien nog leeg.",
                null=True,
                verbose_name="archiefactiedatum",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="archiefnominatie",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "blijvend_bewaren",
                        "Het zaakdossier moet bewaard blijven en op de Archiefactiedatum overgedragen worden naar een archiefbewaarplaats.",
                    ),
                    (
                        "vernietigen",
                        "Het zaakdossier moet op of na de Archiefactiedatum vernietigd worden.",
                    ),
                ],
                db_index=True,
                help_text="Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.",
                max_length=40,
                null=True,
                verbose_name="archiefnominatie",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="archiefstatus",
            field=models.CharField(
                choices=[
                    (
                        "nog_te_archiveren",
                        "De zaak cq. het zaakdossier is nog niet als geheel gearchiveerd.",
                    ),
                    (
                        "gearchiveerd",
                        "De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt.",
                    ),
                    (
                        "gearchiveerd_procestermijn_onbekend",
                        "De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt maar de vernietigingsdatum kan nog niet bepaald worden.",
                    ),
                    (
                        "overgedragen",
                        "De zaak cq. het zaakdossier is overgebracht naar een archiefbewaarplaats.",
                    ),
                ],
                db_index=True,
                default="nog_te_archiveren",
                help_text="Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.",
                max_length=40,
                verbose_name="archiefstatus",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.",
                max_length=40,
                validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()],
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="startdatum",
            field=models.DateField(
                db_index=True,
                help_text="De datum waarop met de uitvoering van de zaak is gestart",
            ),
        ),
        migrations.AlterField(
            model_name="zaakobject",
            name="object",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="URL-referentie naar de resource die het OBJECT beschrijft.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="zaakobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("adres", "Adres"),
                    ("besluit", "Besluit"),
                    ("buurt", "Buurt"),
                    ("enkelvoudig_document", "Enkelvoudig document"),
                    ("gemeente", "Gemeente"),
                    ("gemeentelijke_openbare_ruimte", "Gemeentelijke openbare ruimte"),
                    ("huishouden", "Huishouden"),
                    ("inrichtingselement", "Inrichtingselement"),
                    ("kadastrale_onroerende_zaak", "Kadastrale onroerende zaak"),
                    ("kunstwerkdeel", "Kunstwerkdeel"),
                    ("maatschappelijke_activiteit", "Maatschappelijke activiteit"),
                    ("medewerker", "Medewerker"),
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("openbare_ruimte", "Openbare ruimte"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("pand", "Pand"),
                    ("spoorbaandeel", "Spoorbaandeel"),
                    ("status", "Status"),
                    ("terreindeel", "Terreindeel"),
                    ("terrein_gebouwd_object", "Terrein gebouwd object"),
                    ("vestiging", "Vestiging"),
                    ("waterdeel", "Waterdeel"),
                    ("wegdeel", "Wegdeel"),
                    ("wijk", "Wijk"),
                    ("woonplaats", "Woonplaats"),
                    ("woz_deelobject", "Woz deel object"),
                    ("woz_object", "Woz object"),
                    ("woz_waarde", "Woz waarde"),
                    ("zakelijk_recht", "Zakelijk recht"),
                    ("overige", "Overige"),
                ],
                db_index=True,
                help_text="Beschrijft het type OBJECT gerelateerd aan de ZAAK. Als er geen passend type is, dan moet het type worden opgegeven onder `objectTypeOverige`.",
                max_length=100,
            ),
        ),
    ]
