# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-03-10 22:16

from django.db import migrations, models

import django_loose_fk.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0004_auto_20210628_1514"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak_or__relevant_zaak_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="resultaat", name="_resultaattype_or__resultaattype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="rol", name="_roltype_or__roltype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="status", name="_statustype_or__statustype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaak", name="_zaaktype_or__zaaktype_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakbesluit", name="_besluit_or__besluit_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakeigenschap", name="_eigenschap_or__eigenschap_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakinformatieobject",
            name="_informatieobject_or__informatieobject_url_filled",
        ),
        migrations.AlterField(
            model_name="overige", name="overige_data", field=models.JSONField(),
        ),
        migrations.AddConstraint(
            model_name="relevantezaakrelatie",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_relevant_zaak",
                model_name="relevantezaakrelatie",
                url_field="_relevant_zaak_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultaat",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_resultaattype",
                model_name="resultaat",
                url_field="_resultaattype_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="rol",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_roltype",
                model_name="rol",
                url_field="_roltype_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_statustype",
                model_name="status",
                url_field="_statustype_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaak",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_zaaktype",
                model_name="zaak",
                url_field="_zaaktype_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakbesluit",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_besluit",
                model_name="zaakbesluit",
                url_field="_besluit_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakeigenschap",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_eigenschap",
                model_name="zaakeigenschap",
                url_field="_eigenschap_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakinformatieobject",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="zaken",
                fk_field="_informatieobject",
                model_name="zaakinformatieobject",
                url_field="_informatieobject_url",
            ),
        ),
    ]
