# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-05-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0010_auto_20210628_0848"),
        ("documenten", "0006_alter_enkelvoudiginformatieobject__informatieobjecttype"),
        ("zaken", "0006_zaakobject_object_type_overige_definitie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaat",
            name="_resultaattype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het RESULTAATTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.resultaattype",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="_roltype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ROLTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.roltype",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="_statustype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het STATUSTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.statustype",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_zaaktype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ZAAKTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.zaaktype",
            ),
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="_eigenschap",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de EIGENSCHAP (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.eigenschap",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobject",
            name="_informatieobject",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het INFORMATIEOBJECT (in de Documenten API), waar ook de relatieinformatie opgevraagd kan worden.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documenten.enkelvoudiginformatieobjectcanonical",
            ),
        ),
    ]
