# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-03-28 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0006_merge_0005_auto_20220310_2216_0005_zaakcontactmoment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakVerzoek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "verzoek",
                    models.URLField(
                        help_text="URL-referentie naar het VERZOEK (in de Klantinteractie API)",
                        max_length=1000,
                        verbose_name="verzoek",
                    ),
                ),
                (
                    "_objectverzoek",
                    models.URLField(
                        blank=True,
                        help_text="Link to the related object in the Klantinteractie API",
                        verbose_name="objectverzoek",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakverzoek",
                "verbose_name_plural": "zaakverzoeken",
                "unique_together": {("zaak", "verzoek")},
            },
        ),
    ]
