# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-05-31 15:10

import uuid

import django.db.models.deletion
from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0006_auto_20220506_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultaat",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rol",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaak",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaak",
            name="opdrachtgevende_organisatie",
            field=vng_api_common.fields.RSINField(
                blank=True,
                help_text="De krachtens publiekrecht ingestelde rechtspersoon dan wel ander niet-natuurlijk persoon waarbinnen het (bestuurs)orgaan zetelt dat opdracht heeft gegeven om taken uit te voeren waaraan de zaak invulling geeft.",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="zaakeigenschap",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaakinformatieobject",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ZaakVerzoek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "verzoek",
                    models.URLField(
                        help_text="URL-referentie naar het VERZOEK (in de Klantinteractie API)",
                        max_length=1000,
                        verbose_name="verzoek",
                    ),
                ),
                (
                    "_objectverzoek",
                    models.URLField(
                        blank=True,
                        help_text="Link to the related object in the Klantinteractie API",
                        verbose_name="objectverzoek",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaakverzoek",
                "verbose_name_plural": "zaakverzoeken",
                "unique_together": {("zaak", "verzoek")},
            },
        ),
        migrations.CreateModel(
            name="ZaakContactMoment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "contactmoment",
                    models.URLField(
                        help_text="URL-referentie naar het CONTACTMOMENT (in de CMC API)",
                        max_length=1000,
                        verbose_name="contactmoment",
                    ),
                ),
                (
                    "_objectcontactmoment",
                    models.URLField(
                        blank=True,
                        help_text="Link to the related object in the CMC API",
                        verbose_name="objectcontactmoment",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "contactmoment",
                "verbose_name_plural": "contactmomenten",
                "unique_together": {("zaak", "contactmoment")},
            },
        ),
    ]
