# Generated by Django 2.2.4 on 2019-10-17 09:19

from django.db import migrations, models

import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [("zaken", "0006_auto_20191017_0906")]

    operations = [
        migrations.AddField(
            model_name="zaakinformatieobject",
            name="_informatieobject_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the informatieobject in an external API",
                max_length=1000,
                verbose_name="External informatieobject",
            ),
        ),
        migrations.AddField(
            model_name="zaakinformatieobject",
            name="informatieobject",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_informatieobject",
                null=False,
                url_field="_informatieobject_url",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="zaakinformatieobject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_informatieobject__isnull=True, _negated=True),
                        ("_informatieobject_url", ""),
                    ),
                    models.Q(
                        ("_informatieobject__isnull", True),
                        models.Q(_informatieobject_url="", _negated=True),
                    ),
                    _connector="OR",
                ),
                name="_informatieobject_or__informatieobject_url_filled",
            ),
        ),
    ]
