# Generated by Django 2.2.4 on 2019-10-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zaken", "0007_auto_20191017_0919")]

    operations = [
        migrations.AlterField(
            model_name="zaakinformatieobject",
            name="_informatieobject",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het INFORMATIEOBJECT (in de Documenten API), waar ook de relatieinformatie opgevraagd kan worden.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documenten.EnkelvoudigInformatieObjectCanonical",
            ),
        )
    ]
