# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0007_auto_20220531_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ("-datum_status_gezet",),
                "verbose_name": "status",
                "verbose_name_plural": "statussen",
            },
        ),
        migrations.AddField(
            model_name="zaakobject",
            name="object_type_overige_definitie",
            field=models.JSONField(
                blank=True,
                help_text='Verwijzing naar het schema van het type OBJECT als `objectType` de waarde "overige" heeft.',
                null=True,
                verbose_name="definitie object type overige",
            ),
        ),
    ]
