# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.14 on 2022-07-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0007_auto_20220531_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ("-datum_status_gezet",),
                "verbose_name": "status",
                "verbose_name_plural": "statussen",
            },
        ),
    ]
