# Generated by Django 3.2.14 on 2022-07-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0005_zaakobject_object_type_overige_definitie"),
        ("zaken", "0008_alter_status_options"),
    ]

    operations = []
