# Generated by Django 2.2.4 on 2019-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zaken", "0008_auto_20191017_1046")]

    operations = [
        migrations.AddConstraint(
            model_name="zaakinformatieobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(_informatieobject_url="", _negated=True),
                fields=("zaak", "_informatieobject_url"),
                name="unique_zaak_and_external_document",
            ),
        )
    ]
