# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-05-06 09:31

from django.db import migrations

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0008_auto_20220503_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="opdrachtgevende_organisatie",
            field=vng_api_common.fields.RSINField(
                blank=True,
                help_text="De krachtens publiekrecht ingestelde rechtspersoon dan wel ander niet-natuurlijk persoon waarbinnen het (bestuurs)orgaan zetelt dat opdracht heeft gegeven om taken uit te voeren waaraan de zaak invulling geeft.",
                max_length=9,
            ),
        ),
    ]
