# Generated by Django 2.2.4 on 2019-11-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0012_auto_20191122_1414"),
        ("zaken", "0010_auto_20191122_1411"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaak", old_name="zaaktype", new_name="_zaaktype"
        ),
        migrations.AddField(
            model_name="zaak",
            name="_zaaktype_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar extern ZAAKTYPE (in een andere Catalogi API).",
                max_length=1000,
                verbose_name="extern zaaktype",
            ),
        ),
    ]
