# Generated by Django 2.2.4 on 2019-11-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0011_auto_20191122_1923"),
        ("zaken", "0012_auto_20191125_1638"),
    ]

    operations = []
