# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.15 on 2022-11-01 10:02

from django.db import migrations
import django.db.models.deletion
import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("zaken", "0013_auto_20220816_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern ZAAK (in een andere Zaken API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern ZAAK (in een andere Zaken API).",
                max_length=1000,
                null=True,
                verbose_name="relevant zaak relative url",
            ),
        ),
        migrations.AlterField(
            model_name="resultaat",
            name="_resultaattype_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern RESULTAATTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="resultaat",
            name="_resultaattype_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern RESULTAATTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="resultaattype relative url",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="_roltype_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern ROLTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="_roltype_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern ROLTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="roltype relative url",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="_statustype_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern STATUSTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="_statustype_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern STATUSTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="statustype relative url",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_zaaktype_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar het extern ZAAKTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_zaaktype_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar het extern ZAAKTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="zaaktype relative url",
            ),
        ),
        migrations.AlterField(
            model_name="zaakbesluit",
            name="_besluit_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar externe BESLUIT (in een andere Besluiten API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="zaakbesluit",
            name="_besluit_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar externe BESLUIT (in een andere Besluiten API).",
                max_length=1000,
                null=True,
                verbose_name="besluit relative url",
            ),
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="_eigenschap_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar extern EIGENSCHAP (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="_eigenschap_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar extern EIGENSCHAP (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="eigenschap relative url",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobject",
            name="_informatieobject_base_url",
            field=openzaak.utils.fields.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar de externe API",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobject",
            name="_informatieobject_relative_url",
            field=openzaak.utils.fields.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar de externe API",
                max_length=1000,
                null=True,
                verbose_name="informatieobject relative url",
            ),
        ),
    ]
