# Generated by Django 2.2.4 on 2019-11-29 12:00

from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0014_auto_20191129_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevantezaakrelatie',
            name='url',
            field=django_loose_fk.fields.FkOrURLField(blank=False, fk_field='_relevant_zaak', null=False, url_field='_relevant_zaak_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relevantezaakrelatie',
            name='_relevant_zaak',
            field=models.ForeignKey(blank=True, help_text='URL-referentie naar de ZAAK.', null=True, on_delete=django.db.models.deletion.CASCADE, to='zaken.Zaak'),
        ),
        migrations.AddConstraint(
            model_name='relevantezaakrelatie',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, _relevant_zaak__isnull=True), ('_relevant_zaak_url', '')), models.Q(('_relevant_zaak__isnull', True), models.Q(_negated=True, _relevant_zaak_url='')), _connector='OR'), name='_relevant_zaak_or__relevant_zaak_url_filled'),
        ),
    ]
