# Generated by Django 2.2.4 on 2019-12-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0015_auto_20191129_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de ZAAK.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zaken.Zaak",
                verbose_name="relevante zaak",
            ),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar extern ZAAK (in een andere zaken API)",
                max_length=1000,
                verbose_name="externe relevante zaak",
            ),
        ),
    ]
