# Generated by Django 2.2.4 on 2019-12-05 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("besluiten", "0012_auto_20191128_1536"),
        ("zaken", "0015_auto_20191129_1200"),
    ]

    operations = [
        migrations.DeleteModel(name="ZaakBesluit",),
        migrations.CreateModel(
            name="ZaakBesluit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "_besluit_url",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar extern BESLUIT (in een andere Besluiten API).",
                        max_length=1000,
                        verbose_name="extern besluit",
                    ),
                ),
                (
                    "_besluit",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL-referentie naar het BESLUIT (in de Besluiten API).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="besluiten.Besluit",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.Zaak",
                    ),
                ),
            ],
        ),
    ]
