# Generated by Django 2.2.4 on 2019-12-05 11:39

from django.db import migrations, models
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0016_auto_20191205_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaakbesluit",
            name="besluit",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False, fk_field="_besluit", null=False, url_field="_besluit_url"
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="zaakbesluit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_besluit__isnull=True, _negated=True),
                        ("_besluit_url", ""),
                    ),
                    models.Q(
                        ("_besluit__isnull", True),
                        models.Q(_besluit_url="", _negated=True),
                    ),
                    _connector="OR",
                ),
                name="_besluit_or__besluit_url_filled",
            ),
        ),
    ]
