# Generated by Django 2.2.4 on 2019-12-18 13:24

from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0017_auto_20191218_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultaat",
            name="resultaattype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_resultaattype",
                null=False,
                url_field="_resultaattype_url",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resultaat",
            name="_resultaattype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het RESULTAATTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.ResultaatType",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultaat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_negated=True, _resultaattype__isnull=True),
                        ("_resultaattype_url", ""),
                    ),
                    models.Q(
                        ("_resultaattype__isnull", True),
                        models.Q(_negated=True, _resultaattype_url=""),
                    ),
                    _connector="OR",
                ),
                name="_resultaattype_or__resultaattype_url_filled",
            ),
        ),
    ]
