# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0017_zaak_identificatie_ptr"),
    ]

    # ALTER table operations result in table locks
    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="hoofdzaak",
            field=models.IntegerField(db_column="hoofdzaak_id", null=True),
        ),
        migrations.AlterField(
            model_name="klantcontact",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="_relevant_zaak",
            field=models.IntegerField(db_column="_relevant_zaak_id", null=True),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="resultaat",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id", unique=True),
        ),
        migrations.AlterField(
            model_name="rol",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="status",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakbesluit",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakcontactmoment",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobject",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakkenmerk",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakobject",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaakverzoek",
            name="zaak",
            field=models.IntegerField(db_column="zaak_id"),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="id",
            field=models.IntegerField(primary_key=False, serialize=False),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie_ptr",
            field=models.OneToOneField(
                help_text="Zaak identification details are tracked in a separate table so numbers can be generated/reserved before the zaak is actually created.",
                on_delete=django.db.models.deletion.PROTECT,
                to="zaken.zaakidentificatie",
                verbose_name="Zaak identification details",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="relevantezaakrelatie",
                    name="zaken_relevantezaakrelatie__relevant_zaak_or__relevant_zaak_base_url_filled",
                ),
                migrations.RemoveField(
                    model_name="relevantezaakrelatie",
                    name="url",
                ),
            ],
        ),
    ]
