# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0018_auto_20221214_1009"),
    ]

    # ALTER table operations result in table locks
    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie_ptr",
            field=models.OneToOneField(
                help_text="Zaak identification details are tracked in a separate table so numbers can be generated/reserved before the zaak is actually created.",
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="zaken.zaakidentificatie",
                verbose_name="Zaak identification details",
            ),
        ),
    ]
