# Generated by Django 2.2.4 on 2019-12-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0016_auto_20191204_1500"),
        ("zaken", "0018_auto_20191218_1324"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status", old_name="statustype", new_name="_statustype"
        ),
        migrations.AddField(
            model_name="status",
            name="_statustype_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar extern STATUSTYPE (in een andere Catalogi API).",
                max_length=1000,
                verbose_name="extern statustype",
            ),
        ),
    ]
