# Generated by Django 2.2.4 on 2019-12-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0016_auto_20191217_1545"),
        ("zaken", "0018_auto_20191205_1607"),
    ]

    operations = []
