# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 12:59

import django.db.models.deletion
from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0019_auto_20221214_1229"),
    ]

    # ALTER table operations result in table locks
    operations = [
        migrations.RenameField(
            model_name="zaak",
            old_name="id",
            new_name="_id",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="bronorganisatie",
            new_name="_bronorganisatie",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="identificatie",
            new_name="_identificatie",
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_id",
            field=models.IntegerField(db_column="id", null=True),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_bronorganisatie",
            field=vng_api_common.fields.RSINField(
                db_column="bronorganisatie",
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_identificatie",
            field=models.CharField(
                blank=True,
                db_column="identificatie",
                db_index=True,
                help_text="De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.",
                max_length=40,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zaak",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie_ptr",
            field=models.OneToOneField(
                help_text="Zaak identification details are tracked in a separate table so numbers can be generated/reserved before the zaak is actually created.",
                on_delete=django.db.models.deletion.PROTECT,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="zaken.zaakidentificatie",
                verbose_name="Zaak identification details",
            ),
        ),
    ]
