# Generated by Django 2.2.4 on 2019-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0019_merge_20191219_0922"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zaakbesluit", name="unique_zaak_and_besluit_document",
        ),
        migrations.AddConstraint(
            model_name="zaakbesluit",
            constraint=models.UniqueConstraint(
                condition=models.Q(_besluit_url="", _negated=True),
                fields=("zaak", "_besluit_url"),
                name="unique_zaak_and_besluit",
            ),
        ),
    ]
