# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.16 on 2022-12-14 14:13

from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0021_auto_20221214_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaakidentificatie",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="zaakidentificatie",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.",
                max_length=40,
                verbose_name="value",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakidentificatie",
            constraint=models.CheckConstraint(
                check=models.Q(("identificatie", ""), _negated=True),
                name="identificatie_not_empty",
            ),
        ),
    ]
