# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0023_alter_zaakidentificatie_identificatie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="datum_status_gezet",
            field=models.DateTimeField(
                db_index=True,
                help_text="De datum waarop de ZAAK de status heeft verkregen.",
            ),
        ),
    ]
