# Generated by Django 2.2.4 on 2019-12-19 16:57

from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0023_auto_20191219_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="roltype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False, fk_field="_roltype", null=False, url_field="_roltype_url"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rol",
            name="_roltype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ROLTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.RolType",
            ),
        ),
        migrations.AddConstraint(
            model_name="rol",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_negated=True, _roltype__isnull=True),
                        ("_roltype_url", ""),
                    ),
                    models.Q(
                        ("_roltype__isnull", True),
                        models.Q(_negated=True, _roltype_url=""),
                    ),
                    _connector="OR",
                ),
                name="_roltype_or__roltype_url_filled",
            ),
        ),
    ]
