# Generated by Django 2.2.4 on 2019-12-17 13:53

from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0023_auto_20191217_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="statustype",
            field=django_loose_fk.fields.FkOrURLField(
                blank=False,
                fk_field="_statustype",
                null=False,
                url_field="_statustype_url",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="status",
            name="_statustype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het STATUSTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.StatusType",
            ),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_negated=True, _statustype__isnull=True),
                        ("_statustype_url", ""),
                    ),
                    models.Q(
                        ("_statustype__isnull", True),
                        models.Q(_negated=True, _statustype_url=""),
                    ),
                    _connector="OR",
                ),
                name="_statustype_or__statustype_url_filled",
            ),
        ),
    ]
