# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0024_alter_status_datum_status_gezet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spoorbaandeel",
            name="type",
            field=models.CharField(
                choices=[
                    ("breedspoor", "Breedspoor"),
                    ("normaalspoor", "Normaalspoor"),
                    ("smalspoor", "Smalspoor"),
                    ("spoorbaan", "Spoorbaan"),
                ],
                help_text="Specificatie van het soort Spoorbaan",
                max_length=40,
            ),
        ),
    ]
