# Generated by Django 2.2.9 on 2020-01-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0029_auto_20200103_1607"),
        ("zaken", "0029_zaakinformatieobject__objectinformatieobject_url"),
    ]

    operations = []
