# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 3.2.23 on 2024-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0031_zaak_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adres",
            name="identificatie",
            field=models.CharField(
                blank=True,
                help_text="De unieke identificatie van het OBJECT",
                max_length=100,
            ),
        ),
    ]
