# Generated by Django 2.2.9 on 2020-01-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0032_auto_20200110_1613"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adres",
            options={"verbose_name": "adres", "verbose_name_plural": "adressen"},
        ),
        migrations.AlterModelOptions(
            name="buurt",
            options={"verbose_name": "buurt", "verbose_name_plural": "buurten"},
        ),
        migrations.AlterModelOptions(
            name="gemeente",
            options={"verbose_name": "gemeente", "verbose_name_plural": "gemeenten"},
        ),
        migrations.AlterModelOptions(
            name="gemeentelijkeopenbareruimte",
            options={
                "verbose_name": "gemeentelijke openbare ruimte",
                "verbose_name_plural": "gemeentelijke openbare ruimten",
            },
        ),
        migrations.AlterModelOptions(
            name="huishouden",
            options={
                "verbose_name": "huishouden",
                "verbose_name_plural": "huishoudens",
            },
        ),
        migrations.AlterModelOptions(
            name="inrichtingselement",
            options={
                "verbose_name": "inrichtingselement",
                "verbose_name_plural": "inrichtingselementen",
            },
        ),
        migrations.AlterModelOptions(
            name="kadastraleonroerendezaak",
            options={
                "verbose_name": "kadastrale onroerende zaak",
                "verbose_name_plural": "kadastrale onroerende zaken",
            },
        ),
        migrations.AlterModelOptions(
            name="kunstwerkdeel",
            options={
                "verbose_name": "kunstwerkdeel",
                "verbose_name_plural": "kunstwerkdelen",
            },
        ),
        migrations.AlterModelOptions(
            name="maatschappelijkeactiviteit",
            options={
                "verbose_name": "maatschappelijke activiteit",
                "verbose_name_plural": "maatschappelijke activiteiten",
            },
        ),
        migrations.AlterModelOptions(
            name="medewerker",
            options={
                "verbose_name": "medewerker",
                "verbose_name_plural": "medewerkers",
            },
        ),
        migrations.AlterModelOptions(
            name="natuurlijkpersoon",
            options={
                "verbose_name": "natuurlijk persoon",
                "verbose_name_plural": "natuurlijke personen",
            },
        ),
        migrations.AlterModelOptions(
            name="nietnatuurlijkpersoon",
            options={
                "verbose_name": "niet-natuurlijk persoon",
                "verbose_name_plural": "niet-natuurlijke personen",
            },
        ),
        migrations.AlterModelOptions(
            name="openbareruimte",
            options={
                "verbose_name": "openbare ruimte",
                "verbose_name_plural": "openbare ruimten",
            },
        ),
        migrations.AlterModelOptions(
            name="organisatorischeeenheid",
            options={
                "verbose_name": "organisatorische eenheid",
                "verbose_name_plural": "organisatorische eenheden",
            },
        ),
        migrations.AlterModelOptions(
            name="overige",
            options={"verbose_name": "overig", "verbose_name_plural": "overige"},
        ),
        migrations.AlterModelOptions(
            name="pand",
            options={"verbose_name": "pand", "verbose_name_plural": "panden"},
        ),
        migrations.AlterModelOptions(
            name="spoorbaandeel",
            options={
                "verbose_name": "spoorbaandeel",
                "verbose_name_plural": "spoorbaandelen",
            },
        ),
        migrations.AlterModelOptions(
            name="terreindeel",
            options={
                "verbose_name": "terreindeel",
                "verbose_name_plural": "terreindelen",
            },
        ),
        migrations.AlterModelOptions(
            name="terreingebouwdobject",
            options={
                "verbose_name": "terreingebouwd object",
                "verbose_name_plural": "terreingebouwde objecten",
            },
        ),
        migrations.AlterModelOptions(
            name="vestiging",
            options={"verbose_name": "vestiging", "verbose_name_plural": "vestigingen"},
        ),
        migrations.AlterModelOptions(
            name="waterdeel",
            options={"verbose_name": "waterdeel", "verbose_name_plural": "waterdelen"},
        ),
        migrations.AlterModelOptions(
            name="wegdeel",
            options={"verbose_name": "wegdeel", "verbose_name_plural": "wegdelen"},
        ),
        migrations.AlterModelOptions(
            name="wijk",
            options={"verbose_name": "wijk", "verbose_name_plural": "wijken"},
        ),
        migrations.AlterModelOptions(
            name="woonplaats",
            options={
                "verbose_name": "woonplaats",
                "verbose_name_plural": "woonplaatsen",
            },
        ),
        migrations.AlterModelOptions(
            name="wozdeelobject",
            options={
                "verbose_name": "WOZ-deelobject",
                "verbose_name_plural": "WOZ-deelobjecten",
            },
        ),
        migrations.AlterModelOptions(
            name="wozobject",
            options={
                "verbose_name": "WOZ-object",
                "verbose_name_plural": "WOZ-objecten",
            },
        ),
        migrations.AlterModelOptions(
            name="wozwaarde",
            options={
                "verbose_name": "WOZ-waarde",
                "verbose_name_plural": "WOZ-waarden",
            },
        ),
        migrations.AlterModelOptions(
            name="zakelijkrecht",
            options={
                "verbose_name": "zakelijk recht",
                "verbose_name_plural": "zakelijke rechten",
            },
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="_eigenschap",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de EIGENSCHAP (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.Eigenschap",
            ),
        ),
        migrations.AlterField(
            model_name="zaakeigenschap",
            name="_eigenschap_url",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar externe EIGENSCHAP (in een andere Catalogi API).",
                max_length=1000,
                verbose_name="externe eigenschap",
            ),
        ),
    ]
