# Generated by Django 4.2.15 on 2024-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0034_zaak_communicatiekanaal_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="laatst_gelezen",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="laatst gelezen"
            ),
        ),
    ]
