# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0034_zaak_communicatiekanaal_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="authenticatie_context",
            field=models.JSONField(
                blank=True,
                help_text="Metadata about the authentication context and mandate that applied when the role was added to the case.",
                null=True,
                verbose_name="authentication context",
            ),
        ),
        migrations.AddConstraint(
            model_name="rol",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "betrokkene_type__in",
                        ["natuurlijk_persoon", "niet_natuurlijk_persoon", "vestiging"],
                    ),
                    models.Q(
                        models.Q(
                            (
                                "betrokkene_type__in",
                                [
                                    "natuurlijk_persoon",
                                    "niet_natuurlijk_persoon",
                                    "vestiging",
                                ],
                            ),
                            _negated=True,
                        ),
                        ("authenticatie_context__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="rol_auth_context_support_check",
            ),
        ),
    ]
