# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.15 on 2024-09-27 13:48

from django.db import migrations, models
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0035_rol_authenticatie_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nietnatuurlijkpersoon",
            name="kvk_nummer",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** Een Kamer van Koophandel uniek nummer",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="nietnatuurlijkpersoon",
            name="inn_nnp_id",
            field=vng_api_common.fields.RSINField(
                blank=True,
                db_index=True,
                help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON. Het is het RSIN veld.",
                max_length=9,
            ),
        ),
    ]
