# Generated by Django 4.2.17 on 2025-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0036_nietnatuurlijkpersoon_kvk_nummer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevantezaakrelatie",
            name="toelichting",
            field=models.CharField(
                blank=True,
                help_text="Een korte toelichting van de zaak relatie. (Vooral bedoeld in combinatie met relatie aard 'Overig')",
                max_length=200,
                null=True,
                verbose_name="toelichting",
            ),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="aard_relatie",
            field=models.CharField(
                choices=[
                    (
                        "vervolg",
                        "De andere zaak gaf aanleiding tot het starten van de onderhanden zaak.",
                    ),
                    (
                        "onderwerp",
                        "De andere zaak is relevant voor cq. is onderwerp van de onderhanden zaak.",
                    ),
                    (
                        "bijdrage",
                        "Aan het bereiken van de uitkomst van de andere zaak levert de onderhanden zaak een bijdrage.",
                    ),
                    ("overig", "Overig"),
                ],
                help_text="Benamingen van de aard van de relaties van andere zaken tot (onderhanden) zaken.",
                max_length=20,
            ),
        ),
    ]
