# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.17 on 2025-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0036_nietnatuurlijkpersoon_kvk_nummer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="roltoelichting",
            field=models.TextField(
                blank=True,
                help_text="**EXPERIMENTEEL** Toelichting bij de rol (dit veld wijkt af van de standaard, omdat het veld niet verplicht is).",
                max_length=1000,
            ),
        ),
    ]
