# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 4.2.17 on 2025-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0037_alter_rol_roltoelichting"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevantezaakrelatie",
            name="overige_relatie",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** Naam van de overige relatie. Verplicht bij relatie aard `overig`.",
                max_length=100,
                verbose_name="overige relatie",
            ),
        ),
        migrations.AddField(
            model_name="relevantezaakrelatie",
            name="toelichting",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** Een toelichting op de aard van de relatie tussen beide ZAKEN. (vooral bedoeld in combinatie met relatie aard `overig`)",
                max_length=255,
                verbose_name="toelichting",
            ),
        ),
        migrations.AlterField(
            model_name="relevantezaakrelatie",
            name="aard_relatie",
            field=models.CharField(
                choices=[
                    (
                        "vervolg",
                        "De andere zaak gaf aanleiding tot het starten van de onderhanden zaak.",
                    ),
                    (
                        "onderwerp",
                        "De andere zaak is relevant voor cq. is onderwerp van de onderhanden zaak.",
                    ),
                    (
                        "bijdrage",
                        "Aan het bereiken van de uitkomst van de andere zaak levert de onderhanden zaak een bijdrage.",
                    ),
                    ("overig", "**EXPERIMENTEEL** Overig"),
                ],
                help_text="Benamingen van de aard van de relaties van andere zaken tot (onderhanden) zaken.",
                max_length=20,
            ),
        ),
    ]
