# Generated by Django 4.2.17 on 2025-02-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0038_relevantezaakrelatie_overige_relatie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaak",
            old_name="_bronorganisatie",
            new_name="bronorganisatie",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_identificatie",
            new_name="identificatie",
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie_ptr",
            field=models.OneToOneField(
                help_text="Zaak identification details are tracked in a separate table so numbers can be generated/reserved before the zaak is actually created.",
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="zaken.zaakidentificatie",
                verbose_name="Zaak identification details",
            ),
        ),
    ]
