# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 4.2.17 on 2025-02-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0038_relevantezaakrelatie_overige_relatie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="tijdvak_geldigheid_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="**EXPERIMENTEEL** De datum waarop de geldigheidsperiode van de ROL begint binnen de ZAAK.",
                null=True,
                verbose_name="begindatum geldigheid",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="tijdvak_geldigheid_eind_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="**EXPERIMENTEEL** De datum waarop de geldigheidsperiode van de ROL eindigt binnen de ZAAK.",
                null=True,
                verbose_name="einddatum geldigheid",
            ),
        ),
    ]
