# Generated by Django 4.2.17 on 2025-02-13 10:05

from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0039_rename__bronorganisatie_zaak_bronorganisatie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.",
                max_length=40,
            ),
        ),
    ]
