# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 4.2.19 on 2025-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0039_rol_begin_geldigheid_rol_einde_geldigheid"),
    ]

    operations = [
        migrations.AddField(
            model_name="nietnatuurlijkpersoon",
            name="vestigings_nummer",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** Een korte unieke aanduiding van de Vestiging.",
                max_length=24,
            ),
        ),
    ]
