# Generated by Django 4.2.19 on 2025-03-24 10:14

from django.db import migrations

def forward(apps, schema_editor):
    Zaak = apps.get_model("zaken", "Zaak")
    ZaakIdentificatie = apps.get_model("zaken", "ZaakIdentificatie")
    for zaak in Zaak.objects.filter(_identificatie="", _bronorganisatie="").iterator():
        zi = ZaakIdentificatie.objects.get(id=zaak.pk)
        zaak._identificatie = zi.identificatie
        zaak._bronorganisatie = zi.bronorganisatie
        zaak.save()


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0039_rol_begin_geldigheid_rol_einde_geldigheid"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
