# Generated by Django 4.2.19 on 2025-03-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0039_rol_begin_geldigheid_rol_einde_geldigheid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaak",
            old_name="_bronorganisatie",
            new_name="bronorganisatie",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_identificatie",
            new_name="identificatie",
        ),
    ]
