# Generated by Django 4.2.19 on 2025-03-25 10:33

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0040_adres_nietnatuurlijkpersoon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                help_text="Aanduiding van de mate waarin het zaakdossier van de ZAAK voor de openbaarheid bestemd is.",
                verbose_name="vertrouwlijkheidaanduiding",
            ),
        ),
    ]
