# Generated by Django 4.2.19 on 2025-03-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0040_auto_20250324_1014"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaak",
            old_name="_bronorganisatie",
            new_name="bronorganisatie",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_identificatie",
            new_name="identificatie",
        ),
    ]
