# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.1.7 on 2025-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0040_adres_nietnatuurlijkpersoon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="opschorting_eerdere_opschorting",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="**EXPERIMENTEEL** Aanduiding of de behandeling van de ZAAK in het verleden is opgeschort.",
                verbose_name="eerdere opschorting",
            ),
        ),
    ]
