# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.1.7 on 2025-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0040_adres_nietnatuurlijkpersoon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medewerker",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="**EXPERIMENTEEL** Een korte unieke aanduiding van de MEDEWERKER. Dit veld wijkt af van de standaard, omdat er 128 karakters zijn toegestaan in plaats van 24",
                max_length=128,
            ),
        ),
    ]
