# Generated by Django 4.2.19 on 2025-03-25 10:33

from django.db import migrations
from vng_api_common.constants import MAPPING


def forward(apps, schema_editor):
    Zaak = apps.get_model("zaken", "Zaak")
    for zaak in Zaak.objects.iterator():
        zaak.vertrouwelijkheidaanduiding = MAPPING[zaak.vertrouwelijkheidaanduiding]
        zaak.calculate_etag_value = lambda: None
        zaak.save(update_fields=["vertrouwelijkheidaanduiding"])


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0041_alter_zaak_vertrouwelijkheidaanduiding"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
