# Generated by Django 4.2.19 on 2025-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0041_rename__bronorganisatie_zaak_bronorganisatie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zaak",
            name="identificatie_ptr",
        ),
        migrations.AlterField(
            model_name="zaak",
            name="_id",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
    ]
