# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.1.7 on 2025-04-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0041_alter_medewerker_identificatie"),
        ("zaken", "0041_zaak_opschorting_eerdere_opschorting"),
    ]

    operations = []
