# Generated by Django 5.1.7 on 2025-04-11 13:42

import vng_api_common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0042_auto_20250325_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                db_index=True,
                help_text="Aanduiding van de mate waarin het zaakdossier van de ZAAK voor de openbaarheid bestemd is.",
                verbose_name="vertrouwlijkheidaanduiding",
            ),
        ),
    ]
