# Generated by Django 5.2.3 on 2025-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0043_substatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
