# Generated by Django 5.2.3 on 2025-07-16 12:44

import django.db.models.deletion
import openzaak.utils.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0043_substatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakNotitie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatie voor deze notitie",
                        unique=True,
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        help_text="Korte omschrijving of titel van de notitie",
                        max_length=255,
                    ),
                ),
                (
                    "tekst",
                    models.TextField(
                        help_text="De volledige inhoud of beschrijving van de notitie"
                    ),
                ),
                (
                    "aangemaakt_door",
                    models.CharField(
                        blank=True,
                        help_text="Naam of identificatie van de auteur van de notitie",
                        max_length=255,
                    ),
                ),
                (
                    "notitie_type",
                    models.CharField(
                        choices=[("intern", "Intern"), ("extern", "Extern")],
                        default="intern",
                        help_text="Intern mag enkel een medewerker zien, extern mag gezien worden door medewerker en de initiator.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("concept", "Concept"), ("definitief", "Definitief")],
                        default="concept",
                        max_length=50,
                    ),
                ),
                (
                    "aanmaakdatum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop de handeling is gedaan.",
                    ),
                ),
                (
                    "wijzigingsdatum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum en tijd waarop de notitie voor het laatst is gewijzigd",
                    ),
                ),
                (
                    "gerelateerd_aan",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zaken.zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaaknotitie",
                "verbose_name_plural": "zaaknotities",
            },
            bases=(openzaak.utils.mixins.APIMixin, models.Model),
        ),
    ]
