# Generated by Django 5.2.3 on 2025-08-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0044_zaak__json"),
        ("zaken", "0044_zaaknotitie"),
    ]

    operations = []
