# Generated by Django 5.2.7 on 2025-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0044_zaaknotitie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaak',
            old_name='_bronorganisatie',
            new_name='bronorganisatie',
        ),
        migrations.RenameField(
            model_name='zaak',
            old_name='_identificatie',
            new_name='identificatie',
        ),
        migrations.RemoveField(
            model_name='zaak',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='zaak',
            name='identificatie_ptr',
        ),
        migrations.AddField(
            model_name='zaak',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
