# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.2.7 on 2025-11-04 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0044_zaaknotitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='laatst_gemuteerd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='**EXPERIMENTEEL** Tijdstip waarop de ZAAK voor het laatst een nieuwe STATUS heeft gekregen.', verbose_name='laatst gewijzigd op'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='laatst_geopend',
            field=models.DateTimeField(blank=True, help_text='**EXPERIMENTEEL** Tijdstip waarop de ZAAK voor het laatst geopend is door de eigenaar van de ZAAK.', null=True, verbose_name='laatst geopend op'),
        ),
    ]
