# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.2.7 on 2025-11-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0045_zaak_laatst_gemuteerd_zaak_laatst_geopend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='betalingsindicatie',
            field=models.CharField(blank=True, choices=[('nvt', 'Er is geen sprake van te betalen, met de zaak gemoeide, kosten.'), ('gefactureerd', '**EXPERIMENTEEL** Opdracht tot facturatie verzonden'), ('gecrediteerd', '**EXPERIMENTEEL** Opdracht tot creditering verzonden'), ('betaald', '**EXPERIMENTEEL** Betaling vastgesteld (bijvoorbeeld via online kassa bij directe aanvraag)'), ('nog_niet', '**DEPRECATED** De met de zaak gemoeide kosten zijn (nog) niet betaald.'), ('gedeeltelijk', '**DEPRECATED** De met de zaak gemoeide kosten zijn gedeeltelijk betaald.'), ('geheel', '**DEPRECATED** De met de zaak gemoeide kosten zijn geheel betaald.')], help_text='Indicatie of de, met behandeling van de zaak gemoeide, kosten betaald zijn door de desbetreffende betrokkene.', max_length=20, verbose_name='betalingsindicatie'),
        ),
    ]
