# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.2.8 on 2026-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0046_alter_zaak_betalingsindicatie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="**EXPERIMENTEEL** Een korte identificatie van de organisatorische eenheid. Dit veld wijkt af van de standaard, omdat er 255 karakters zijn toegestaan in plaats van 24",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="is_gehuisvest_in",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** Dit veld wijkt af van de standaard, omdat er 255 karakters zijn toegestaan in plaats van 24",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="**EXPERIMENTEEL** De feitelijke naam van de organisatorische eenheid. Dit veld wijkt af van de standaard, omdat er 255 karakters zijn toegestaan in plaats van 50",
                max_length=255,
            ),
        ),
    ]
