# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.8 on 2026-01-23 14:42

import django.db.models.deletion
import openzaak.components.zaken.models.zaken
import openzaak.utils.fields
import zgw_consumers.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0047_alter_organisatorischeeenheid_identificatie_and_more'),
        ('zgw_consumers', '0027_service_oauth2_scope_service_oauth2_token_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaakRelatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_gerelateerde_zaak_relative_url', openzaak.utils.fields.RelativeURLField(blank=True, help_text='Relatief deel van URL-referentie naar externe ZAAK (in een andere Zaken API).', max_length=1000, null=True, verbose_name='gerelateerde zaak relative url')),
                ('_gerelateerde_zaak_url', zgw_consumers.models.fields.ServiceUrlField(base_field='_gerelateerde_zaak_base_url', blank=True, null=True, relative_field='_gerelateerde_zaak_relative_url')),
                ('url', openzaak.components.zaken.models.zaken._FkOrServiceUrlField(blank=False, fk_field='_gerelateerde_zaak', null=False, url_field='_gerelateerde_zaak_url')),
                ('_gerelateerde_zaak', models.ForeignKey(blank=True, help_text='URL-referentie naar de ZAAK.', null=True, on_delete=django.db.models.deletion.CASCADE, to='zaken.zaak', verbose_name='gerelateerde zaak')),
                ('_gerelateerde_zaak_base_url', openzaak.utils.fields.ServiceFkField(blank=True, help_text='Basis deel van URL-referentie naar externe ZAAK (in een andere Zaken API).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='zgw_consumers.service')),
                ('zaak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerelateerde_zaken', to='zaken.zaak')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('zaak', '_gerelateerde_zaak'), name='zaak_gerelateerde_zaak_unique_together'), models.CheckConstraint(condition=models.Q(models.Q(('_gerelateerde_zaak_base_url__isnull', True), models.Q(('_gerelateerde_zaak_relative_url__isnull', True), ('_gerelateerde_zaak_relative_url', ''), _connector='OR')), models.Q(models.Q(('_gerelateerde_zaak_base_url__isnull', True), _negated=True), models.Q(('_gerelateerde_zaak_relative_url__isnull', True), ('_gerelateerde_zaak_relative_url', ''), _connector='OR', _negated=True)), _connector='OR'), name='zaken_zaakrelatie__gerelateerde_zaak_base_url_and__gerelateerde_zaak_relative_url_filled'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(('_gerelateerde_zaak__isnull', True), _negated=True), ('_gerelateerde_zaak_base_url__isnull', True)), models.Q(('_gerelateerde_zaak__isnull', True), models.Q(('_gerelateerde_zaak_base_url__isnull', True), _negated=True)), _connector='OR'), name='zaken_zaakrelatie__gerelateerde_zaak_or__gerelateerde_zaak_base_url_filled')],
            },
        ),
    ]
