# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.12 on 2026-03-26 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0048_zaakrelatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='laatst_gemuteerd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='**EXPERIMENTEEL** Tijdstip waarop de ZAAK voor het laatst wijzingen heeft gehad die relevant kunnen zijn voor de initiator van de ZAAK.', verbose_name='laatst gewijzigd op'),
        ),
    ]
