# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-07-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0026_set_P0D_servicenorms_to_none"),
        ("zaken", "0049_alter_zaak_laatst_gemuteerd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zaak",
            name="zaken_zaak__zaaktype_or__zaaktype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaak",
            name="zaken_zaak__zaaktype_base_url_and__zaaktype_relative_url_filled",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_zaaktype",
            new_name="zaaktype",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_base_url",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_relative_url",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_url",
        ),
    ]
