# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-07-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0026_set_P0D_servicenorms_to_none"),
        (
            "zaken",
            "0050_remove_zaak_zaken_zaak__zaaktype_or__zaaktype_base_url_filled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="status",
            name="zaken_status__statustype_or__statustype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="status",
            name="zaken_status__statustype_base_url_and__statustype_relative_url_filled",
        ),
        migrations.RenameField(
            model_name="status",
            old_name="_statustype",
            new_name="statustype",
        ),

        migrations.RemoveField(
            model_name="status",
            name="_statustype_base_url",
        ),
        migrations.RemoveField(
            model_name="status",
            name="_statustype_relative_url",
        ),
        migrations.RemoveField(
            model_name="status",
            name="_statustype_url",
        ),
    ]
