# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaken', '0050_alter_zaakobject_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='identificatie',
            field=models.CharField(blank=True, db_index=True, help_text='Een unieke aanduiding van de MEDEWERKER.', max_length=254),
        ),
        migrations.AlterField(
            model_name='nietnatuurlijkpersoon',
            name='inn_rechtsvorm',
            field=models.CharField(blank=True, choices=[('besloten_vennootschap', 'Besloten Vennootschap'), ('cooperatie_europees_economische_samenwerking', 'Cooperatie, Europees Economische Samenwerking'), ('europese_cooperatieve_vennootschap', 'Europese Cooperatieve Vennootschap'), ('europese_naamloze_vennootschap', 'Europese Naamloze Vennootschap'), ('kerkelijke_organisatie', 'Kerkelijke Organisatie'), ('naamloze_vennootschap', 'Naamloze Vennootschap'), ('onderlinge_waarborg_maatschappij', 'Onderlinge Waarborg Maatschappij'), ('overig_privaatrechtelijke_rechtspersoon', 'Overig privaatrechtelijke rechtspersoon'), ('stichting', 'Stichting'), ('vereniging', 'Vereniging'), ('vereniging_van_eigenaars', 'Vereniging van Eigenaars'), ('publiekrechtelijke_rechtspersoon', 'Publiekrechtelijke Rechtspersoon'), ('vennootschap_onder_firma', 'Vennootschap onder Firma'), ('maatschap', 'Maatschap'), ('rederij', 'Rederij'), ('commanditaire_vennootschap', 'Commanditaire vennootschap'), ('kapitaalvennootschap_binnen_eer', 'Kapitaalvennootschap binnen EER'), ('overige_buitenlandse_rechtspersoon_vennootschap', 'Overige buitenlandse rechtspersoon vennootschap'), ('kapitaalvennootschap_buiten_eer', 'Kapitaalvennootschap buiten EER')], help_text='De juridische vorm van de NIET-NATUURLIJK PERSOON.', max_length=50),
        ),
    ]
