# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-08-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0026_set_P0D_servicenorms_to_none"),
        ("zaken", "0050_alter_zaakobject_object_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="status",
            name="zaken_status__statustype_or__statustype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="status",
            name="zaken_status__statustype_base_url_and__statustype_relative_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaak",
            name="zaken_zaak__zaaktype_or__zaaktype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaak",
            name="zaken_zaak__zaaktype_base_url_and__zaaktype_relative_url_filled",
        ),
        migrations.RenameField(
            model_name="status",
            old_name="_statustype",
            new_name="statustype",
        ),
        migrations.RemoveField(
            model_name="status",
            name="_statustype_base_url",
        ),
        migrations.RemoveField(
            model_name="status",
            name="_statustype_relative_url",
        ),
        migrations.RemoveField(
            model_name="status",
            name="_statustype_url",
        ),
        migrations.RenameField(
            model_name="zaak",
            old_name="_zaaktype",
            new_name="zaaktype",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_base_url",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_relative_url",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="_zaaktype_url",
        ),
        migrations.AlterField(
            model_name="status",
            name="statustype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het STATUSTYPE (in de Catalogi API).",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.statustype",
            ),
        ),
        migrations.AlterField(
            model_name="zaak",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE (in de Catalogi API).",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.zaaktype",
            ),
        ),
    ]
