# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-08-07 15:56

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0026_set_P0D_servicenorms_to_none"),
        (
            "zaken",
            "0051_remove_status_zaken_status__statustype_or__statustype_base_url_filled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resultaat",
            name="zaken_resultaat__resultaattype_or__resultaattype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="resultaat",
            name="zaken_resultaat__resultaattype_base_url_and__resultaattype_relative_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="rol",
            name="zaken_rol__roltype_or__roltype_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="rol",
            name="zaken_rol__roltype_base_url_and__roltype_relative_url_filled",
        ),

        migrations.RenameField(
            model_name="resultaat",
            old_name="_resultaattype",
            new_name="resultaattype",
        ),
        migrations.RenameField(
            model_name="rol",
            old_name="_roltype",
            new_name="roltype",
        ),

        migrations.AlterField(
            model_name="resultaat",
            name="resultaattype",
            field=models.ForeignKey(
                "catalogi.ResultaatType",
                on_delete=models.PROTECT,
                help_text="URL-referentie naar het RESULTAATTYPE (in de Catalogi API).",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="roltype",
            field=models.ForeignKey(
                to="catalogi.roltype",
                on_delete=django.db.models.deletion.PROTECT,
                help_text="URL-referentie naar een roltype binnen het ZAAKTYPE van de ZAAK.",
            ),
        ),

        migrations.RemoveField(
            model_name="resultaat",
            name="_resultaattype_base_url",
        ),
        migrations.RemoveField(
            model_name="resultaat",
            name="_resultaattype_relative_url",
        ),
        migrations.RemoveField(
            model_name="resultaat",
            name="_resultaattype_url",
        ),

        migrations.RemoveField(
            model_name="rol",
            name="_roltype_base_url",
        ),
        migrations.RemoveField(
            model_name="rol",
            name="_roltype_relative_url",
        ),
        migrations.RemoveField(
            model_name="rol",
            name="_roltype_url",
        ),
    ]
