# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-08-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0026_set_P0D_servicenorms_to_none"),
        (
            "zaken",
            "0052_remove_resultaat_zaken_resultaat__resultaattype_or__resultaattype_base_url_filled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zaakeigenschap",
            name="zaken_zaakeigenschap__eigenschap_or__eigenschap_base_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakeigenschap",
            name="zaken_zaakeigenschap__eigenschap_base_url_and__eigenschap_relative_url_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakobject",
            name="zaken_zaakobject__zaakobjecttype_base_url_and__zaakobjecttype_relative_url_filled",
        ),

        migrations.RenameField(
            model_name="zaakeigenschap",
            old_name="_eigenschap",
            new_name="eigenschap",
        ),
        migrations.RenameField(
            model_name="zaakobject",
            old_name="_zaakobjecttype",
            new_name="zaakobjecttype",
        ),

        migrations.AlterField(
            model_name="zaakeigenschap",
            name="eigenschap",
            field=models.ForeignKey(
                help_text="URL-referentie naar de EIGENSCHAP (in de Catalogi API).",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.eigenschap",
            ),
        ),
        migrations.AlterField(
            model_name="zaakobject",
            name="zaakobjecttype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ZAAKOBJECTTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.zaakobjecttype",
            ),
        ),

        migrations.RemoveField(
            model_name="zaakeigenschap",
            name="_eigenschap_base_url",
        ),
        migrations.RemoveField(
            model_name="zaakeigenschap",
            name="_eigenschap_relative_url",
        ),
        migrations.RemoveField(
            model_name="zaakeigenschap",
            name="_eigenschap_url",
        ),

        migrations.RemoveField(
            model_name="zaakobject",
            name="_zaakobjecttype_base_url",
        ),
        migrations.RemoveField(
            model_name="zaakobject",
            name="_zaakobjecttype_relative_url",
        ),
        migrations.RemoveField(
            model_name="zaakobject",
            name="_zaakobjecttype_url",
        ),
    ]
