# Generated by Django 5.2.17 on 2026-09-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besluiten', '0021_remove_besluit_besluiten_besluit__zaak_base_url_and__zaak_relative_url_filled_and_more'),
        ('zaken', '0053_remove_zaakeigenschap_zaken_zaakeigenschap__eigenschap_or__eigenschap_base_url_filled_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zaakbesluit',
            name='zaken_zaakbesluit__besluit_or__besluit_base_url_filled',
        ),
        migrations.RemoveConstraint(
            model_name='zaakbesluit',
            name='unique_zaak_and_besluit',
        ),
        migrations.RemoveConstraint(
            model_name='zaakbesluit',
            name='zaken_zaakbesluit__besluit_base_url_and__besluit_relative_url_filled',
        ),
        migrations.RenameField(
            model_name='zaakbesluit',
            old_name='_besluit',
            new_name='besluit',
        ),
        migrations.AlterUniqueTogether(
            name='zaakbesluit',
            unique_together={('zaak', 'besluit')},
        ),
        migrations.AlterField(
            model_name='zaakbesluit',
            name='besluit',
            field=models.ForeignKey(blank=True, help_text='URL-referentie naar het BESLUIT (in de Besluiten API).', null=True, on_delete=django.db.models.deletion.CASCADE, to='besluiten.besluit'),
        ),
        migrations.AddConstraint(
            model_name='zaakbesluit',
            constraint=models.UniqueConstraint(fields=('zaak', 'besluit'), name='unique_zaak_and_besluit'),
        ),
        migrations.RemoveField(
            model_name='zaakbesluit',
            name='_besluit_base_url',
        ),
        migrations.RemoveField(
            model_name='zaakbesluit',
            name='_besluit_relative_url',
        ),
        migrations.RemoveField(
            model_name='zaakbesluit',
            name='_besluit_url',
        ),
    ]
