# Generated by Django 2.0.8 on 2018-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0002_auto_20180906_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluit',
            name='vervalreden',
            field=models.CharField(blank=True, choices=[('tijdelijk', 'Besluit met tijdelijke werking'), ('ingetrokken_overheid', 'Besluit ingetrokken door overheid'), ('ingetrokken_belanghebbende', 'Besluit ingetrokken o.v.v. belanghebbende')], max_length=30, verbose_name='vervalreden'),
        ),
    ]
