# Generated by Django 2.0.8 on 2018-10-29 09:59

from django.db import migrations, models
import vng_api_common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0003_besluit_vervalreden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluit',
            name='datum',
            field=models.DateField(help_text='De beslisdatum (AWB) van het besluit.', validators=[vng_api_common.validators.UntilTodayValidator()], verbose_name='datum'),
        ),
    ]
