# Generated by Django 2.0.8 on 2018-10-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0004_auto_20181029_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluit',
            name='toelichting',
            field=models.TextField(blank=True, help_text='Toelichting bij het besluit.', verbose_name='toelichting'),
        ),
    ]
