# Generated by Django 2.0.8 on 2018-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0005_auto_20181029_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluit',
            name='vervalreden',
            field=models.CharField(blank=True, choices=[('tijdelijk', 'Besluit met tijdelijke werking'), ('ingetrokken_overheid', 'Besluit ingetrokken door overheid'), ('ingetrokken_belanghebbende', 'Besluit ingetrokken o.v.v. belanghebbende')], help_text='De omschrijving die aangeeft op grond waarvan het besluit is of komt te vervallen.', max_length=30, verbose_name='vervalreden'),
        ),
    ]
