# Generated by Django 2.0.13 on 2019-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0007_auto_20190528_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluit',
            name='_zaakbesluit',
            field=models.URLField(blank=True, help_text='Link to the related object in the ZRC API', verbose_name='zaakbesluit'),
        ),
    ]
