# Generated by Django 2.2.2 on 2019-07-01 15:37

from django.db import migrations


def rewrite_urls(apps, schema_editor):
    Besluit = apps.get_model("brc_datamodel.Besluit")

    besluiten = Besluit.objects.filter(
        besluittype__regex=r"^https?://.*/catalogussen/[\w-]+/.*"
    )
    for besluit in besluiten:
        bits = besluit.besluittype.split("/")
        index = bits.index("catalogussen")

        new_bits = bits[0:index] + bits[index + 2:]
        besluit.besluittype = "/".join(new_bits)
        besluit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brc_datamodel', '0009_auto_20190701_1436'),
    ]

    operations = [
        migrations.RunPython(rewrite_urls, migrations.RunPython.noop),
    ]
