# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.9 on 2019-12-23 13:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorizations", "0011_auto_20191114_0728"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorisatieSpec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ac", "Autorisatiecomponent"),
                            ("nrc", "Notificatierouteringcomponent"),
                            ("zrc", "Zaakregistratiecomponent"),
                            ("ztc", "Zaaktypecatalogus"),
                            ("drc", "Documentregistratiecomponent"),
                            ("brc", "Besluitregistratiecomponent"),
                        ],
                        help_text="Component waarop autorisatie van toepassing is.",
                        max_length=50,
                        verbose_name="component",
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="Komma-gescheiden lijst van scope labels.",
                        size=None,
                        verbose_name="scopes",
                    ),
                ),
                (
                    "max_vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                        max_length=20,
                    ),
                ),
                (
                    "applicatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorisatie_specs",
                        to="authorizations.Applicatie",
                        verbose_name="applicatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "autorisatiespec",
                "verbose_name_plural": "autorisatiespecs",
                "unique_together": {("applicatie", "component")},
            },
        ),
    ]
