# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAPICredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_root",
                    models.URLField(
                        help_text="URL of the external API, ending in a trailing slash. Example: https://example.com/api/v1/",
                        unique=True,
                        verbose_name="API-root",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="Human readable label of the external API.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "header_key",
                    models.CharField(max_length=100, verbose_name="header key"),
                ),
                (
                    "header_value",
                    models.CharField(max_length=255, verbose_name="header value"),
                ),
            ],
            options={
                "verbose_name": "other external API credential",
                "verbose_name_plural": "other external API credentials",
            },
        ),
    ]
