# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 2.2.25 on 2022-01-24 13:56

import django.contrib.postgres.fields
from django.db import migrations, models
import vng_api_common.fields
import vng_api_common.models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0006_auto_20210323_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unieke naam van de rol", max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Gebruikersvriendelijke naam van de rol",
                        max_length=255,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ac", "Autorisaties API"),
                            ("nrc", "Notificaties API"),
                            ("zrc", "Zaken API"),
                            ("ztc", "Catalogi API"),
                            ("drc", "Documenten API"),
                            ("brc", "Besluiten API"),
                        ],
                        help_text="Component waarop autorisatie van toepassing is.",
                        max_length=50,
                        verbose_name="component",
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="Komma-gescheiden lijst van scope labels.",
                        size=None,
                        verbose_name="scopes",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het zaaktype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "informatieobjecttype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het informatieobjecttype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="informatieobjecttype",
                    ),
                ),
                (
                    "besluittype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het besluittype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="besluittype",
                    ),
                ),
                (
                    "max_vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                        max_length=20,
                    ),
                ),
            ],
            options={"verbose_name": "rol", "verbose_name_plural": "rollen",},
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
