# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0007_auto_20220318_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorisatiespec",
            name="component",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisaties API"),
                    ("nrc", "Notificaties API"),
                    ("zrc", "Zaken API"),
                    ("ztc", "Catalogi API"),
                    ("drc", "Documenten API"),
                    ("brc", "Besluiten API"),
                    ("cmc", "Contactmomenten API"),
                    ("kc", "Klanten API"),
                    ("vrc", "Verzoeken API"),
                ],
                help_text="Component waarop autorisatie van toepassing is.",
                max_length=50,
                verbose_name="component",
            ),
        ),
    ]
