# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-07-05 09:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0015_auto_20220318_1608"),
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
        ("autorisaties", "0009_alter_autorisatiespec_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogusAutorisatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ac", "Autorisaties API"),
                            ("nrc", "Notificaties API"),
                            ("zrc", "Zaken API"),
                            ("ztc", "Catalogi API"),
                            ("drc", "Documenten API"),
                            ("brc", "Besluiten API"),
                            ("cmc", "Contactmomenten API"),
                            ("kc", "Klanten API"),
                            ("vrc", "Verzoeken API"),
                        ],
                        help_text="Component waarop autorisatie van toepassing is.",
                        max_length=50,
                        verbose_name="component",
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="Komma-gescheiden lijst van scope labels.",
                        size=None,
                        verbose_name="scopes",
                    ),
                ),
                (
                    "max_vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                        max_length=20,
                    ),
                ),
                (
                    "applicatie",
                    models.ForeignKey(
                        help_text="The application to which this authorisation belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorizations.applicatie",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="The catalogi for which this authorisation gives permissions",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.catalogus",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalogus autorisatie",
                "verbose_name_plural": "catalogus autorisaties",
                "unique_together": {("applicatie", "catalogus", "component")},
            },
        ),
    ]
