# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0011_autorisatiespec_to_catalogusautorisatie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutorisatieSpec",
        ),
    ]
