# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0012_delete_autorisatiespec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogusautorisatie",
            name="component",
            field=models.CharField(
                choices=[
                    ("zrc", "Zaken API"),
                    ("drc", "Documenten API"),
                    ("brc", "Besluiten API"),
                ],
                help_text="Component waarop autorisatie van toepassing is.",
                max_length=50,
                verbose_name="component",
            ),
        ),
    ]
