# Generated by Django 4.2.19 on 2025-03-25 10:33

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0014_remove_orphaned_jwtsecrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogusautorisatie",
            name="max_vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                blank=True,
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
            ),
        ),
    ]
