# Generated by Django 5.2.15 on 2026-07-30 10:56

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
import vng_api_common.fields
import vng_api_common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorisaties', '0014_remove_orphaned_jwtsecrets'),
        ('catalogi', '0026_set_P0D_servicenorms_to_none'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique resource identifier (UUID4)', unique=True)),
                ('client_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='Comma separated list of consumer identifiers (client_ids)', size=None, verbose_name='client IDs')),
                ('label', models.CharField(help_text='A human readable representation of the application, for end users.', max_length=100)),
                ('heeft_alle_autorisaties', models.BooleanField(default=False, help_text='If all authorizations are given to this applicatie, no individual permissions have to be configured. Only enable this if you fully trust the consumer.', verbose_name='has all authorizations')),
            ],
            options={
                'verbose_name': 'applicatie',
                'verbose_name_plural': 'applicaties',
                'ordering': ['pk'],
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='catalogusautorisatie',
            name='applicatie',
            field=models.ForeignKey(help_text='The application to which this authorisation belongs', on_delete=django.db.models.deletion.CASCADE, to='autorisaties.applicatie'),
        ),
        migrations.CreateModel(
            name='Autorisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('ac', 'Autorisaties API'), ('nrc', 'Notificaties API'), ('zrc', 'Zaken API'), ('ztc', 'Catalogi API'), ('drc', 'Documenten API'), ('brc', 'Besluiten API'), ('cmc', 'Contactmomenten API'), ('kc', 'Klanten API'), ('vrc', 'Verzoeken API')], help_text='Component waarop autorisatie van toepassing is.', max_length=50, verbose_name='component')),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Komma-gescheiden lijst van scope labels.', size=None, verbose_name='scopes')),
                ('max_vertrouwelijkheidaanduiding', vng_api_common.fields.VertrouwelijkheidsAanduidingField(blank=True, choices=[('openbaar', 'Openbaar'), ('beperkt_openbaar', 'Beperkt openbaar'), ('intern', 'Intern'), ('zaakvertrouwelijk', 'Zaakvertrouwelijk'), ('vertrouwelijk', 'Vertrouwelijk'), ('confidentieel', 'Confidentieel'), ('geheim', 'Geheim'), ('zeer_geheim', 'Zeer geheim')], help_text='Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).', max_length=20)),
                ('applicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisaties', to='autorisaties.applicatie', verbose_name='applicatie')),
                ('besluittype', models.ForeignKey(blank=True, help_text='het besluittype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisaties', to='catalogi.besluittype')),
                ('informatieobjecttype', models.ForeignKey(blank=True, help_text='het informatieobjecttype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisaties', to='catalogi.informatieobjecttype')),
                ('zaaktype', models.ForeignKey(blank=True, help_text='het zaaktype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisaties', to='catalogi.zaaktype')),
            ],
            options={
                'verbose_name': 'autorisatie',
                'verbose_name_plural': 'autorisaties',
                'ordering': ['pk'],
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
