# Generated by Django 5.1.7 on 2025-04-15 07:27

import vng_api_common.fields
from django.db import migrations


from vng_api_common.constants import VA_MAPPING, REVERSE_VA_MAPPING


def forward(apps, schema_editor):
    CatalogusAutorisatie = apps.get_model("autorisaties", "CatalogusAutorisatie")
    BATCH_SIZE = 2000
    batch = []
    for instance in CatalogusAutorisatie.objects.iterator():
        instance._max_vertrouwelijkheidaanduiding = VA_MAPPING[
            instance.max_vertrouwelijkheidaanduiding
        ]
        batch.append(instance)

        if len(batch) >= BATCH_SIZE:
            CatalogusAutorisatie.objects.bulk_update(
                batch, ["_max_vertrouwelijkheidaanduiding"]
            )
            batch.clear()

    # Handle final batch
    if batch:
        CatalogusAutorisatie.objects.bulk_update(
            batch, ["_max_vertrouwelijkheidaanduiding"]
        )


def backward(apps, schema_editor):
    CatalogusAutorisatie = apps.get_model("autorisaties", "CatalogusAutorisatie")
    BATCH_SIZE = 2000
    batch = []
    for instance in CatalogusAutorisatie.objects.filter(
        max_vertrouwelijkheidaanduiding=""
    ).iterator():
        instance.max_vertrouwelijkheidaanduiding = REVERSE_VA_MAPPING[
            instance._max_vertrouwelijkheidaanduiding
        ]
        batch.append(instance)

        if len(batch) >= BATCH_SIZE:
            CatalogusAutorisatie.objects.bulk_update(
                batch, ["max_vertrouwelijkheidaanduiding"]
            )
            batch.clear()

    # Handle final batch
    if batch:
        CatalogusAutorisatie.objects.bulk_update(
            batch, ["max_vertrouwelijkheidaanduiding"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0014_remove_orphaned_jwtsecrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogusautorisatie",
            name="_max_vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingFieldInt(
                blank=True,
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                db_index=True,
                help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                null=True,
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
