# Generated by Django 5.2.15 on 2026-07-29 09:53

import django.contrib.postgres.fields
import django.db.models.deletion
import vng_api_common.fields
import vng_api_common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0018_alter_applicatie_options_alter_autorisatie_options'),
        ('autorisaties', '0014_remove_orphaned_jwtsecrets'),
        ('catalogi', '0026_set_P0D_servicenorms_to_none'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('ac', 'Autorisaties API'), ('nrc', 'Notificaties API'), ('zrc', 'Zaken API'), ('ztc', 'Catalogi API'), ('drc', 'Documenten API'), ('brc', 'Besluiten API'), ('cmc', 'Contactmomenten API'), ('kc', 'Klanten API'), ('vrc', 'Verzoeken API')], help_text='Component waarop autorisatie van toepassing is.', max_length=50, verbose_name='component')),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Komma-gescheiden lijst van scope labels.', size=None, verbose_name='scopes')),
                ('max_vertrouwelijkheidaanduiding', vng_api_common.fields.VertrouwelijkheidsAanduidingField(blank=True, choices=[('openbaar', 'Openbaar'), ('beperkt_openbaar', 'Beperkt openbaar'), ('intern', 'Intern'), ('zaakvertrouwelijk', 'Zaakvertrouwelijk'), ('vertrouwelijk', 'Vertrouwelijk'), ('confidentieel', 'Confidentieel'), ('geheim', 'Geheim'), ('zeer_geheim', 'Zeer geheim')], help_text='Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).', max_length=20)),
                ('applicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oz_autorisaties', to='authorizations.applicatie', verbose_name='applicatie')),
                ('besluittype', models.ForeignKey(blank=True, help_text='het besluittype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisaties', to='catalogi.besluittype')),
                ('informatieobjecttype', models.ForeignKey(blank=True, help_text='het informatieobjecttype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisaties', to='catalogi.informatieobjecttype')),
                ('zaaktype', models.ForeignKey(blank=True, help_text='het zaaktype waarop de autorisatie van toepassing is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisaties', to='catalogi.zaaktype')),
            ],
            options={
                'verbose_name': 'autorisatie',
                'verbose_name_plural': 'autorisaties',
                'ordering': ['pk'],
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
