# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.15 on 2026-07-31 08:49
from urllib.parse import urlparse

from django.db import migrations
from django.db.migrations import RunPython
from django.urls import Resolver404, resolve

from django_loose_fk.loaders import BaseLoader

SIZE = 500
loader = BaseLoader()


def move_applications(apps, schema_editor):
    ApplicationOld = apps.get_model("authorizations", "Applicatie")
    AutorisatieOld = apps.get_model("authorizations", "Autorisatie")

    ApplicationNew = apps.get_model("autorisaties", "Applicatie")
    AutorisatieNew = apps.get_model("autorisaties", "Autorisatie")
    CatalogusAutorisatie = apps.get_model("autorisaties", "CatalogusAutorisatie")

    ZaakType = apps.get_model("catalogi", "ZaakType")
    BesluitType = apps.get_model("catalogi", "BesluitType")
    InformatieObjectType = apps.get_model("catalogi", "InformatieObjectType")

    def _parse_url(url: str, expected_resource: str) -> str | None:
        """
        Validate url and return the related object.
        """
        if not url:
            return None

        if not loader.is_local_url(url):
            raise ValueError(f"{url} is not a local URL")

        path = urlparse(url).path

        try:
            resolve(path)
        except Resolver404:
            raise ValueError(f"{url} is not a valid URL")

        path_parts = path.split("/")
        resource = path_parts[-2]

        if resource != expected_resource:
            raise ValueError(f"{url} is not a expected {expected_resource} resource")

        uuid = path_parts[-1]

        match resource:
            case "besluittypen":
                model = BesluitType
            case "informatieobjecttypen":
                model = InformatieObjectType
            case "zaaktypen":
                model = ZaakType
            case _:
                raise ValueError(f"Unknown resource: {resource}")

        try:
            return model.objects.get(uuid=uuid)
        except model.DoesNotExist:
            raise ValueError(f"{url} does not exist")

    new_apps = [
        ApplicationNew(
            uuid=app_old.uuid,
            client_ids=app_old.client_ids,
            label=app_old.label,
            heeft_alle_autorisaties=app_old.heeft_alle_autorisaties,
        )
        for app_old in ApplicationOld.objects.iterator(chunk_size=SIZE)
    ]
    ApplicationNew.objects.bulk_create(new_apps, batch_size=SIZE)

    new_pk_by_uuid = {app_new.uuid: app_new.pk for app_new in new_apps}

    autorisaties = []
    for autorisatie_old in AutorisatieOld.objects.select_related("applicatie").iterator(
        chunk_size=SIZE
    ):
        zaaktype = _parse_url(autorisatie_old.zaaktype, "zaaktypen")
        informatieobjecttype = _parse_url(
            autorisatie_old.informatieobjecttype, "informatieobjecttypen"
        )
        besluittype = _parse_url(autorisatie_old.besluittype, "besluittypen")

        if any([autorisatie_old.component == "zrc" and not zaaktype, autorisatie_old.component == "drc" and not informatieobjecttype,  autorisatie_old.component == "brc" and not besluittype]):
            continue

        autorisaties.append(
            AutorisatieNew(
                applicatie_id=new_pk_by_uuid[autorisatie_old.applicatie.uuid],
                component=autorisatie_old.component,
                scopes=autorisatie_old.scopes,
                zaaktype=zaaktype,
                informatieobjecttype=informatieobjecttype,
                besluittype=besluittype,
                max_vertrouwelijkheidaanduiding=autorisatie_old.max_vertrouwelijkheidaanduiding,
            )
        )
    AutorisatieNew.objects.bulk_create(autorisaties, batch_size=SIZE)

    catalogus_autorisaties = []

    for ca in CatalogusAutorisatie.objects.select_related("applicatie").iterator(chunk_size=SIZE):
        ca.new_applicatie_id = new_pk_by_uuid[ca.applicatie.uuid]
        ca.applicatie_id = None
        catalogus_autorisaties.append(ca)

    CatalogusAutorisatie.objects.bulk_update(
        catalogus_autorisaties, ["new_applicatie_id", "applicatie_id"], batch_size=SIZE
    )

    ApplicationOld.objects.all().delete()

def reverse(apps, schema_editor):
    CatalogusAutorisatie = apps.get_model("autorisaties", "CatalogusAutorisatie")
    CatalogusAutorisatie.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "autorisaties",
            "0015_applicatie_alter_catalogusautorisatie_applicatie_and_more",
        ),
    ]

    operations = [
        RunPython(move_applications, reverse),
    ]
