# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.15 on 2026-07-31 13:02
import django
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('autorisaties', '0016_move_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogusautorisatie',
            name='applicatie',
        ),
        migrations.RenameField(
            model_name='catalogusautorisatie',
            old_name='new_applicatie',
            new_name='applicatie',
        ),
        migrations.AlterField(
            model_name='catalogusautorisatie',
            name='applicatie',
            field=models.ForeignKey(help_text='The application to which this authorisation belongs', on_delete=django.db.models.deletion.CASCADE, to='autorisaties.applicatie'),
        ),
    ]
