# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-08-20 10:57

from django.db import migrations


def _move_permission(apps, old_app: str, new_app: str,  old_model: str, new_model: str):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("auth", "Group")

    old_ct = ContentType.objects.get(app_label=old_app, model=old_model)
    new_ct = ContentType.objects.get(app_label=new_app, model=new_model)

    action_map = {}
    for old_perm in Permission.objects.filter(content_type=old_ct):
        action = old_perm.codename.split("_")[0]
        new_perm = Permission.objects.filter(
            content_type=new_ct, codename=f"{action}_{new_model}"
        ).first()
        if new_perm:
            action_map[old_perm.id] = new_perm

    for user in User.objects.filter(user_permissions__content_type=old_ct).distinct():
        for old_id, new_perm in action_map.items():
            if user.user_permissions.filter(id=old_id).exists():
                user.user_permissions.add(new_perm)
                user.user_permissions.remove(old_id)

    for group in Group.objects.filter(permissions__content_type=old_ct).distinct():
        for old_id, new_perm in action_map.items():
            if group.permissions.filter(id=old_id).exists():
                group.permissions.add(new_perm)
                group.permissions.remove(old_id)

def move_permissions(apps, schema_editor):
    _move_permission(apps, "authorizations", "autorisaties", "applicatie", "applicatie")
    _move_permission(apps, "authorizations", "autorisaties", "autorisatie", "autorisatie")

class Migration(migrations.Migration):

    dependencies = [
        ('autorisaties', '0017_remove_old_application_fk_on_catalogiautorisatie'),
    ]

    operations = [
        migrations.RunPython(move_permissions, migrations.RunPython.noop),
    ]
