# Generated by Django 2.0.6 on 2018-06-06 11:12

from django.db import migrations, models
import django.db.models.deletion
import vng_api_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.URLField()),
                ('datum_status_gezet', models.DateTimeField(help_text='De datum waarop de ZAAK de status heeft verkregen.')),
                ('statustoelichting', models.TextField(blank=True, help_text='Een, voor de initiator van de zaak relevante, toelichting op de status van een zaak.')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statussen',
            },
        ),
        migrations.CreateModel(
            name='Zaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaakidentificatie', models.CharField(help_text='De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.', max_length=40, unique=True, validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()])),
            ],
            options={
                'verbose_name': 'zaak',
                'verbose_name_plural': 'zaken',
            },
        ),
        migrations.AddField(
            model_name='status',
            name='zaak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Zaak'),
        ),
    ]
