# Generated by Django 2.0.6 on 2018-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='zaaktype',
            field=models.URLField(default='', help_text='URL naar het zaaktype in de CATALOGUS waar deze voorkomt'),
            preserve_default=False,
        ),
    ]
