# Generated by Django 2.0.6 on 2018-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20180611_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlantContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke aanduiding van een KLANTCONTACT', max_length=14, unique=True)),
                ('datumtijd', models.DateTimeField(help_text='De datum en het tijdstip waarop het KLANTCONTACT begint')),
                ('kanaal', models.CharField(blank=True, help_text='Het communicatiekanaal waarlangs het KLANTCONTACT gevoerd wordt', max_length=20)),
            ],
            options={
                'verbose_name': 'klantcontact',
                'verbose_name_plural': 'klantcontacten',
            },
        ),
    ]
