# Generated by Django 2.0.6 on 2018-07-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0026_rol_betrokkene'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisatorischeEenheid',
        ),
    ]
