# Generated by Django 2.0.6 on 2018-08-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0030_auto_20180813_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaak',
            old_name='zaakidentificatie',
            new_name='identificatie',
        ),
        migrations.AlterUniqueTogether(
            name='zaak',
            unique_together={('bronorganisatie', 'identificatie')},
        ),
    ]
