# Generated by Django 2.0.6 on 2018-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0031_auto_20180815_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='rolomschrijving_generiek',
        ),
        migrations.AlterField(
            model_name='rol',
            name='rolomschrijving',
            field=models.CharField(choices=[('Adviseur', 'Adviseur'), ('Behandelaar', 'Behandelaar'), ('Belanghebbende', 'Belanghebbende'), ('Beslisser', 'Beslisser'), ('Initiator', 'Initiator'), ('Klantcontacter', 'Klantcontacter'), ('Zaakcoördinator', 'Zaakcoördinator'), ('Mede-initiator', 'Mede-initiator')], help_text='Algemeen gehanteerde benaming van de aard van de ROL', max_length=80),
        ),
    ]
