# Generated by Django 2.0.6 on 2018-08-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0032_auto_20180816_1451'),
        ('datamodel', '0032_auto_20180816_1352'),
    ]

    operations = [
    ]
