# Generated by Django 2.0.6 on 2018-08-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_merge_20180816_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaakKenmerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenmerk', models.CharField(help_text='Identificeert uniek de zaak in een andere administratie.', max_length=40)),
                ('bron', models.CharField(help_text='De aanduiding van de administratie waar het kenmerk op slaat.', max_length=40)),
            ],
            options={
                'verbose_name': 'zaak kenmerk',
                'verbose_name_plural': 'zaak kenmerken',
            },
        ),
        migrations.AddField(
            model_name='zaak',
            name='omschrijving',
            field=models.CharField(blank=True, help_text='Een korte omschrijving van de zaak.', max_length=80),
        ),
        migrations.AddField(
            model_name='zaak',
            name='uiterlijke_einddatum_afdoening',
            field=models.DateField(blank=True, help_text='De laatste datum waarop volgens wet- en regelgeving de zaak afgerond dient te zijn.', null=True),
        ),
        migrations.AddField(
            model_name='zaak',
            name='verantwoordelijke_organisatie',
            field=models.URLField(default='http://www.vngrealisatie.nl/onbekend', help_text='URL naar de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaakkenmerk',
            name='zaak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Zaak'),
        ),
    ]
