# Generated by Django 2.0.6 on 2018-09-19 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0035_auto_20180919_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
    ]
