# Generated by Django 2.0.6 on 2018-12-19 10:27

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0037_auto_20181129_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='bronorganisatie',
            field=vng_api_common.fields.RSINField(help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef', max_length=9),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='verantwoordelijke_organisatie',
            field=vng_api_common.fields.RSINField(help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef', max_length=9),
        ),
    ]
