# Generated by Django 2.0.9 on 2019-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0044_zaak_resultaattoelichting'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='betalingsindicatie',
            field=models.CharField(blank=True, choices=[('nvt', 'Er is geen sprake van te betalen, met de zaak gemoeide, kosten.'), ('nog_niet', 'De met de zaak gemoeide kosten zijn (nog) niet betaald.'), ('gedeeltelijk', 'De met de zaak gemoeide kosten zijn gedeeltelijk betaald.'), ('geheel', 'De met de zaak gemoeide kosten zijn geheel betaald.')], help_text='Indicatie of de, met behandeling van de zaak gemoeide, kosten betaald zijn door de desbetreffende betrokkene.', max_length=20, verbose_name='betalingsindicatie'),
        ),
    ]
