# Generated by Django 2.0.9 on 2019-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0045_zaak_betalingsindicatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='laatste_betaaldatum',
            field=models.DateTimeField(blank=True, help_text='De datum waarop de meest recente betaling is verwerkt van kosten die gemoeid zijn met behandeling van de zaak.', null=True, verbose_name='laatste betaaldatum'),
        ),
    ]
