# Generated by Django 2.0.9 on 2019-01-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0049_zaak_selectielijstklasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='hoofdzaak',
            field=models.ForeignKey(blank=True, help_text='De verwijzing naar de ZAAK, waarom verzocht is door de initiator daarvan, die behandeld wordt in twee of meer separate ZAAKen waarvan de onderhavige ZAAK er één is.', limit_choices_to={'hoofdzaak__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deelzaken', to='datamodel.Zaak', verbose_name='is deelzaak van'),
        ),
    ]
