# Generated by Django 2.0.9 on 2019-01-28 10:44

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0052_auto_20190128_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='verlenging_duur',
            field=vng_api_common.fields.DaysDurationField(blank=True, help_text='Het aantal werkbare dagen waarmee de doorlooptijd van de behandeling van de ZAAK is verlengd (of verkort) ten opzichte van de eerder gecommuniceerde doorlooptijd.', max_duration=999, min_duration=1, null=True, verbose_name='duur verlenging'),
        ),
    ]
