# Generated by Django 2.0.9 on 2019-01-29 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0053_auto_20190128_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaakproductofdienst',
            name='zaak',
        ),
        migrations.AddField(
            model_name='zaak',
            name='producten_of_diensten',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000, verbose_name='URL naar product/dienst'), default=list, help_text='De producten en/of diensten die door de zaak worden voortgebracht. Dit zijn URLs naar de resources zoals die door de producten- en dienstencatalogus-API wordt ontsloten. De producten/diensten moeten bij het zaaktype vermeld zijn.', size=None),
        ),
        migrations.DeleteModel(
            name='ZaakProductOfDienst',
        ),
    ]
