# Generated by Django 2.0.10 on 2019-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0054_auto_20190129_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('resultaat_type', models.URLField()),
                ('toelichting', models.TextField(blank=True, help_text='Een toelichting op wat het resultaat van de zaak inhoudt.', max_length=1000)),
            ],
            options={
                'verbose_name': 'resultaat',
                'verbose_name_plural': 'resultaten',
            },
        ),
        migrations.RemoveField(
            model_name='zaak',
            name='resultaattoelichting',
        ),
        migrations.AddField(
            model_name='zaak',
            name='archiefactiedatum',
            field=models.DateField(blank=True, help_text='De datum waarop het gearchiveerde zaakdossier vernietigd moet worden dan wel overgebracht moet worden naar een archiefbewaarplaats. Wordt automatisch berekend bij het aanmaken of wijzigen van een RESULTAAT aan deze ZAAK indien nog leeg.', null=True, verbose_name='archiefactiedatum'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='archiefnominatie',
            field=models.CharField(blank=True, choices=[('blijvend_bewaren', 'Het zaakdossier moet bewaard blijven en op de Archiefactiedatum overgedragen worden naar een archiefbewaarplaats.'), ('vernietigen', 'Het zaakdossier moet op of na de Archiefactiedatum vernietigd worden.')], help_text='Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.', max_length=40, null=True, verbose_name='archiefnominatie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='archiefstatus',
            field=models.CharField(choices=[('nog_te_archiveren', 'De zaak cq. het zaakdossier is nog niet als geheel gearchiveerd.'), ('gearchiveerd', 'De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt.'), ('gearchiveerd_procestermijn_onbekend', 'De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt maar de vernietigingsdatum kan nog niet bepaald worden.'), ('overgedragen', 'De zaak cq. het zaakdossier is overgebracht naar een archiefbewaarplaats.')], default='nog_te_archiveren', help_text='Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.', max_length=40, verbose_name='archiefstatus'),
        ),
        migrations.AddField(
            model_name='zaakeigenschap',
            name='_naam',
            field=models.CharField(default='-see-ztc-', help_text='De naam van de EIGENSCHAP (overgenomen uit ZTC).', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zaak',
            name='opschorting_reden',
            field=models.CharField(blank=True, help_text='Omschrijving van de reden voor het opschorten van de behandeling van de zaak.', max_length=200, verbose_name='reden opschorting'),
        ),
        migrations.AddField(
            model_name='resultaat',
            name='zaak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Zaak'),
        ),
    ]
