# Generated by Django 2.0.13 on 2019-05-23 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0056_auto_20190311_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaakBesluit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('besluit', models.URLField(help_text='URL-referentie naar het informatieobject in het BRC, waar ook de relatieinformatie opgevraagd kan worden.', max_length=1000, verbose_name='besluit')),
                ('zaak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Zaak')),
            ],
            options={
                'verbose_name': 'zaakbesluit',
                'verbose_name_plural': 'zaakbesluiten',
            },
        ),
        migrations.AlterUniqueTogether(
            name='zaakbesluit',
            unique_together={('zaak', 'besluit')},
        ),
    ]
