# Generated by Django 2.0.13 on 2019-05-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrc_datamodel', '0057_auto_20190523_1513'),
        ('zrc_datamodel', '0057_auto_20190517_1351'),
    ]

    operations = [
    ]
