# Generated by Django 2.2.2 on 2019-06-20 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0062_rol_registratiedatum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natuurlijkpersoon',
            old_name='nummer_ander_natuurlijk_persoon',
            new_name='anp_identificatie',
        ),
        migrations.RenameField(
            model_name='natuurlijkpersoon',
            old_name='burgerservicenummer',
            new_name='inp_bsn',
        ),
        migrations.RenameField(
            model_name='nietnatuurlijkpersoon',
            old_name='nummer_ander_nietnatuurlijk_persoon',
            new_name='ann_identificatie',
        ),
        migrations.RenameField(
            model_name='nietnatuurlijkpersoon',
            old_name='rsin',
            new_name='inn_nnp_id',
        ),
        migrations.RenameField(
            model_name='nietnatuurlijkpersoon',
            old_name='rechtsvorm',
            new_name='inn_rechtsvorm',
        ),
        migrations.RenameField(
            model_name='natuurlijkpersoon',
            old_name='a_nummer',
            new_name='inp_a_nummer',
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='inp_a_nummer',
            field=models.CharField(blank=True, help_text='Het administratienummer van de persoon, bedoeld in de Wet BRP', max_length=10, validators=[django.core.validators.RegexValidator(code='a-nummer-incorrect-format', message='inpA_nummer must consist of 10 digits', regex='^[1-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='nietnatuurlijkpersoon',
            name='ann_identificatie',
            field=models.CharField(blank=True, help_text='Het door de gemeente uitgegeven unieke nummer voor een ANDER NIET-NATUURLIJK PERSOON', max_length=17),
        ),
    ]
