# Generated by Django 2.2.2 on 2019-06-28 09:38
import itertools
import operator

from django.db import migrations

from ..constants import AardZaakRelatie


def copy_to_relation(apps, schema_editor):
    Zaak = apps.get_model("datamodel", "Zaak")
    RelevanteZaakRelatie = apps.get_model("datamodel", "RelevanteZaakRelatie")

    default_aard = AardZaakRelatie.bijdrage

    relaties = []
    for zaak in Zaak.objects.filter(relevante_andere_zaken__len__gt=0):
        relaties += [
            RelevanteZaakRelatie(zaak=zaak, aard_relatie=default_aard, url=url)
            for url in zaak.relevante_andere_zaken
        ]

    RelevanteZaakRelatie.objects.bulk_create(relaties)


def copy_from_relation(apps, schema_editor):
    RelevanteZaakRelatie = apps.get_model("datamodel", "RelevanteZaakRelatie")

    relaties = RelevanteZaakRelatie.objects.select_related("zaak").order_by("zaak__id")
    for zaak, _relaties in itertools.groupby(relaties, key=operator.itemgetter("zaak")):
        zaak.relevante_andere_zaken = [relatie.url for relatie in relaties]
        zaak.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0063_auto_20190628_0938'),
    ]

    operations = [
        migrations.RunPython(copy_to_relation, copy_from_relation),
    ]
