# Generated by Django 2.2.2 on 2019-06-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0064_copy_relevante_andere_zaken'),
        ('datamodel', '0063_auto_20190620_1743'),
    ]

    operations = [
    ]
