# Generated by Django 2.2.2 on 2019-06-27 09:08

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0066_auto_20190628_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huishouden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(help_text='Uniek identificerend administratienummer van een huishouden zoals toegekend door de gemeente waarin het huishouden woonachtig is.', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WozDeelobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer_WOZ_deel_object', models.CharField(help_text='Uniek identificatienummer voor het deelobject binnen een WOZ-object.', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ZakelijkRecht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('avg_aard', models.CharField(help_text='aanduiding voor de aard van het recht', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='medewerker',
            name='zaakobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.AddField(
            model_name='natuurlijkpersoon',
            name='zaakobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.AddField(
            model_name='nietnatuurlijkpersoon',
            name='zaakobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='zaakobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='zaakobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Rol'),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Rol'),
        ),
        migrations.AlterField(
            model_name='nietnatuurlijkpersoon',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Rol'),
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Rol'),
        ),
        migrations.AlterField(
            model_name='vestiging',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Rol'),
        ),
        migrations.AlterField(
            model_name='zaakobject',
            name='object_type',
            field=models.CharField(choices=[('adres', 'Adres'), ('besluit', 'Besluit'), ('buurt', 'Buurt'), ('enkelvoudigDocument', 'Enkelvoudig document'), ('gemeente', 'Gemeente'), ('gemeentelijkeOpenbareRuimte', 'Gemeentelijke openbare ruimte'), ('huishouden', 'Huishouden'), ('inrichtingselement', 'Inrichtingselement'), ('kadastraleOnroerendeZaak', 'Kadastrale onroerende zaak'), ('kunstwerkdeel', 'Kunstwerkdeel'), ('maatschappelijkeActiviteit', 'Maatschappelijke activiteit'), ('medewerker', 'Medewerker'), ('natuurlijkPersoon', 'Natuurlijk persoon'), ('nietNatuurlijkPersoon', 'Niet-natuurlijk persoon'), ('openbareRuimte', 'Openbare ruimte'), ('organisatorischeEenheid', 'Organisatorische eenheid'), ('pand', 'Pand'), ('spoorbaandeel', 'Spoorbaandeel'), ('status', 'Status'), ('terreindeel', 'Terreindeel'), ('terreinGebouwdObject', 'Terrein gebouwd object'), ('vestiging', 'Vestiging'), ('waterdeel', 'Waterdeel'), ('wegdeel', 'Wegdeel'), ('wijk', 'Wijk'), ('woonplaats', 'Woonplaats'), ('wozDeelobject', 'Woz deel object'), ('wozObject', 'Woz object'), ('wozWaarde', 'Woz waarde'), ('zakelijkRecht', 'Zakelijk recht'), ('overige', 'Overige')], help_text='Beschrijft het type object gerelateerd aan de zaak', max_length=100),
        ),
        migrations.CreateModel(
            name='ZakelijkRechtHeeftAlsGerechtigde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakelijk_recht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heeft_als_gerechtigde', to='datamodel.ZakelijkRecht')),
            ],
        ),
        migrations.AddField(
            model_name='zakelijkrecht',
            name='zaakobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.CreateModel(
            name='WozWaarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waardepeildatum', models.CharField(help_text='De datum waarnaar de waarde van het WOZ-object wordt bepaald.', max_length=9)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='WozObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wozobject_nummer', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('oao_identificatie', models.CharField(max_length=100)),
                ('wpl_woonplaats_naam', models.CharField(max_length=80)),
                ('gor_openbare_ruimte_naam', models.CharField(help_text='Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming', max_length=80)),
                ('aoa_postcode', models.CharField(blank=True, max_length=7)),
                ('aoa_huisnummer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('aoa_huisletter', models.CharField(blank=True, max_length=1)),
                ('aoa_huisnummertoevoeging', models.CharField(blank=True, max_length=4)),
                ('locatie_omschrijving', models.CharField(max_length=1000)),
                ('woz_deelobject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_onderdeel_van', to='datamodel.WozDeelobject')),
                ('woz_warde', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_voor', to='datamodel.WozWaarde')),
                ('zaakobject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.AddField(
            model_name='wozdeelobject',
            name='zaakobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.CreateModel(
            name='Woonplaats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('woonplaats_naam', models.CharField(help_text='De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS toegekende benaming.', max_length=80)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Wijk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wijk_code', models.CharField(help_text='De code behorende bij de naam van de wijk.', max_length=2)),
                ('wijk_naam', models.CharField(help_text='De naam van de wijk, zoals die door het CBS wordt gebruikt.', max_length=40)),
                ('gem_gemeente_code', models.CharField(help_text='Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid', max_length=4)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Wegdeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.TextField(blank=True, help_text='De benaming van het OBJECT', max_length=500)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Waterdeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_waterdeel', models.CharField(help_text='Specificatie van het soort water', max_length=50)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.TextField(blank=True, help_text='De benaming van het OBJECT', max_length=500)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='TerreinGebouwdObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('num_identificatie', models.CharField(max_length=100)),
                ('oao_identificatie', models.CharField(max_length=100)),
                ('wpl_woonplaats_naam', models.CharField(max_length=80)),
                ('gor_openbare_ruimte_naam', models.CharField(help_text='Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming', max_length=80)),
                ('aoa_postcode', models.CharField(blank=True, max_length=7)),
                ('aoa_huisnummer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('aoa_huisletter', models.CharField(blank=True, max_length=1)),
                ('aoa_huisnummertoevoeging', models.CharField(blank=True, max_length=4)),
                ('ogo_locatie_aanduiding', models.CharField(max_length=100)),
                ('huishouden', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_gehuisvest_in', to='datamodel.Huishouden')),
                ('zaakobject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Terreindeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.TextField(blank=True, help_text='De benaming van het OBJECT', max_length=500)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Spoorbaandeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('breedspoor', 'breedspoor'), ('normaalspoor', 'normaalspoor'), ('smalspoor', 'smalspoor'), ('spoorbaan', 'spoorbaan')], help_text='Specificatie van het soort Spoorbaan', max_length=40)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.TextField(blank=True, help_text='De benaming van het OBJECT', max_length=500)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Overige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overige_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='OpenbareRuimte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('wpl_woonplaats_naam', models.CharField(max_length=80)),
                ('gor_openbare_ruimte_naam', models.CharField(help_text='Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming', max_length=80)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='MaatschappelijkeActiviteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvk_nummer', models.CharField(help_text='Landelijk uniek identificerend administratienummer van een MAATSCHAPPELIJKE ACTIVITEIT zoals toegewezen door de Kamer van Koophandel (KvK).', max_length=8)),
                ('handelsnaam', models.CharField(help_text='De naam waaronder de onderneming handelt.', max_length=200)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Kunstwerkdeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Specificatie van het soort Kunstwerk waartoe het kunstwerkdeel behoort.', max_length=40)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.CharField(max_length=80)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='KadastraleOnroerendeZaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadastrale_identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('kadastrale_aanduiding', models.CharField(help_text='De typering van de kadastrale aanduiding van een onroerende zaak conform Kadaster', max_length=1000)),
                ('zaakobject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
                ('zakelijk_recht', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heeft_betrekking_op', to='datamodel.ZakelijkRecht')),
            ],
        ),
        migrations.CreateModel(
            name='Inrichtingselement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bak', 'Bak'), ('Bord', 'Bord'), ('Installatie', 'Installatie'), ('Kast', 'Kast'), ('Mast', 'Mast'), ('Paal', 'Paal'), ('Sensor', 'Sensor'), ('Straatmeubilair', 'Straatmeubilair'), ('Waterinrichtingselement', 'Waterinrichtingselement'), ('Weginrichtingselement', 'Weginrichtingselement')], help_text='Specificatie van de aard van het inrichtingselement.', max_length=30)),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('naam', models.TextField(blank=True, help_text='De benaming van het OBJECT', max_length=500)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.AddField(
            model_name='huishouden',
            name='zaakobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject'),
        ),
        migrations.CreateModel(
            name='GemeentelijkeOpenbareRuimte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('openbare_ruimte_naam', models.CharField(help_text='Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming', max_length=80)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Gemeente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemeente_naam', models.CharField(help_text='De officiële door de gemeente vastgestelde gemeentenaam.', max_length=80)),
                ('gemeente_code', models.CharField(help_text='Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid', max_length=4)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(help_text='De unieke identificatie van het OBJECT', max_length=100)),
                ('wpl_woonplaats_naam', models.CharField(max_length=80)),
                ('gor_openbare_ruimte_naam', models.CharField(help_text='Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming', max_length=80)),
                ('huisnummer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('huisletter', models.CharField(blank=True, max_length=1)),
                ('huisnummertoevoeging', models.CharField(blank=True, max_length=4)),
                ('postcode', models.CharField(blank=True, max_length=7)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
        ),
        migrations.AddField(
            model_name='natuurlijkpersoon',
            name='zakelijk_rechtHeeft_als_gerechtigde',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZakelijkRechtHeeftAlsGerechtigde'),
        ),
        migrations.AddField(
            model_name='nietnatuurlijkpersoon',
            name='zakelijk_rechtHeeft_als_gerechtigde',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZakelijkRechtHeeftAlsGerechtigde'),
        ),
        migrations.CreateModel(
            name='Buurt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buurt_code', models.CharField(help_text='De code behorende bij de naam van de buurt', max_length=2)),
                ('buurt_naam', models.CharField(help_text='De naam van de buurt, zoals die door het CBS wordt gebruikt.', max_length=40)),
                ('gem_gemeente_code', models.CharField(help_text='Een numerieke aanduiding waarmee een Nederlandse gemeente uniek wordt aangeduid', max_length=4)),
                ('wyk_wijk_code', models.CharField(help_text='De code behorende bij de naam van de wijk', max_length=2)),
                ('zaakobject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ZaakObject')),
            ],
            options={
                'unique_together': {('buurt_code', 'wyk_wijk_code')},
            },
        ),
    ]
