# Generated by Django 2.2.2 on 2019-06-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0067_auto_20190627_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaakobject',
            old_name='object_type',
            new_name='type',
        ),
    ]
