# Generated by Django 2.2.2 on 2019-07-01 15:01

from django.db import migrations


def rewrite_urls(apps, schema_editor):
    Zaak = apps.get_model("datamodel.Zaak")
    Status = apps.get_model("datamodel.Status")
    ZaakEigenschap = apps.get_model("datamodel.ZaakEigenschap")

    zaken = Zaak.objects.filter(zaaktype__regex=r"^https?://.*/catalogussen/[\w-]+/.*")
    for zaak in zaken:
        bits = zaak.zaaktype.split("/")
        index = bits.index("catalogussen")

        new_bits = bits[0:index] + bits[index + 2:]
        zaak.zaaktype = "/".join(new_bits)
        zaak.save()

    statussen = Status.objects.filter(
        status_type__regex=r"^https?://.*/catalogussen/[\w-]+/zaaktypen/[\w-]+/.*"
    )
    for status in statussen:
        bits = status.status_type.split("/")
        index = bits.index("catalogussen")

        new_bits = bits[0:index] + bits[index + 4:]
        status.status_type = "/".join(new_bits)
        status.save()

    eigenschappen = ZaakEigenschap.objects.filter(
        eigenschap__regex=r"^https?://.*/catalogussen/[\w-]+/zaaktypen/[\w-]+/.*"
    )
    for eigenschap in eigenschappen:
        bits = eigenschap.eigenschap.split("/")
        index = bits.index("catalogussen")

        new_bits = bits[0:index] + bits[index + 4:]
        eigenschap.eigenschap = "/".join(new_bits)
        eigenschap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0070_auto_20190627_1404'),
    ]

    operations = [
        migrations.RunPython(rewrite_urls, migrations.RunPython.noop),
    ]
