# Generated by Django 2.2.2 on 2019-07-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0072_auto_20190705_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natuurlijkpersoon',
            name='sub_verblijf_buitenland',
        ),
        migrations.RemoveField(
            model_name='nietnatuurlijkpersoon',
            name='sub_verblijf_buitenland',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='sub_verblijf_buitenland',
        ),
        migrations.CreateModel(
            name='SubVerblijfBuitenland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnd_landcode', models.CharField(help_text='De code, behorende bij de landnaam, zoals opgenomen in de Land/Gebied-tabel van de BRP.', max_length=4)),
                ('lnd_landnaam', models.CharField(help_text='De naam van het land, zoals opgenomen in de Land/Gebied-tabel van de BRP.', max_length=40)),
                ('sub_adres_buitenland_1', models.CharField(blank=True, max_length=35)),
                ('sub_adres_buitenland_2', models.CharField(blank=True, max_length=35)),
                ('sub_adres_buitenland_3', models.CharField(blank=True, max_length=35)),
                ('natuurlijkpersoon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_verblijf_buitenland', to='datamodel.NatuurlijkPersoon')),
                ('nietnatuurlijkpersoon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_verblijf_buitenland', to='datamodel.NietNatuurlijkPersoon')),
                ('vestiging', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_verblijf_buitenland', to='datamodel.Vestiging')),
            ],
        ),
    ]
