# Generated by Django 2.2.2 on 2019-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0073_auto_20190705_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='indicatie_machtiging',
            field=models.CharField(blank=True, choices=[('gemachtigde', 'De betrokkene in de rol bij de zaak is door een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen'), ('machtiginggever', 'De betrokkene in de rol bij de zaak heeft een andere betrokkene bij dezelfde zaak gemachtigd om namens hem of haar te handelen')], help_text='Indicatie_machtiging', max_length=40),
        ),
        migrations.AlterField(
            model_name='kunstwerkdeel',
            name='type',
            field=models.CharField(choices=[('Keermuur', 'Keermuur'), ('Overkluizing', 'Overkluizing'), ('Duiker', 'Duiker'), ('Faunavoorziening', 'Faunavoorziening'), ('Vispassage', 'Vispassage'), ('Bodemval', 'Bodemval'), ('Coupure', 'Coupure'), ('Ponton', 'Ponton'), ('Voorde', 'Voorde'), ('Hoogspanningsmast', 'Hoogspanningsmast'), ('Gemaal', 'Gemaal'), ('Perron', 'Perron'), ('Sluis', 'Sluis'), ('Strekdam', 'Strekdam'), ('Steiger', 'Steiger'), ('Stuw', 'Stuw')], help_text='Specificatie van het soort Kunstwerk waartoe het kunstwerkdeel behoort.', max_length=40),
        ),
        migrations.AlterField(
            model_name='waterdeel',
            name='type_waterdeel',
            field=models.CharField(choices=[('Zee', 'Zee'), ('Waterloop', 'Waterloop'), ('Watervlakte', 'Watervlakte'), ('Greppel, droge sloot', 'Greppel, droge sloot')], help_text='Specificatie van het soort water', max_length=50),
        ),
    ]
