# Generated by Django 2.2.2 on 2019-07-11 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0074_auto_20190709_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='producten_of_diensten',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000, verbose_name='URL naar product/dienst'), blank=True, default=list, help_text='De producten en/of diensten die door de zaak worden voortgebracht. Dit zijn URLs naar de resources zoals die door de producten- en dienstencatalogus-API wordt ontsloten. De producten/diensten moeten bij het zaaktype vermeld zijn.', size=None),
        ),
    ]
