# Generated by Django 2.2.2 on 2019-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0080_auto_20190717_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrichtingselement',
            name='type',
            field=models.CharField(choices=[('bak', 'Bak'), ('bord', 'Bord'), ('installatie', 'Installatie'), ('kast', 'Kast'), ('mast', 'Mast'), ('paal', 'Paal'), ('sensor', 'Sensor'), ('straatmeubilair', 'Straatmeubilair'), ('waterinrichtingselement', 'Waterinrichtingselement'), ('weginrichtingselement', 'Weginrichtingselement')], help_text='Specificatie van de aard van het inrichtingselement.', max_length=30),
        ),
        migrations.AlterField(
            model_name='kunstwerkdeel',
            name='type',
            field=models.CharField(choices=[('keermuur', 'Keermuur'), ('overkluizing', 'Overkluizing'), ('duiker', 'Duiker'), ('faunavoorziening', 'Faunavoorziening'), ('vispassage', 'Vispassage'), ('bodemval', 'Bodemval'), ('coupure', 'Coupure'), ('ponton', 'Ponton'), ('voorde', 'Voorde'), ('hoogspanningsmast', 'Hoogspanningsmast'), ('gemaal', 'Gemaal'), ('perron', 'Perron'), ('sluis', 'Sluis'), ('strekdam', 'Strekdam'), ('steiger', 'Steiger'), ('stuw', 'Stuw')], help_text='Specificatie van het soort Kunstwerk waartoe het kunstwerkdeel behoort.', max_length=40),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('m', 'Man'), ('v', 'Vrouw'), ('o', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1),
        ),
        migrations.AlterField(
            model_name='nietnatuurlijkpersoon',
            name='inn_rechtsvorm',
            field=models.CharField(blank=True, choices=[('besloten_vennootschap', 'Besloten Vennootschap'), ('cooperatie_europees_economische_samenwerking', 'Cooperatie, Europees Economische Samenwerking'), ('europese_cooperatieve_venootschap', 'Europese Cooperatieve Venootschap'), ('europese_naamloze_vennootschap', 'Europese Naamloze Vennootschap'), ('kerkelijke_organisatie', 'Kerkelijke Organisatie'), ('naamloze_vennootschap', 'Naamloze Vennootschap'), ('onderlinge_waarborg_maatschappij', 'Onderlinge Waarborg Maatschappij'), ('overig_privaatrechtelijke_rechtspersoon', 'Overig privaatrechtelijke rechtspersoon'), ('stichting', 'Stichting'), ('vereniging', 'Vereniging'), ('vereniging_van_eigenaars', 'Vereniging van Eigenaars'), ('publiekrechtelijke_rechtspersoon', 'Publiekrechtelijke Rechtspersoon'), ('vennootschap_onder_firma', 'Vennootschap onder Firma'), ('maatschap', 'Maatschap'), ('rederij', 'Rederij'), ('commanditaire_vennootschap', 'Commanditaire vennootschap'), ('kapitaalvennootschap_binnen_eer', 'Kapitaalvennootschap binnen EER'), ('overige_buitenlandse_rechtspersoon_vennootschap', 'Overige buitenlandse rechtspersoon vennootschap'), ('kapitaalvennootschap_buiten_eer', 'Kapitaalvennootschap buiten EER')], help_text='De juridische vorm van de NIET-NATUURLIJK PERSOON.', max_length=50),
        ),
        migrations.AlterField(
            model_name='waterdeel',
            name='type_waterdeel',
            field=models.CharField(choices=[('zee', 'Zee'), ('waterloop', 'Waterloop'), ('watervlakte', 'Watervlakte'), ('greppel_droge_sloot', 'Greppel, droge sloot')], help_text='Specificatie van het soort water', max_length=50),
        ),
    ]
