# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-03-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_internalservices_initial"),
        ("config", "0003_auto_20200326_0909"),
    ]

    operations = []
