# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_merge_20200326_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalservice",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the API is enabled in Open Zaak.",
                verbose_name="enabled",
            ),
        ),
        migrations.AlterField(
            model_name="internalservice",
            name="nlx",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the service is to be provided over NLX.",
                verbose_name="nlx",
            ),
        ),
    ]
