# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0007_admin_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlxconfig",
            name="outway",
            field=models.URLField(
                blank=True,
                help_text="Example: http://my-outway.nlx:8080",
                verbose_name="NLX outway address",
            ),
        ),
    ]
