# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_auto_20200416_0903"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_unpublished_typen",
                    models.BooleanField(
                        default=False,
                        help_text="Normally, a type must be published before an object of that type (ZAAK, INFORMATIEOBJECT, BESLUIT) can be created from it. Enabling this flag bypasses this check. This is intended to support development - do not enable this in production.",
                        verbose_name="allow concept *typen",
                    ),
                ),
            ],
            options={"verbose_name": "feature flags",},
        ),
    ]
