# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.17 on 2021-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_featureflags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalservice",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisaties API"),
                    ("nrc", "Notificaties API"),
                    ("zrc", "Zaken API"),
                    ("ztc", "Catalogi API"),
                    ("drc", "Documenten API"),
                    ("brc", "Besluiten API"),
                ],
                max_length=50,
                unique=True,
                verbose_name="API type",
            ),
        ),
    ]
