# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 2.2.27 on 2022-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0012_delete_nlxconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalservice",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("ac", "Autorisaties API"),
                    ("nrc", "Notificaties API"),
                    ("zrc", "Zaken API"),
                    ("ztc", "Catalogi API"),
                    ("drc", "Documenten API"),
                    ("brc", "Besluiten API"),
                    ("cmc", "Contactmomenten API"),
                    ("kc", "Klanten API"),
                ],
                max_length=50,
                unique=True,
                verbose_name="API type",
            ),
        ),
    ]
