# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-03-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_auto_20220318_1558"),
        ("config", "0013_remove_internalservice_nlx"),
    ]

    operations = []
