# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 5.2.3 on 2025-09-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_alter_internalservice_api_type"),
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudEventConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not cloudevents should be sent on Zaak create",
                    ),
                ),
                (
                    "oin",
                    models.CharField(
                        help_text="The OIN that will be used in the source field of the cloudevent.",
                        max_length=20,
                        verbose_name="OIN",
                    ),
                ),
                (
                    "zaak_create_event_type",
                    models.CharField(
                        help_text="The type that will be used for the zaak create cloudevent",
                        max_length=64,
                        verbose_name="Zaak create cloud event type",
                    ),
                ),
                (
                    "status_update_event_type",
                    models.CharField(
                        default="zaak-status-update",
                        help_text="The type that will be used for the status update cloudevent",
                        max_length=64,
                        verbose_name="Status update cloud event type",
                    ),
                ),
                (
                    "zaak_read_event_type",
                    models.CharField(
                        default="zaak-read",
                        help_text="The type that will be used for the zaak read cloudevent",
                        max_length=64,
                        verbose_name="Zaak read cloud event type",
                    ),
                ),
                (
                    "logius_service",
                    models.ForeignKey(
                        help_text="The service to which cloudevents will be sent on Zaak create",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "CloudEvents configuration",
                "verbose_name_plural": "CloudEvents configurations",
            },
        ),
    ]
