# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_alter_internalservice_api_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflags",
            name="improved_pagination_performance",
            field=models.BooleanField(
                default=False,
                help_text="Improve performance for paginated API endpoints by disabling exact counts,this causes an extra attribute to be set in the API responses (`countExact`).",
                verbose_name="improved API pagination performance",
            ),
        ),
    ]
