# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 5.2.3 on 2025-09-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_alter_internalservice_api_type"),
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudEventConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not cloud events should be sent for operations on Zaak",
                    ),
                ),
                (
                    "webhook_path",
                    models.CharField(
                        default="/event/zaak",
                        help_text="Relative path on the webhook service where cloud events will be sent. ",
                        max_length=255,
                        verbose_name="Webhook path",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="The value of the source field of the cloud events.",
                        max_length=100,
                        verbose_name="Cloud event source",
                    ),
                ),
                (
                    "webhook_service",
                    models.ForeignKey(
                        help_text="The service to which cloudevents will be sent on Zaak create",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "CloudEvents configuration",
                "verbose_name_plural": "CloudEvents configurations",
            },
        ),
    ]
