# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.15 on 2024-10-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("config", "0015_alter_internalservice_api_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudEventConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not cloudevents should be sent on Zaak create",
                    ),
                ),
                (
                    "oin",
                    models.CharField(
                        help_text="The OIN that will be used in the source field of the cloudevent.",
                        max_length=20,
                        verbose_name="OIN",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The type that will be used for the cloudevent",
                        max_length=64,
                        verbose_name="Cloud event type",
                    ),
                ),
                (
                    "logius_service",
                    models.ForeignKey(
                        help_text="The service to which cloudevents will be sent on Zaak create",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "CloudEvents configuration",
                "verbose_name_plural": "CloudEvents configurations",
            },
        ),
    ]
