# Generated by Django 5.2.7 on 2025-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_cloudeventconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudEventConfig',
        ),
    ]
