# Generated by Django 5.2.8 on 2026-01-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_cloudeventconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudEventConfig',
        ),
    ]
