# Generated by Django 4.2.15 on 2024-10-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0017_rename_type_cloudeventconfig_zaak_create_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudeventconfig",
            name="status_update_event_type",
            field=models.CharField(
                default="zaak-status-update",
                help_text="The type that will be used for the status update cloudevent",
                max_length=64,
                verbose_name="Status update cloud event type",
            ),
        ),
        migrations.AlterField(
            model_name="cloudeventconfig",
            name="zaak_create_event_type",
            field=models.CharField(
                help_text="The type that will be used for the zaak create cloudevent",
                max_length=64,
                verbose_name="Zaak create cloud event type",
            ),
        ),
    ]
