# Generated by Django 4.2.15 on 2024-10-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0018_cloudeventconfig_status_update_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudeventconfig",
            name="zaak_read_event_type",
            field=models.CharField(
                default="zaak-read",
                help_text="The type that will be used for the zaak read cloudevent",
                max_length=64,
                verbose_name="Zaak read cloud event type",
            ),
        ),
    ]
