---

- name: Deploy Open Zaak on a single server
  hosts: all

  collections:
    - openzaak.deploy

  vars_files:
    - vars/postgres.yml
    - vars/open-zaak.yml

  vars:
    # postgresql vars - from secrets
    postgresql_users:
      - name: "{{ openzaak_db_username }}"
        password: "{{ openzaak_db_password }}"
        port: "{{ openzaak_db_port }}"
    postgresql_databases:
      - name: "{{ openzaak_db_name }}"
        owner: "{{ openzaak_db_username }}"
        port: "{{ openzaak_db_port }}"

    # certbot vars
    certbot_admin_email: support@maykinmedia.nl
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    # certbot_create_standalone_stop_services: ['nginx']
    certbot_certs:
      - domains:
          - "{{ openzaak_domain }}"

    # nginx vars
    nginx_http_template_enable: true

  roles:
    - role: os_setup

    - role: geerlingguy.postgresql
      tags:
        - db

    - role: geerlingguy.docker

    - role: geerlingguy.certbot

    - role: app_database
      vars:
        app_db_provision_user: no
        app_db_provision_database: no
        app_db_become_user: postgres

        app_db_host: ''
        app_db_port: "{{ openzaak_db_port }}"
        app_db_name: "{{ openzaak_db_name }}"
        app_db_extensions:
          - postgis
          - pg_trgm
      tags:
        - app_db

    - role: open_zaak_docker
      vars:
        openzaak_version: '1.19.0'  # see https://hub.docker.com/r/openzaak/open-zaak/tags
      tags:
        - replicas

    - role: nginxinc.nginx
      vars:
        nginx_http_template:
          default:
            # set by open_notificaties_docker role
            template_file: "{{ openzaak_nginx_template }}"
            conf_file_name: openzaak.conf
            conf_file_location: /etc/nginx/conf.d/

        # set by the open_zaak_docker role while provisioning the docker volume
        openzaak_volume_path: "{{ openzaak_volume.volume.Mountpoint }}"
      tags:
        - replicas
