collections:
  - name: openzaak.deploy
    version: 0.17.0
    source: https://galaxy.ansible.com

roles:
  - src: geerlingguy.postgresql
  - src: geerlingguy.docker
  - src: geerlingguy.certbot
  - src: nginxinc.nginx
    version: 0.12.0
