---

# Set up the internal services to network containers

- name: Set up Redis cache service
  k8s:
    state: present
    name: cache
    namespace: "{{ opennotificaties_namespace }}"
    definition: "{{ lookup('template', 'redis-svc.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes

- name: Set up RabbitMQ broker service
  k8s:
    state: present
    name: rabbitmq
    namespace: "{{ opennotificaties_namespace }}"
    definition: "{{ lookup('template', 'rabbitmq-svc.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes


- name: Set up Open Notificaties service
  k8s:
    state: present
    name: opennotificaties
    namespace: "{{ opennotificaties_namespace }}"
    definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
