---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # default config from the container, scraping itself
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  # docker service discovery
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels:
          - __meta_docker_container_name
        regex: /(.*)
        target_label: container
      - source_labels:
          - __meta_docker_container_log_stream
        target_label: logstream
      - source_labels:
          - __meta_docker_container_label_client
        target_label: client
      - source_labels:
          - __meta_docker_container_label_app
        target_label: app
      - source_labels:
          - __meta_docker_container_label_target
        target_label: target
      - source_labels:
          - __meta_docker_container_label_service
        target_label: service
      - source_labels:
          - __meta_docker_container_label_app
        action: drop
        regex: promtail
    pipeline_stages:
      - docker: {}
      - static_labels:
          job: docker
          instance: docker.host.internal
