# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-24 10:05

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import openzaak.components.catalogi.models.validators
import openzaak.utils.fields
import uuid
import vng_api_common.fields
import vng_api_common.models
import vng_api_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalogus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_admin_name",
                    models.CharField(
                        help_text="Naam voor interne doeleinden. Dit attribuut wordt niet ontsloten via de API.",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "domein",
                    models.CharField(
                        help_text="Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt.",
                        max_length=5,
                        validators=[
                            openzaak.components.catalogi.models.validators.validate_uppercase
                        ],
                        verbose_name="domein",
                    ),
                ),
                (
                    "rsin",
                    vng_api_common.fields.RSINField(
                        db_index=True,
                        help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS.",
                        max_length=9,
                        verbose_name="rsin",
                    ),
                ),
                (
                    "contactpersoon_beheer_naam",
                    models.CharField(
                        help_text="De naam van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.",
                        max_length=40,
                        verbose_name="naam",
                    ),
                ),
                (
                    "contactpersoon_beheer_telefoonnummer",
                    models.CharField(
                        blank=True,
                        help_text="Het telefoonnummer van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.",
                        max_length=20,
                        verbose_name="telefoonnummer",
                    ),
                ),
                (
                    "contactpersoon_beheer_emailadres",
                    models.EmailField(
                        blank=True,
                        help_text="Het emailadres van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.",
                        max_length=254,
                        verbose_name="emailadres",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalogus",
                "verbose_name_plural": "catalogi",
                "unique_together": {("domein", "rsin")},
            },
        ),
        migrations.CreateModel(
            name="EigenschapSpecificatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groep",
                    models.CharField(
                        blank=True,
                        help_text="Benaming van het object of groepattribuut waarvan de EIGENSCHAP een inhoudelijk gegeven specificeert.",
                        max_length=32,
                        validators=[
                            openzaak.components.catalogi.models.validators.validate_letters_numbers_underscores
                        ],
                        verbose_name="groep",
                    ),
                ),
                (
                    "formaat",
                    models.CharField(
                        choices=[
                            ("tekst", "Tekst"),
                            ("getal", "Getal"),
                            ("datum", "Datum"),
                            ("datum_tijd", "Datum/tijd"),
                        ],
                        help_text="Het soort tekens waarmee waarden van de EIGENSCHAP kunnen worden vastgelegd.",
                        max_length=20,
                        verbose_name="formaat",
                    ),
                ),
                (
                    "lengte",
                    models.CharField(
                        help_text="Het aantal karakters (lengte) waarmee waarden van de EIGENSCHAP worden vastgelegd.",
                        max_length=14,
                        verbose_name="lengte",
                    ),
                ),
                (
                    "kardinaliteit",
                    models.CharField(
                        help_text="Het aantal mogelijke voorkomens van waarden van deze EIGENSCHAP bij een zaak van het ZAAKTYPE.",
                        max_length=3,
                        validators=[
                            openzaak.components.catalogi.models.validators.KardinaliteitValidator()
                        ],
                        verbose_name="kardinaliteit",
                    ),
                ),
                (
                    "waardenverzameling",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=100, verbose_name="waardenverzameling"
                        ),
                        blank=True,
                        help_text="Waarden die deze EIGENSCHAP kan hebben.",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigenschap specificatie",
                "verbose_name_plural": "Eigenschap specificaties",
            },
        ),
        migrations.CreateModel(
            name="InformatieObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum_begin_geldigheid",
                    models.DateField(
                        help_text="De datum waarop het is ontstaan.",
                        verbose_name="datum begin geldigheid",
                    ),
                ),
                (
                    "datum_einde_geldigheid",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop het is opgeheven.",
                        null=True,
                        verbose_name="datum einde geldigheid",
                    ),
                ),
                (
                    "concept",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                        verbose_name="concept",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.",
                        max_length=80,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Aanduiding van de mate waarin informatieobjecten van dit INFORMATIEOBJECTTYPE voor de openbaarheid bestemd zijn.",
                        max_length=20,
                        verbose_name="vertrouwelijkheidaanduiding",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="URL-referentie naar de CATALOGUS waartoe dit INFORMATIEOBJECTTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.Catalogus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informatieobjecttype",
                "verbose_name_plural": "Informatieobjecttypen",
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StatusType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "statustype_omschrijving",
                    models.CharField(
                        help_text="Een korte, voor de initiator van de zaak relevante, omschrijving van de aard van de STATUS van zaken van een ZAAKTYPE.",
                        max_length=80,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "statustype_omschrijving_generiek",
                    models.CharField(
                        blank=True,
                        help_text="Algemeen gehanteerde omschrijving van de aard van STATUSsen van het STATUSTYPE",
                        max_length=80,
                        verbose_name="omschrijving generiek",
                    ),
                ),
                (
                    "statustypevolgnummer",
                    models.PositiveSmallIntegerField(
                        help_text="Een volgnummer voor statussen van het STATUSTYPE binnen een zaak.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="statustypevolgnummer",
                    ),
                ),
                (
                    "informeren",
                    models.BooleanField(
                        default=False,
                        help_text="Aanduiding die aangeeft of na het zetten van een STATUS van dit STATUSTYPE de Initiator moet worden geïnformeerd over de statusovergang.",
                        verbose_name="informeren",
                    ),
                ),
                (
                    "statustekst",
                    models.CharField(
                        blank=True,
                        help_text="De tekst die wordt gebruikt om de Initiator te informeren over het bereiken van een STATUS van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.",
                        max_length=1000,
                        verbose_name="statustekst",
                    ),
                ),
                (
                    "toelichting",
                    models.CharField(
                        blank=True,
                        help_text="Een eventuele toelichting op dit STATUSTYPE.",
                        max_length=1000,
                        null=True,
                        verbose_name="toelichting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statustype",
                "verbose_name_plural": "Statustypen",
                "ordering": ("zaaktype", "-statustypevolgnummer"),
            },
        ),
        migrations.CreateModel(
            name="ZaakType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum_begin_geldigheid",
                    models.DateField(
                        help_text="De datum waarop het is ontstaan.",
                        verbose_name="datum begin geldigheid",
                    ),
                ),
                (
                    "datum_einde_geldigheid",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop het is opgeheven.",
                        null=True,
                        verbose_name="datum einde geldigheid",
                    ),
                ),
                (
                    "concept",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                        verbose_name="concept",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.",
                        max_length=50,
                        validators=[
                            vng_api_common.validators.AlphanumericExcludingDiacritic()
                        ],
                        verbose_name="identificatie",
                    ),
                ),
                (
                    "zaaktype_omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de aard van ZAAKen van het ZAAKTYPE.",
                        max_length=80,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "zaaktype_omschrijving_generiek",
                    models.CharField(
                        blank=True,
                        help_text="Algemeen gehanteerde omschrijving van de aard van ZAAKen van het ZAAKTYPE",
                        max_length=80,
                        verbose_name="omschrijving generiek",
                    ),
                ),
                (
                    "vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Aanduiding van de mate waarin zaakdossiers van ZAAKen van dit ZAAKTYPE voor de openbaarheid bestemd zijn. Indien de zaak bij het aanmaken geen vertrouwelijkheidaanduiding krijgt, dan wordt deze waarde gezet.",
                        max_length=20,
                        verbose_name="vertrouwelijkheidaanduiding",
                    ),
                ),
                (
                    "doel",
                    models.TextField(
                        help_text="Een omschrijving van hetgeen beoogd is te bereiken met een zaak van dit zaaktype.",
                        verbose_name="doel",
                    ),
                ),
                (
                    "aanleiding",
                    models.TextField(
                        help_text="Een omschrijving van de gebeurtenis die leidt tot het starten van een ZAAK van dit ZAAKTYPE.",
                        verbose_name="aanleiding",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een eventuele toelichting op dit zaaktype, zoals een beschrijving van het procesverloop op de hoofdlijnen.",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "indicatie_intern_of_extern",
                    models.CharField(
                        choices=[("intern", "Intern"), ("extern", "Extern")],
                        help_text="Een aanduiding waarmee onderscheid wordt gemaakt tussen ZAAKTYPEn die Intern respectievelijk Extern geïnitieerd worden. Indien van beide sprake kan zijn, dan prevaleert de externe initiatie.",
                        max_length=6,
                        verbose_name="indicatie intern of extern",
                    ),
                ),
                (
                    "handeling_initiator",
                    models.CharField(
                        help_text="Werkwoord dat hoort bij de handeling die de initiator verricht bij dit zaaktype. Meestal 'aanvragen', 'indienen' of 'melden'. Zie ook het IOB model op https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.handeling_initiator",
                        max_length=20,
                        verbose_name="handeling initiator",
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        help_text="Het onderwerp van ZAAKen van dit ZAAKTYPE. In veel gevallen nauw gerelateerd aan de product- of dienstnaam uit de Producten- en Dienstencatalogus (PDC). Bijvoorbeeld: 'Evenementenvergunning', 'Geboorte', 'Klacht'. Zie ook het IOB model op https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.onderwerp",
                        max_length=80,
                        verbose_name="onderwerp",
                    ),
                ),
                (
                    "handeling_behandelaar",
                    models.CharField(
                        help_text="Werkwoord dat hoort bij de handeling die de behandelaar verricht bij het afdoen van ZAAKen van dit ZAAKTYPE. Meestal 'behandelen', 'uitvoeren', 'vaststellen' of 'onderhouden'. Zie ook het IOB model op https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.handeling_behandelaar",
                        max_length=20,
                        verbose_name="handeling behandelaar",
                    ),
                ),
                (
                    "doorlooptijd_behandeling",
                    openzaak.utils.fields.DurationField(
                        help_text="De periode waarbinnen volgens wet- en regelgeving een ZAAK van het ZAAKTYPE afgerond dient te zijn, in kalenderdagen.",
                        verbose_name="doorlooptijd behandeling",
                    ),
                ),
                (
                    "servicenorm_behandeling",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De periode waarbinnen verwacht wordt dat een ZAAK van het ZAAKTYPE afgerond wordt conform de geldende servicenormen van de zaakbehandelende organisatie(s).",
                        null=True,
                        verbose_name="servicenorm behandeling",
                    ),
                ),
                (
                    "opschorting_en_aanhouding_mogelijk",
                    models.BooleanField(
                        help_text="Aanduiding die aangeeft of ZAAKen van dit mogelijk ZAAKTYPE kunnen worden opgeschort en/of aangehouden.",
                        verbose_name="opschorting/aanhouding mogelijk",
                    ),
                ),
                (
                    "verlenging_mogelijk",
                    models.BooleanField(
                        help_text="Aanduiding die aangeeft of de Doorlooptijd behandeling van ZAAKen van dit ZAAKTYPE kan worden verlengd.",
                        verbose_name="verlenging mogelijk",
                    ),
                ),
                (
                    "verlengingstermijn",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De termijn (typisch een aantal dagen) waarmee de Doorlooptijd behandeling van ZAAKen van dit ZAAKTYPE kan worden verlengd. Mag alleen een waarde bevatten als verlenging mogelijk is.",
                        null=True,
                        verbose_name="verlengingstermijn",
                    ),
                ),
                (
                    "trefwoorden",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=30, verbose_name="trefwoord"
                        ),
                        blank=True,
                        db_index=True,
                        default=list,
                        help_text="Een trefwoord waarmee ZAAKen van het ZAAKTYPE kunnen worden gekarakteriseerd.",
                        size=None,
                    ),
                ),
                (
                    "publicatie_indicatie",
                    models.BooleanField(
                        help_text="Aanduiding of (het starten van) een ZAAK dit ZAAKTYPE gepubliceerd moet worden.",
                        verbose_name="publicatie indicatie",
                    ),
                ),
                (
                    "publicatietekst",
                    models.TextField(
                        blank=True,
                        help_text="De generieke tekst van de publicatie van ZAAKen van dit ZAAKTYPE.",
                        verbose_name="publicatietekst",
                    ),
                ),
                (
                    "verantwoordingsrelatie",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=40, verbose_name="verantwoordingsrelatie"
                        ),
                        blank=True,
                        default=list,
                        help_text="De relatie tussen ZAAKen van dit ZAAKTYPE en de beleidsmatige en/of financiële verantwoording.",
                        size=None,
                    ),
                ),
                (
                    "versiedatum",
                    models.DateField(
                        help_text="De datum waarop de (gewijzigde) kenmerken van het ZAAKTYPE geldig zijn geworden",
                        verbose_name="versiedatum",
                    ),
                ),
                (
                    "producten_of_diensten",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="URL naar product/dienst"
                        ),
                        help_text="Het product of de dienst die door ZAAKen van dit ZAAKTYPE wordt voortgebracht.",
                        size=None,
                    ),
                ),
                (
                    "selectielijst_procestype",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar een vanuit archiveringsoptiek onderkende groep processen met dezelfde kenmerken (PROCESTYPE in de Selectielijst API).",
                        verbose_name="selectielijst procestype",
                    ),
                ),
                (
                    "referentieproces_naam",
                    models.CharField(
                        help_text="De naam van het Referentieproces.",
                        max_length=80,
                        verbose_name="referentieprocesnaam",
                    ),
                ),
                (
                    "referentieproces_link",
                    models.URLField(
                        blank=True,
                        help_text="De URL naar de beschrijving van het Referentieproces",
                        verbose_name="referentieproceslink",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="URL-referentie naar de CATALOGUS waartoe dit ZAAKTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.Catalogus",
                    ),
                ),
                (
                    "deelzaaktypen",
                    models.ManyToManyField(
                        blank=True,
                        help_text="De ZAAKTYPE(n) waaronder ZAAKen als deelzaak kunnen voorkomen bij ZAAKen van dit ZAAKTYPE.",
                        related_name="hoofdzaaktypen",
                        to="catalogi.ZaakType",
                    ),
                ),
            ],
            options={"verbose_name": "Zaaktype", "verbose_name_plural": "Zaaktypen",},
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ZaakTypeInformatieObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "volgnummer",
                    models.PositiveSmallIntegerField(
                        help_text="Uniek volgnummer van het ZAAK-INFORMATIEOBJECTTYPE binnen het ZAAKTYPE.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="volgnummer",
                    ),
                ),
                (
                    "richting",
                    models.CharField(
                        choices=[
                            ("inkomend", "Inkomend"),
                            ("intern", "Intern"),
                            ("uitgaand", "Uitgaand"),
                        ],
                        db_index=True,
                        help_text="Aanduiding van de richting van informatieobjecten van het gerelateerde INFORMATIEOBJECTTYPE bij zaken van het gerelateerde ZAAKTYPE.",
                        max_length=20,
                        verbose_name="richting",
                    ),
                ),
                (
                    "informatieobjecttype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het INFORMATIEOBJECTTYPE.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.InformatieObjectType",
                        verbose_name="informatie object type",
                    ),
                ),
                (
                    "statustype",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL-referentie naar het STATUSTYPE waarbij deze INFORMATIEOBJECTTYPEn verplicht aanwezig moeten zijn.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heeft_verplichte_zit",
                        to="catalogi.StatusType",
                        verbose_name="status type",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het ZAAKTYPE.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.ZaakType",
                        verbose_name="zaaktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaak-Informatieobject-Type",
                "verbose_name_plural": "Zaak-Informatieobject-Typen",
                "unique_together": {("zaaktype", "volgnummer")},
            },
        ),
        migrations.AddField(
            model_name="statustype",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE van ZAAKen waarin STATUSsen van dit STATUSTYPE bereikt kunnen worden.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statustypen",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="zaaktypen",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit INFORMATIEOBJECTTYPE",
                related_name="informatieobjecttypen",
                through="catalogi.ZaakTypeInformatieObjectType",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.CreateModel(
            name="ZaakTypenRelatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gerelateerd_zaaktype",
                    models.URLField(
                        help_text="URL referentie naar het gerelateerde zaaktype, mogelijks in een extern ZTC.",
                        verbose_name="gerelateerd zaaktype",
                    ),
                ),
                (
                    "aard_relatie",
                    models.CharField(
                        choices=[
                            ("vervolg", "Vervolg"),
                            ("bijdrage", "Bijdrage"),
                            ("onderwerp", "Onderwerp"),
                        ],
                        help_text="Omschrijving van de aard van de relatie van zaken van het ZAAKTYPE tot zaken van het andere ZAAKTYPE",
                        max_length=15,
                        verbose_name="aard relatie",
                    ),
                ),
                (
                    "toelichting",
                    models.CharField(
                        blank=True,
                        help_text="Een toelichting op de aard van de relatie tussen beide ZAAKTYPEN.",
                        max_length=255,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaaktypenrelaties",
                        to="catalogi.ZaakType",
                        verbose_name="zaaktype van",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaaktypenrelatie",
                "verbose_name_plural": "Zaaktypenrelaties",
                "unique_together": {("zaaktype", "gerelateerd_zaaktype")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="statustype", unique_together={("zaaktype", "statustypevolgnummer")},
        ),
        migrations.CreateModel(
            name="RolType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de aard van de ROL.",
                        max_length=100,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "omschrijving_generiek",
                    models.CharField(
                        choices=[
                            ("adviseur", "Adviseur"),
                            ("behandelaar", "Behandelaar"),
                            ("belanghebbende", "Belanghebbende"),
                            ("beslisser", "Beslisser"),
                            ("initiator", "Initiator"),
                            ("klantcontacter", "Klantcontacter"),
                            ("zaakcoordinator", "Zaakcoördinator"),
                            ("mede_initiator", "Mede-initiator"),
                        ],
                        db_index=True,
                        help_text="Algemeen gehanteerde omschrijving van de aard van de ROL.",
                        max_length=20,
                        verbose_name="omschrijving generiek",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het ZAAKTYPE waar deze ROLTYPEn betrokken kunnen zijn.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.ZaakType",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roltype",
                "verbose_name_plural": "Roltypen",
                "unique_together": {("zaaktype", "omschrijving")},
            },
        ),
        migrations.CreateModel(
            name="ResultaatType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de aard van resultaten van het RESULTAATTYPE.",
                        max_length=20,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "resultaattypeomschrijving",
                    models.URLField(
                        help_text="Algemeen gehanteerde omschrijving van de aard van resultaten van het RESULTAATTYPE. Dit moet een URL-referentie zijn naar de referenlijst van generieke resultaattypeomschrijvingen. Im ImZTC heet dit 'omschrijving generiek'",
                        max_length=1000,
                        verbose_name="resultaattypeomschrijving",
                    ),
                ),
                (
                    "omschrijving_generiek",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Gecachete tekstuele waarde van de generieke resultaattypeomschrijving.",
                        max_length=20,
                        verbose_name="omschrijving generiek",
                    ),
                ),
                (
                    "selectielijstklasse",
                    models.URLField(
                        help_text="URL-referentie naar de, voor het archiefregime bij het RESULTAATTYPE relevante, categorie in de Selectielijst Archiefbescheiden (RESULTAAT in de Selectielijst API) van de voor het ZAAKTYPE verantwoordelijke overheidsorganisatie.",
                        max_length=1000,
                        verbose_name="selectielijstklasse",
                    ),
                ),
                (
                    "archiefnominatie",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "blijvend_bewaren",
                                "Het zaakdossier moet bewaard blijven en op de Archiefactiedatum overgedragen worden naar een archiefbewaarplaats.",
                            ),
                            (
                                "vernietigen",
                                "Het zaakdossier moet op of na de Archiefactiedatum vernietigd worden.",
                            ),
                        ],
                        default="",
                        help_text="Aanduiding die aangeeft of ZAAKen met een resultaat van dit RESULTAATTYPE blijvend moeten worden bewaard of (op termijn) moeten worden vernietigd. Indien niet expliciet opgegeven wordt dit gevuld vanuit de selectielijst.",
                        max_length=20,
                        verbose_name="archiefnominatie",
                    ),
                ),
                (
                    "archiefactietermijn",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De termijn, na het vervallen van het bedrjfsvoeringsbelang, waarna het zaakdossier (de ZAAK met alle bijbehorende INFORMATIEOBJECTen) van een ZAAK met een resultaat van dit RESULTAATTYPE vernietigd of overgebracht (naar een archiefbewaarplaats) moet worden. Voor te vernietigen dossiers betreft het de in die Selectielijst genoemde bewaartermjn. Voor blijvend te bewaren zaakdossiers betreft het de termijn vanaf afronding van de zaak tot overbrenging (de procestermijn is dan nihil).",
                        null=True,
                        verbose_name="archiefactietermijn",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_afleidingswijze",
                    models.CharField(
                        choices=[
                            ("afgehandeld", "Afgehandeld"),
                            ("ander_datumkenmerk", "Ander datumkenmerk"),
                            ("eigenschap", "Eigenschap"),
                            ("gerelateerde_zaak", "Gerelateerde zaak"),
                            ("hoofdzaak", "Hoofdzaak"),
                            ("ingangsdatum_besluit", "Ingangsdatum besluit"),
                            ("termijn", "Termijn"),
                            ("vervaldatum_besluit", "Vervaldatum besluit"),
                            ("zaakobject", "Zaakobject"),
                        ],
                        help_text="Wijze van bepalen van de brondatum.",
                        max_length=20,
                        verbose_name="afleidingswijze brondatum",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_datumkenmerk",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de attribuutsoort van het procesobject dat bepalend is voor het einde van de procestermijn.",
                        max_length=80,
                        verbose_name="datumkenmerk",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_einddatum_bekend",
                    models.BooleanField(
                        default=False,
                        help_text="Indicatie dat de einddatum van het procesobject gedurende de uitvoering van de zaak bekend moet worden. Indien deze nog niet bekend is en deze waarde staat op `true`, dan kan de zaak (nog) niet afgesloten worden.",
                        verbose_name="einddatum bekend",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_objecttype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("adres", "Adres"),
                            ("besluit", "Besluit"),
                            ("buurt", "Buurt"),
                            ("enkelvoudig_document", "Enkelvoudig document"),
                            ("gemeente", "Gemeente"),
                            (
                                "gemeentelijke_openbare_ruimte",
                                "Gemeentelijke openbare ruimte",
                            ),
                            ("huishouden", "Huishouden"),
                            ("inrichtingselement", "Inrichtingselement"),
                            (
                                "kadastrale_onroerende_zaak",
                                "Kadastrale onroerende zaak",
                            ),
                            ("kunstwerkdeel", "Kunstwerkdeel"),
                            (
                                "maatschappelijke_activiteit",
                                "Maatschappelijke activiteit",
                            ),
                            ("medewerker", "Medewerker"),
                            ("natuurlijk_persoon", "Natuurlijk persoon"),
                            ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                            ("openbare_ruimte", "Openbare ruimte"),
                            ("organisatorische_eenheid", "Organisatorische eenheid"),
                            ("pand", "Pand"),
                            ("spoorbaandeel", "Spoorbaandeel"),
                            ("status", "Status"),
                            ("terreindeel", "Terreindeel"),
                            ("terrein_gebouwd_object", "Terrein gebouwd object"),
                            ("vestiging", "Vestiging"),
                            ("waterdeel", "Waterdeel"),
                            ("wegdeel", "Wegdeel"),
                            ("wijk", "Wijk"),
                            ("woonplaats", "Woonplaats"),
                            ("woz_deelobject", "Woz deel object"),
                            ("woz_object", "Woz object"),
                            ("woz_waarde", "Woz waarde"),
                            ("zakelijk_recht", "Zakelijk recht"),
                            ("overige", "Overige"),
                        ],
                        help_text="Het soort object in de registratie dat het procesobject representeert.",
                        max_length=80,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_registratie",
                    models.CharField(
                        blank=True,
                        help_text="De naam van de registratie waarvan het procesobject deel uit maakt.",
                        max_length=80,
                        verbose_name="registratie",
                    ),
                ),
                (
                    "brondatum_archiefprocedure_procestermijn",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is.",
                        null=True,
                        verbose_name="procestermijn",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een toelichting op dit RESULTAATTYPE en het belang hiervan voor ZAAKen waarin een resultaat van dit RESULTAATTYPE wordt geselecteerd.",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het ZAAKTYPE van ZAAKen waarin resultaten van dit RESULTAATTYPE bereikt kunnen worden.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultaattypen",
                        to="catalogi.ZaakType",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultaattype",
                "verbose_name_plural": "resultaattypen",
                "unique_together": {("zaaktype", "omschrijving")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="informatieobjecttype",
            unique_together={("catalogus", "omschrijving")},
        ),
        migrations.CreateModel(
            name="Eigenschap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "eigenschapnaam",
                    models.CharField(
                        help_text="De naam van de EIGENSCHAP",
                        max_length=20,
                        verbose_name="eigenschapnaam",
                    ),
                ),
                (
                    "definitie",
                    models.CharField(
                        help_text="De beschrijving van de betekenis van deze EIGENSCHAP",
                        max_length=255,
                        verbose_name="definitie",
                    ),
                ),
                (
                    "toelichting",
                    models.CharField(
                        blank=True,
                        help_text="Een toelichting op deze EIGENSCHAP en het belang hiervan voor zaken van dit ZAAKTYPE.",
                        max_length=1000,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "specificatie_van_eigenschap",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attribuutkenmerken van de eigenschap",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.EigenschapSpecificatie",
                        verbose_name="specificatie van eigenschap",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het ZAAKTYPE van de ZAAKen waarvoor deze EIGENSCHAP van belang is.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.ZaakType",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigenschap",
                "verbose_name_plural": "Eigenschappen",
                "unique_together": {("zaaktype", "eigenschapnaam")},
            },
        ),
        migrations.CreateModel(
            name="BesluitType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum_begin_geldigheid",
                    models.DateField(
                        help_text="De datum waarop het is ontstaan.",
                        verbose_name="datum begin geldigheid",
                    ),
                ),
                (
                    "datum_einde_geldigheid",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop het is opgeheven.",
                        null=True,
                        verbose_name="datum einde geldigheid",
                    ),
                ),
                (
                    "concept",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                        verbose_name="concept",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de aard van BESLUITen van het BESLUITTYPE.",
                        max_length=80,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "omschrijving_generiek",
                    models.CharField(
                        blank=True,
                        help_text="Algemeen gehanteerde omschrijving van de aard van BESLUITen van het BESLUITTYPE",
                        max_length=80,
                        verbose_name="omschrijving generiek",
                    ),
                ),
                (
                    "besluitcategorie",
                    models.CharField(
                        blank=True,
                        help_text="Typering van de aard van BESLUITen van het BESLUITTYPE.",
                        max_length=40,
                        verbose_name="besluitcategorie",
                    ),
                ),
                (
                    "reactietermijn",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De duur (typisch een aantal dagen), gerekend vanaf de verzend- of publicatiedatum, waarbinnen verweer tegen een besluit van het besluittype mogelijk is.",
                        null=True,
                        verbose_name="reactietermijn",
                    ),
                ),
                (
                    "publicatie_indicatie",
                    models.BooleanField(
                        help_text="Aanduiding of BESLUITen van dit BESLUITTYPE gepubliceerd moeten worden.",
                        verbose_name="publicatie indicatie",
                    ),
                ),
                (
                    "publicatietekst",
                    models.TextField(
                        blank=True,
                        help_text="De generieke tekst van de publicatie van BESLUITen van dit BESLUITTYPE",
                        verbose_name="publicatietekst",
                    ),
                ),
                (
                    "publicatietermijn",
                    openzaak.utils.fields.DurationField(
                        blank=True,
                        help_text="De duur (typisch een aantal dagen), gerekend vanaf de verzend- of publicatiedatum, dat BESLUITen van dit BESLUITTYPE gepubliceerd moeten blijven.",
                        null=True,
                        verbose_name="publicatietermijn",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Een eventuele toelichting op dit BESLUITTYPE.",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="URL-referentie naar de CATALOGUS waartoe dit BESLUITTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.Catalogus",
                    ),
                ),
                (
                    "informatieobjecttypen",
                    models.ManyToManyField(
                        blank=True,
                        help_text="URL-referenties naar het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.",
                        related_name="besluittypen",
                        to="catalogi.InformatieObjectType",
                    ),
                ),
                (
                    "zaaktypen",
                    models.ManyToManyField(
                        help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE",
                        related_name="besluittypen",
                        to="catalogi.ZaakType",
                    ),
                ),
            ],
            options={
                "verbose_name": "besluittype",
                "verbose_name_plural": "besluittypen",
                "unique_together": {("catalogus", "omschrijving")},
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
