# Generated by Django 2.2.4 on 2019-09-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("catalogi", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="catalogus",
            options={
                "verbose_name": "catalogus",
                "verbose_name_plural": "catalogussen",
            },
        ),
        migrations.AlterModelOptions(
            name="eigenschap",
            options={
                "verbose_name": "Eigenschap",
                "verbose_name_plural": "Eigenschappen",
            },
        ),
        migrations.AlterModelOptions(
            name="statustype",
            options={
                "verbose_name": "Statustype",
                "verbose_name_plural": "Statustypen",
            },
        ),
        migrations.AlterModelOptions(
            name="zaakinformatieobjecttype",
            options={
                "verbose_name": "Zaak-Informatieobject-Type",
                "verbose_name_plural": "Zaak-Informatieobject-Typen",
            },
        ),
        migrations.AlterModelOptions(
            name="zaakinformatieobjecttypearchiefregime",
            options={
                "verbose_name": "Zaak-Informatieobject-Type Archiefregime",
                "verbose_name_plural": "Zaak-Informatieobject-Type Archiefregimes",
            },
        ),
        migrations.AlterModelOptions(
            name="zaakobjecttype",
            options={
                "verbose_name": "Zaakobjecttype",
                "verbose_name_plural": "Zaakobjecttypen",
            },
        ),
        migrations.AlterModelOptions(
            name="zaaktype",
            options={"verbose_name": "Zaaktype", "verbose_name_plural": "Zaaktypen"},
        ),
        migrations.AlterModelOptions(
            name="zaaktypenrelatie",
            options={
                "verbose_name": "Zaaktypenrelatie",
                "verbose_name_plural": "Zaaktypenrelaties",
            },
        ),
    ]
