# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.9 on 2020-01-31 11:47
from dataclasses import dataclass

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace

OLD = "https://referentielijsten-api.vng.cloud/api/v1/"
NEW = "https://selectielijst.openzaak.nl/api/v1/"


@dataclass
class _Replace:
    current: str
    new: str

    def __call__(self, apps, _):
        ZaakType = apps.get_model("catalogi", "ZaakType")
        ResultaatType = apps.get_model("catalogi", "ResultaatType")

        zaaktypen = ZaakType.objects.filter(
            selectielijst_procestype__startswith=self.current
        )
        zaaktypen.update(
            selectielijst_procestype=Replace(
                "selectielijst_procestype", Value(self.current), Value(self.new)
            )
        )

        resultaattypen = ResultaatType.objects.filter(
            selectielijstklasse__startswith=self.current
        )
        resultaattypen.update(
            selectielijstklasse=Replace(
                "selectielijstklasse", Value(self.current), Value(self.new),
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_Replace(OLD, NEW), _Replace(NEW, OLD)),
    ]
