# Generated by Django 2.2.4 on 2019-09-18 08:59

import django.core.validators
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [("catalogi", "0002_auto_20190911_1520")]

    operations = [
        migrations.AlterField(
            model_name="besluittype",
            name="concept",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                verbose_name="concept",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="rsin",
            field=vng_api_common.fields.RSINField(
                db_index=True,
                help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS.",
                max_length=9,
                verbose_name="rsin",
            ),
        ),
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="concept",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                verbose_name="concept",
            ),
        ),
        migrations.AlterField(
            model_name="roltype",
            name="omschrijving_generiek",
            field=models.CharField(
                choices=[
                    ("adviseur", "Adviseur"),
                    ("behandelaar", "Behandelaar"),
                    ("belanghebbende", "Belanghebbende"),
                    ("beslisser", "Beslisser"),
                    ("initiator", "Initiator"),
                    ("klantcontacter", "Klantcontacter"),
                    ("zaakcoordinator", "Zaakcoördinator"),
                    ("mede_initiator", "Mede-initiator"),
                ],
                db_index=True,
                help_text="Algemeen gehanteerde omschrijving van de aard van de ROL.",
                max_length=20,
                verbose_name="omschrijving generiek",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobjecttype",
            name="richting",
            field=models.CharField(
                choices=[
                    ("inkomend", "Inkomend"),
                    ("intern", "Intern"),
                    ("uitgaand", "Uitgaand"),
                ],
                db_index=True,
                help_text="Aanduiding van de richting van informatieobjecten van het gerelateerde INFORMATIEOBJECTTYPE bij zaken van het gerelateerde ZAAKTYPE.",
                max_length=20,
                verbose_name="richting",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="concept",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API.",
                verbose_name="concept",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="trefwoorden",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=30, verbose_name="trefwoord"),
                blank=True,
                db_index=True,
                default=list,
                help_text="Een trefwoord waarmee ZAAKen van het ZAAKTYPE kunnen worden gekarakteriseerd.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="zaaktype_identificatie",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.",
                validators=[django.core.validators.MaxValueValidator(99999)],
                verbose_name="identificatie",
            ),
        ),
    ]
