# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2020 Dimpact
# Generated by Django 2.2.10 on 2020-06-05 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0003_auto_20200527_0759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschapspecificatie",
            name="waardenverzameling",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=100, verbose_name="waardenverzameling"
                ),
                blank=True,
                default=list,
                help_text="Waarden die deze EIGENSCHAP kan hebben.",
                size=None,
            ),
        ),
    ]
