# Generated by Django 2.2.4 on 2019-09-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0003_auto_20190912_0837"),
        ("catalogi", "0003_auto_20190918_0859"),
    ]

    operations = []
