# Generated by Django 2.2.4 on 2019-10-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogi', '0004_merge_20190919_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='besluittype',
            old_name='informatieobjecttypes',
            new_name='informatieobjecttypen',
        ),
    ]
