# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.10 on 2020-08-17 10:37

from django.db import migrations


def set_selectieklasse_procestype_default_year(apps, _):
    ZaakType = apps.get_model("catalogi.ZaakType")

    for zaaktype in ZaakType.objects.all():
        zaaktype.selectieklasse_procestype_jaar = 2017
        zaaktype.save()


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0005_zaaktype_selectielijst_procestype_jaar"),
    ]

    operations = [
        migrations.RunPython(
            set_selectieklasse_procestype_default_year, migrations.RunPython.noop
        )
    ]
