# Generated by Django 2.2.4 on 2019-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogi', '0005_auto_20191024_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluittype',
            name='informatieobjecttypen',
            field=models.ManyToManyField(blank=True, help_text='URL-referenties naar het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.', related_name='besluittypen', to='catalogi.InformatieObjectType', verbose_name='informatieobjecttype'),
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='zaaktypes',
            field=models.ManyToManyField(help_text='ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE', related_name='besluittypen', to='catalogi.ZaakType', verbose_name='zaaktypes'),
        ),
        migrations.AlterField(
            model_name='informatieobjecttype',
            name='zaaktypes',
            field=models.ManyToManyField(help_text='ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit INFORMATIEOBJECTTYPE', related_name='informatieobjecttypen', through='catalogi.ZaakInformatieobjectType', to='catalogi.ZaakType', verbose_name='zaaktypes'),
        ),
    ]
