# Generated by Django 2.2.4 on 2019-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0006_auto_20191024_1000"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statustype",
            options={
                "ordering": ("zaaktype", "-statustypevolgnummer"),
                "verbose_name": "Statustype",
                "verbose_name_plural": "Statustypen",
            },
        ),
    ]
