# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2019 - 2020 Dimpact
# Generated by Django 2.2.10 on 2020-08-28 14:23

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0006_auto_20200817_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschapspecificatie",
            name="waardenverzameling",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    max_length=100, verbose_name="waardenverzameling"
                ),
                blank=True,
                default=list,
                help_text="Waarden die deze EIGENSCHAP kan hebben.",
                size=None,
            ),
        ),
    ]
