# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.10 on 2021-02-03 09:47

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0007_auto_20200828_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="producten_of_diensten",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="URL naar product/dienst"
                ),
                blank=True,
                default=list,
                help_text="Het product of de dienst die door ZAAKen van dit ZAAKTYPE wordt voortgebracht.",
                size=None,
            ),
        ),
    ]
