# Generated by Django 2.2.4 on 2019-11-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0007_auto_20191112_0920"),
        ("catalogi", "0008_auto_20191112_1111"),
    ]

    operations = []
