# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.17 on 2021-02-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0008_auto_20210203_0947"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="informatieobjecttype",
            unique_together=set(),
        ),
    ]
