# Generated by Django 2.2.4 on 2019-11-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0009_merge_20191120_0931"),
        ("catalogi", "0007_auto_20191119_1136"),
    ]

    operations = []
