# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.24 on 2021-06-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0009_auto_20210224_1144"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="besluittype", unique_together=set(),),
    ]
