# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.12 on 2022-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0010_auto_20210628_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluittype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogus",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eigenschap",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roltype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statustype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaaktypeinformatieobjecttype",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        ),
    ]
