# Generated by Django 2.2.4 on 2019-11-21 16:00

from django.db import migrations

import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0010_merge_20191120_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="doorlooptijd_behandeling",
            field=openzaak.utils.fields.DurationField(
                help_text="De periode waarbinnen volgens wet- en regelgeving een ZAAK van het ZAAKTYPE afgerond dient te zijn, in kalenderdagen.",
                verbose_name="doorlooptijd behandeling",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="servicenorm_behandeling",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De periode waarbinnen verwacht wordt dat een ZAAK van het ZAAKTYPE afgerond wordt conform de geldende servicenormen van de zaakbehandelende organisatie(s).",
                null=True,
                verbose_name="servicenorm behandeling",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="verlengingstermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De termijn (typisch een aantal dagen) waarmee de Doorlooptijd behandeling van ZAAKen van dit ZAAKTYPE kan worden verlengd. Mag alleen een waarde bevatten als verlenging mogelijk is.",
                null=True,
                verbose_name="verlengingstermijn",
            ),
        ),
    ]
