# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-05-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0011_auto_20220329_0921"),
        ("catalogi", "0011_auto_20220531_1017"),
    ]

    operations = []
