# Generated by Django 2.2.4 on 2019-11-22 14:14

from django.db import migrations

import openzaak.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0011_auto_20191121_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="besluittype",
            name="publicatietermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De duur (typisch een aantal dagen), gerekend vanaf de verzend- of publicatiedatum, dat BESLUITen van dit BESLUITTYPE gepubliceerd moeten blijven.",
                null=True,
                verbose_name="publicatietermijn",
            ),
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="reactietermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De duur (typisch een aantal dagen), gerekend vanaf de verzend- of publicatiedatum, waarbinnen verweer tegen een besluit van het besluittype mogelijk is.",
                null=True,
                verbose_name="reactietermijn",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="archiefactietermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De termijn, na het vervallen van het bedrjfsvoeringsbelang, waarna het zaakdossier (de ZAAK met alle bijbehorende INFORMATIEOBJECTen) van een ZAAK met een resultaat van dit RESULTAATTYPE vernietigd of overgebracht (naar een archiefbewaarplaats) moet worden. Voor te vernietigen dossiers betreft het de in die Selectielijst genoemde bewaartermjn. Voor blijvend te bewaren zaakdossiers betreft het de termijn vanaf afronding van de zaak tot overbrenging (de procestermijn is dan nihil).",
                null=True,
                verbose_name="archiefactietermijn",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_procestermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is.",
                null=True,
                verbose_name="procestermijn",
            ),
        ),
    ]
