# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-06-20 12:36

from django.db import migrations, models
import openzaak.components.catalogi.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0012_merge_0011_auto_20220329_0921_0011_auto_20220531_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschapspecificatie",
            name="groep",
            field=models.CharField(
                blank=True,
                help_text="Benaming van het object of groepattribuut waarvan de EIGENSCHAP een inhoudelijk gegeven specificeert.",
                max_length=32,
                validators=[
                    openzaak.components.catalogi.models.validators.validate_letters_numbers_underscores_spaces
                ],
                verbose_name="groep",
            ),
        ),
    ]
