# Generated by Django 2.2.4 on 2019-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0012_auto_20191122_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktype",
            name="deelzaaktypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="De ZAAKTYPE(n) waaronder ZAAKen als deelzaak kunnen voorkomen bij ZAAKen van dit ZAAKTYPE.",
                related_name="hoofdzaaktypen",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="roltype",
            name="omschrijving",
            field=models.CharField(
                help_text="Omschrijving van de aard van de ROL.",
                max_length=100,
                verbose_name="omschrijving",
            ),
        ),
    ]
