# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-06 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0013_alter_eigenschapspecificatie_groep"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_etag",
                    models.CharField(
                        editable=False,
                        help_text="MD5 hash of the resource representation in its current version.",
                        max_length=32,
                        verbose_name="etag value",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "ander_objecttype",
                    models.BooleanField(
                        help_text="Aanduiding waarmee wordt aangegeven of het ZAAKOBJECTTYPE een ander, niet in RSGB en RGBZ voorkomend, objecttype betreft.",
                        verbose_name="Ander objecttype",
                    ),
                ),
                (
                    "objecttype",
                    models.URLField(
                        help_text="URL-referentie naar de OBJECTTYPE waartoe dit ZAAKOBJECTTYPE behoort.",
                        verbose_name="Objecttype",
                    ),
                ),
                (
                    "relatie_omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de betrekking van het Objecttype op zaken van het gerelateerde ZAAKTYPE.",
                        max_length=80,
                        verbose_name="Relatie omschrijving",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAKTYPE waartoe dit ZAAKOBJECTTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.zaaktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaakobjecttype",
                "verbose_name_plural": "Zaakobjecttypen",
            },
        ),
    ]
