# Generated by Django 2.2.4 on 2019-11-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0013_auto_20191128_1032"),
        ("catalogi", "0013_auto_20191125_1107"),
    ]

    operations = []
