# Generated by Django 2.2.4 on 2019-11-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0013_auto_20191125_1107"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogus",
            options={"verbose_name": "catalogus", "verbose_name_plural": "catalogi"},
        ),
        migrations.AddField(
            model_name="catalogus",
            name="_admin_name",
            field=models.CharField(
                default="Catalogus",
                help_text="Naam voor interne doeleinden. Dit attribuut wordt niet ontsloten via de API.",
                max_length=100,
                verbose_name="naam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="catalogus",
            field=models.ForeignKey(
                help_text="URL-referentie naar de CATALOGUS waartoe dit BESLUITTYPE behoort.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.Catalogus",
            ),
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="informatieobjecttypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="URL-referenties naar het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.",
                related_name="besluittypen",
                to="catalogi.InformatieObjectType",
            ),
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="zaaktypen",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE",
                related_name="besluittypen",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="eigenschap",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE van de ZAAKen waarvoor deze EIGENSCHAP van belang is.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="catalogus",
            field=models.ForeignKey(
                help_text="URL-referentie naar de CATALOGUS waartoe dit INFORMATIEOBJECTTYPE behoort.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.Catalogus",
            ),
        ),
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="zaaktypen",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit INFORMATIEOBJECTTYPE",
                related_name="informatieobjecttypen",
                through="catalogi.ZaakInformatieobjectType",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE van ZAAKen waarin resultaten van dit RESULTAATTYPE bereikt kunnen worden.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultaattypen",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="roltype",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE waar deze ROLTYPEn betrokken kunnen zijn.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="statustype",
            name="zaaktype",
            field=models.ForeignKey(
                help_text="URL-referentie naar het ZAAKTYPE van ZAAKen waarin STATUSsen van dit STATUSTYPE bereikt kunnen worden.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statustypen",
                to="catalogi.ZaakType",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="catalogus",
            field=models.ForeignKey(
                help_text="URL-referentie naar de CATALOGUS waartoe dit ZAAKTYPE behoort.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogi.Catalogus",
            ),
        ),
    ]
