# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0014_zaakobjecttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultaattype",
            name="zaakobjecttypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="De ZAAKOBJECTTYPEn die verplicht gerelateerd moeten zijn aan ZAAKen van dit ZAAKTYPE voordat een resultaat van dit RESULTAATTYPE kan worden gezet.",
                related_name="resultaattypen",
                to="catalogi.ZaakObjectType",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="zaakobjecttype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ZAAKOBJECTTYPE.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statustypen",
                to="catalogi.zaakobjecttype",
            ),
        ),
    ]
