# Generated by Django 2.2.4 on 2019-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0015_auto_20191203_1307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_afleidingswijze",
            field=models.CharField(
                choices=[
                    ("afgehandeld", "Afgehandeld"),
                    ("ander_datumkenmerk", "Ander datumkenmerk"),
                    ("eigenschap", "Eigenschap"),
                    ("gerelateerde_zaak", "Gerelateerde zaak"),
                    ("hoofdzaak", "Hoofdzaak"),
                    ("ingangsdatum_besluit", "Ingangsdatum besluit"),
                    ("termijn", "Termijn"),
                    ("vervaldatum_besluit", "Vervaldatum besluit"),
                    ("zaakobject", "Zaakobject"),
                ],
                help_text="Wijze van bepalen van de brondatum.",
                max_length=20,
                verbose_name="afleidingswijze brondatum",
            ),
        ),
    ]
