# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0016_rename__admin_name_catalogus_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogus",
            name="begindatum_versie",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop de versie van de zaaktypecatalogus van toepassing is geworden.",
                null=True,
                verbose_name="begindatum versie",
            ),
        ),
        migrations.AddField(
            model_name="catalogus",
            name="versie",
            field=models.CharField(
                blank=True,
                help_text="Versie-aanduiding van de van toepassing zijnde zaaktypecatalogus.",
                max_length=20,
                verbose_name="versie",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De benaming die is gegeven aan de zaaktypecatalogus.",
                max_length=200,
                verbose_name="naam",
            ),
        ),
    ]
