# Generated by Django 2.2.9 on 2020-01-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0016_auto_20191204_1500"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zaaktypeinformatieobjecttypearchiefregime", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="zaaktypeinformatieobjecttypearchiefregime",
            name="resultaattype",
        ),
        migrations.RemoveField(
            model_name="zaaktypeinformatieobjecttypearchiefregime",
            name="zaak_informatieobject_type",
        ),
        migrations.DeleteModel(name="ZaakObjectType",),
        migrations.DeleteModel(name="ZaakTypeInformatieObjectTypeArchiefregime",),
    ]
