# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-19 12:25

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0016_rename__admin_name_catalogus_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogus",
            name="begindatum_versie",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop de versie van de zaaktypecatalogus van toepassing is geworden.",
                null=True,
                verbose_name="begindatum versie",
            ),
        ),
        migrations.AddField(
            model_name="catalogus",
            name="versie",
            field=models.CharField(
                blank=True,
                help_text="Versie-aanduiding van de van toepassing zijnde zaaktypecatalogus.",
                max_length=20,
                verbose_name="versie",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De benaming die is gegeven aan de zaaktypecatalogus.",
                max_length=200,
                verbose_name="naam",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_definitie",
            field=models.CharField(
                blank=True,
                help_text="Nauwkeurige beschrijving van het generieke type informatieobject",
                max_length=255,
                verbose_name="definitie",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_herkomst",
            field=models.CharField(
                blank=True,
                help_text="De naam van de waardenverzameling, of van de beherende organisatie daarvan, waaruit de waarde is overgenomen.",
                max_length=12,
                verbose_name="herkomst",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_hierarchie",
            field=models.CharField(
                blank=True,
                help_text="De plaats in de rangorde van het informatieobjecttype.",
                max_length=80,
                verbose_name="hierarchie",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_informatieobjecttype",
            field=models.CharField(
                blank=True,
                help_text="Algemeen gehanteerde omschrijving van het type informatieobject.",
                max_length=80,
                verbose_name="informatieobjecttype omschrijving generiek",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_opmerking",
            field=models.CharField(
                blank=True,
                help_text="Zinvolle toelichting bij het informatieobjecttype",
                max_length=255,
                verbose_name="opmerking",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="trefwoord",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30, verbose_name="trefwoord"),
                blank=True,
                default=list,
                help_text="Trefwoord(en) waarmee informatieobjecten van het INFORMATIEOBJECTTYPE kunnen worden gekarakteriseerd. (Gebruik een komma om waarden van elkaar te onderscheiden.)",
                size=None,
            ),
        ),
    ]
