# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0016_alter_resultaattype_omschrijving"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogus",
            old_name="_admin_name",
            new_name="naam",
        ),
    ]
