# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-19 12:25

from django.db import migrations, models
import django.contrib.postgres.fields
import openzaak.utils.fields
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0017_rename__admin_name_catalogus_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogus",
            name="begindatum_versie",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop de versie van de zaaktypecatalogus van toepassing is geworden.",
                null=True,
                verbose_name="begindatum versie",
            ),
        ),
        migrations.AddField(
            model_name="catalogus",
            name="versie",
            field=models.CharField(
                blank=True,
                help_text="Versie-aanduiding van de van toepassing zijnde zaaktypecatalogus.",
                max_length=20,
                verbose_name="versie",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De benaming die is gegeven aan de zaaktypecatalogus.",
                max_length=200,
                verbose_name="naam",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_definitie",
            field=models.CharField(
                blank=True,
                help_text="Nauwkeurige beschrijving van het generieke type informatieobject",
                max_length=255,
                verbose_name="definitie",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_herkomst",
            field=models.CharField(
                blank=True,
                help_text="De naam van de waardenverzameling, of van de beherende organisatie daarvan, waaruit de waarde is overgenomen.",
                max_length=12,
                verbose_name="herkomst",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_hierarchie",
            field=models.CharField(
                blank=True,
                help_text="De plaats in de rangorde van het informatieobjecttype.",
                max_length=80,
                verbose_name="hierarchie",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_informatieobjecttype",
            field=models.CharField(
                blank=True,
                help_text="Algemeen gehanteerde omschrijving van het type informatieobject.",
                max_length=80,
                verbose_name="informatieobjecttype omschrijving generiek",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="omschrijving_generiek_opmerking",
            field=models.CharField(
                blank=True,
                help_text="Zinvolle toelichting bij het informatieobjecttype",
                max_length=255,
                verbose_name="opmerking",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="trefwoord",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30, verbose_name="trefwoord"),
                blank=True,
                default=list,
                help_text="Trefwoord(en) waarmee informatieobjecten van het INFORMATIEOBJECTTYPE kunnen worden gekarakteriseerd. (Gebruik een komma om waarden van elkaar te onderscheiden.)",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="indicatie_specifiek",
            field=models.BooleanField(
                blank=True,
                help_text="Aanduiding of het, vanuit archiveringsoptiek, een resultaattype betreft dat specifiek is voor een bepaalde procesobjectaard.",
                null=True,
                verbose_name="indicatie specifiek",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="informatieobjecttypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="De INFORMATIEOBJECTTYPEn die verplicht aanwezig moeten zijn in het zaakdossier van ZAAKen van dit ZAAKTYPE voordat een resultaat van dit RESULTAATTYPE kan worden gezet.",
                to="catalogi.InformatieObjectType",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="procesobjectaard",
            field=models.CharField(
                blank=True,
                help_text="Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, het resultaattype bij zaken van dit type betrekking heeft.",
                max_length=200,
                verbose_name="procesobjectaard",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="procestermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie.",
                null=True,
                verbose_name="procestermijn",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="besluittypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="Het BESLUITTYPE van besluiten die gepaard gaan met resultaten van het RESULTAATTYPE.",
                to="catalogi.BesluitType",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="doorlooptijd",
            field=vng_api_common.fields.DaysDurationField(
                blank=True,
                help_text="De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van STATUSsen van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.",
                max_duration=999,
                min_duration=1,
                null=True,
                verbose_name="doorlooptijd",
            ),
        ),
        migrations.CreateModel(
            name="CheckListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemnaam",
                    models.CharField(
                        help_text="De betekenisvolle benaming van het checklistitem",
                        max_length=30,
                        verbose_name="itemnaam",
                    ),
                ),
                (
                    "vraagstelling",
                    models.CharField(
                        help_text="Een betekenisvolle vraag waaruit blijkt waarop het aandachtspunt gecontroleerd moet worden.",
                        max_length=255,
                        verbose_name="vraagstelling",
                    ),
                ),
                (
                    "verplicht",
                    models.BooleanField(
                        default=False,
                        help_text="Het al dan niet verplicht zijn van controle van het aandachtspunt voorafgaand aan het bereiken van de status van het gerelateerde STATUSTYPE.",
                        verbose_name="verplicht",
                    ),
                ),
                (
                    "toelichting",
                    models.CharField(
                        blank=True,
                        help_text="Beschrijving van de overwegingen bij het controleren van het aandachtspunt",
                        max_length=1000,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "statustype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.statustype",
                    ),
                ),
            ],
            options={
                "ordering": ("statustype", "itemnaam"),
                "verbose_name": "Checklist item",
                "verbose_name_plural": "Checklist items",
            },
        ),
        migrations.AddField(
            model_name="eigenschap",
            name="statustype",
            field=models.ForeignKey(
                blank=True,
                help_text="Status type moet (onder andere) deze EIGENSCHAP hebben, voordat een STATUS van het STATUSTYPE kan worden gezet.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eigenschappen",
                to="catalogi.statustype",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="informatieobjectcategorie",
            field=models.CharField(
                default="onbekend",
                help_text="Typering van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.",
                max_length=80,
                verbose_name="categorie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="verantwoordelijke",
            field=models.CharField(
                blank=True,
                help_text="De (soort) organisatorische eenheid of (functie van) medewerker die verantwoordelijk is voor de uitvoering van zaken van het ZAAKTYPE.",
                max_length=50,
                verbose_name="verantwoordelijke",
            ),
        ),
    ]
