# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.18 on 2023-09-27 12:05

from django.db import migrations, models


def fill_zaaktype_verantwoordelijke(apps, schema_editor):
    """
    data migration to fill zaaktype.verantwoordelijke with catalogus.rsin
    """
    Catalogus = apps.get_model("catalogi", "Catalogus")
    for catalog in (
        Catalogus.objects.prefetch_related("zaaktype_set")
        .filter(zaaktype__isnull=False)
        .distinct()
    ):

        zaaktypen = catalog.zaaktype_set.all()
        zaaktypen.update(verantwoordelijke=catalog.rsin)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0018_auto_20230919_1225"),
    ]

    operations = [
        migrations.RunPython(
            fill_zaaktype_verantwoordelijke, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="verantwoordelijke",
            field=models.CharField(
                help_text="De (soort) organisatorische eenheid of (functie van) medewerker die verantwoordelijk is voor de uitvoering van zaken van het ZAAKTYPE.",
                max_length=50,
                verbose_name="verantwoordelijke",
            ),
        ),
    ]
