# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2023 Dimpact
# Generated by Django 3.2.23 on 2024-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0020_auto_20231013_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="referentieproces_naam",
            field=models.CharField(
                help_text="De naam van het Referentieproces. Zie ook de Procesarchitectuur Referentieprocessen op https://www.gemmaonline.nl/index.php/Procesarchitectuur_Referentieprocessen",
                max_length=80,
                verbose_name="referentieprocesnaam",
            ),
        ),
    ]
