# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0021_alter_zaaktype_referentieproces_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="bronzaaktype_identificatie",
            field=models.CharField(
                blank=True,
                help_text="De Zaaktype-identificatie van het bronzaaktype binnen de CATALOGUS.",
                max_length=50,
                verbose_name="bronzaaktype identificatie",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="identificatie",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.",
                max_length=50,
                verbose_name="identificatie",
            ),
        ),
    ]
