# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 4.2.11 on 2024-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0022_alter_zaaktype_bronzaaktype_identificatie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_datumkenmerk",
            field=models.CharField(
                blank=True,
                help_text="Naam van de attribuutsoort van het procesobject dat bepalend is voor het einde van de procestermijn. **EXPERIMENTEEL**: In het geval van afleidingswijze zaakobject kunnen nested attributen gespecificeerd worden door middel van `/` (bijv. `some/nested/path`)",
                max_length=80,
                verbose_name="datumkenmerk",
            ),
        ),
    ]
