# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.8 on 2026-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogi', '0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultaattype',
            name='brondatum_archiefprocedure_afleidingswijze',
            field=models.CharField(choices=[('afgehandeld', 'Afgehandeld'), ('ander_datumkenmerk', 'Ander datumkenmerk'), ('eigenschap', 'Eigenschap'), ('gerelateerde_zaak', '**EXPERIMENTEEL DEPRECATED**: Gerelateerde zaak'), ('hoofdzaak', 'Hoofdzaak'), ('ingangsdatum_besluit', 'Ingangsdatum besluit'), ('termijn', 'Termijn'), ('vervaldatum_besluit', 'Vervaldatum besluit'), ('zaakobject', 'Zaakobject')], help_text='Wijze van bepalen van de brondatum.', max_length=20, verbose_name='afleidingswijze brondatum'),
        ),
    ]
