# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2025 Dimpact
# Generated by Django 5.1.7 on 2025-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="statustype",
            name="is_eindstatus",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Geeft aan dat dit STATUSTYPE een eindstatus betreft. Dit gegeven is afgeleid uit alle STATUSTYPEn van dit ZAAKTYPE met het hoogste volgnummer.",
                verbose_name="is eindstatus",
            ),
        ),
    ]
