# Generated by Django 5.2.3 on 2025-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktype",
            name="_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
