# Generated by Django 4.2.19 on 2025-03-25 10:33

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                help_text="Aanduiding van de mate waarin informatieobjecten van dit INFORMATIEOBJECTTYPE voor de openbaarheid bestemd zijn.",
                verbose_name="vertrouwelijkheidaanduiding",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                help_text="Aanduiding van de mate waarin zaakdossiers van ZAAKen van dit ZAAKTYPE voor de openbaarheid bestemd zijn. Indien de zaak bij het aanmaken geen vertrouwelijkheidaanduiding krijgt, dan wordt deze waarde gezet.",
                verbose_name="vertrouwelijkheidaanduiding",
            ),
        ),
    ]
