# Generated by Django 5.1.7 on 2025-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="statustype",
            name="is_eindstatus",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="",
                verbose_name="is eindstatus",
            ),
        ),
    ]
