# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2024 Dimpact
# Generated by Django 5.2.7 on 2025-10-23 07:39

import openzaak.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0023_alter_resultaattype_brondatum_archiefprocedure_datumkenmerk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_afleidingswijze",
            field=models.CharField(
                choices=[
                    ("afgehandeld", "Afgehandeld"),
                    ("ander_datumkenmerk", "Ander datumkenmerk"),
                    ("eigenschap", "Eigenschap"),
                    ("gerelateerde_zaak", "Gerelateerde zaak"),
                    ("hoofdzaak", "Hoofdzaak"),
                    ("ingangsdatum_besluit", "Ingangsdatum besluit"),
                    ("termijn", "Termijn"),
                    ("vervaldatum_besluit", "Vervaldatum besluit"),
                    ("zaakobject", "Zaakobject"),
                ],
                help_text="Wijze van bepalen van de brondatum. Indien niet van toepassing, laat leeg of gebruik 'afgehandeld'.",
                max_length=20,
                verbose_name="afleidingswijze brondatum",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_einddatum_bekend",
            field=models.BooleanField(
                default=False,
                help_text="Indicatie dat de einddatum van het procesobject gedurende de uitvoering van de zaak bekend moet worden. Indien deze nog niet bekend is en deze waarde staat op `true`, dan kan de zaak (nog) niet afgesloten worden. Standaard is deze waarde `False`.",
                verbose_name="einddatum bekend",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_objecttype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adres", "Adres"),
                    ("besluit", "Besluit"),
                    ("buurt", "Buurt"),
                    ("enkelvoudig_document", "Enkelvoudig document"),
                    ("gemeente", "Gemeente"),
                    ("gemeentelijke_openbare_ruimte", "Gemeentelijke openbare ruimte"),
                    ("huishouden", "Huishouden"),
                    ("inrichtingselement", "Inrichtingselement"),
                    ("kadastrale_onroerende_zaak", "Kadastrale onroerende zaak"),
                    ("kunstwerkdeel", "Kunstwerkdeel"),
                    ("maatschappelijke_activiteit", "Maatschappelijke activiteit"),
                    ("medewerker", "Medewerker"),
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("openbare_ruimte", "Openbare ruimte"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("pand", "Pand"),
                    ("spoorbaandeel", "Spoorbaandeel"),
                    ("status", "Status"),
                    ("terreindeel", "Terreindeel"),
                    ("terrein_gebouwd_object", "Terrein gebouwd object"),
                    ("vestiging", "Vestiging"),
                    ("waterdeel", "Waterdeel"),
                    ("wegdeel", "Wegdeel"),
                    ("wijk", "Wijk"),
                    ("woonplaats", "Woonplaats"),
                    ("woz_deelobject", "Woz deel object"),
                    ("woz_object", "Woz object"),
                    ("woz_waarde", "Woz waarde"),
                    ("zakelijk_recht", "Zakelijk recht"),
                    ("overige", "Overige"),
                ],
                help_text="Het soort object in de registratie dat het procesobject representeert.Indien niet van toepassing voor de afleidingswijze, laat leeg.",
                max_length=80,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_procestermijn",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is. Standaard is leeg (None) indien niet van toepassing.",
                null=True,
                verbose_name="procestermijn",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_registratie",
            field=models.CharField(
                blank=True,
                help_text="De naam van de registratie waarvan het procesobject deel uit maakt. Indien niet van toepassing voor de afleidingswijze, laat leeg. ",
                max_length=80,
                verbose_name="registratie",
            ),
        ),
    ]
