# Generated by Django 5.1.7 on 2025-04-11 13:42

import vng_api_common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0024_alter_informatieobjecttype_vertrouwelijkheidaanduiding_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    (10, "Openbaar"),
                    (20, "Beperkt openbaar"),
                    (30, "Intern"),
                    (40, "Zaakvertrouwelijk"),
                    (50, "Vertrouwelijk"),
                    (60, "Confidentieel"),
                    (70, "Geheim"),
                    (80, "Zeer geheim"),
                ],
                db_index=True,
                help_text="Aanduiding van de mate waarin zaakdossiers van ZAAKen van dit ZAAKTYPE voor de openbaarheid bestemd zijn. Indien de zaak bij het aanmaken geen vertrouwelijkheidaanduiding krijgt, dan wordt deze waarde gezet.",
                verbose_name="vertrouwelijkheidaanduiding",
            ),
        ),
    ]
