# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.8 on 2026-01-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogi",
            "0024_alter_resultaattype_brondatum_archiefprocedure_afleidingswijze",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="besluittype",
            options={
                "ordering": ("pk",),
                "verbose_name": "besluittype",
                "verbose_name_plural": "besluittypen",
            },
        ),
    ]
