# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.15 on 2026-07-07 10:22
from dateutil.relativedelta import relativedelta
from django.db import migrations
from django.db.migrations import RunPython

def set_P0D_servicenorms_to_none(apps, schema_editor):
    ZaakType = apps.get_model('catalogi', 'ZaakType')

    ZaakType.objects.filter(servicenorm_behandeling=relativedelta()).update(servicenorm_behandeling=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogi', '0025_alter_besluittype_options'),
    ]

    operations = [
        RunPython(set_P0D_servicenorms_to_none, migrations.RunPython.noop),
    ]
