# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-09-11 12:40

import openzaak.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogi", "0027_alter_resultaattype_brondatum_archiefprocedure_objecttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statustype",
            name="doorlooptijd",
            field=openzaak.utils.fields.DurationField(
                blank=True,
                help_text="De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van STATUSsen van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.",
                null=True,
                verbose_name="doorlooptijd",
            ),
        ),
    ]
