# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-09-25 13:58

import django.db.models.deletion
import openzaak.utils.fields
import zgw_consumers.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogi", "0027_alter_resultaattype_brondatum_archiefprocedure_objecttype"),
        ("zgw_consumers", "0001_initial_to_v120"),
    ]

    operations = [
        migrations.CreateModel(
            name="BesluitTypeInformatieObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_iotype_relative_url",
                    openzaak.utils.fields.RelativeURLField(
                        blank=True,
                        help_text="Relatief deel van URL-referentie naar de externe API",
                        max_length=1000,
                        null=True,
                        verbose_name="informatieobjecttype relative url",
                    ),
                ),
                (
                    "_iotype_url",
                    zgw_consumers.models.fields.ServiceUrlField(
                        base_field="_iotype_base_url",
                        blank=True,
                        null=True,
                        relative_field="_iotype_relative_url",
                    ),
                ),
                (
                    "_informatieobjecttype",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL-referentie naar het INFORMATIEOBJECTTYPE.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.informatieobjecttype",
                    ),
                ),
                (
                    "_iotype_base_url",
                    openzaak.utils.fields.ServiceFkField(
                        blank=True,
                        help_text="Basis deel van URL-referentie naar de externe API",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                    ),
                ),
                (
                    "besluittype",
                    models.ForeignKey(
                        help_text="URL-referentie naar het BESLUITTYPE.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogi.besluittype",
                        verbose_name="besluittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besluit-Informatieobject-Type",
                "verbose_name_plural": "Besluit-Informatieobject-Typen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("besluittype", "_informatieobjecttype"),
                        name="unique_besluittype_and_local_informatieobjecttype",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("_iotype_relative_url__isnull", False)),
                        fields=(
                            "besluittype",
                            "_iotype_base_url",
                            "_iotype_relative_url",
                        ),
                        name="unique_besluittype_and_external_informatieobjecttype",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("_iotype_base_url__isnull", True),
                                models.Q(
                                    ("_iotype_relative_url__isnull", True),
                                    ("_iotype_relative_url", ""),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                models.Q(
                                    ("_iotype_base_url__isnull", True), _negated=True
                                ),
                                models.Q(
                                    ("_iotype_relative_url__isnull", True),
                                    ("_iotype_relative_url", ""),
                                    _connector="OR",
                                    _negated=True,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="catalogi_besluittypeinformatieobjecttype__iotype_base_url_and__iotype_relative_url_filled",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(
                                    ("_informatieobjecttype__isnull", True),
                                    _negated=True,
                                ),
                                ("_iotype_base_url__isnull", True),
                            ),
                            models.Q(
                                ("_informatieobjecttype__isnull", True),
                                models.Q(
                                    ("_iotype_base_url__isnull", True), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="catalogi_besluittypeinformatieobjecttype__informatieobjecttype_or__iotype_base_url_filled",
                    ),
                ],
            },
        ),
        migrations.SeparateDatabaseAndState(
            # the loose-fk field is not a database field: only the fk and url fields
            # have columns
            state_operations=[
                migrations.AddField(
                    model_name="besluittypeinformatieobjecttype",
                    name="informatieobjecttype",
                    field=openzaak.utils.fields.FkOrServiceUrlField(
                        blank=False,
                        fk_field="_informatieobjecttype",
                        null=False,
                        url_field="_iotype_url",
                    ),
                ),
            ],
        ),
    ]
