# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Dimpact
# Generated by Django 5.2.17 on 2026-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogi', '0028_alter_statustype_doorlooptijd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultaattype',
            name='besluittypen',
            field=models.ManyToManyField(blank=True, help_text='Het BESLUITTYPE van besluiten die gepaard gaan met resultaten van het RESULTAATTYPE.', related_name='resultaattypen', to='catalogi.besluittype'),
        ),
    ]
