name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: openzaak/open-zaak
  DJANGO_SETTINGS_MODULE: openzaak.conf.ci
  DB_PASSWORD: ''
  DB_USER: postgres
  ALLOWED_HOSTS: openzaak.nl
  COMPOSE_DOCKER_CLI_BUILD: '1'
  DOCKER_BUILDKIT: '1'

jobs:
  # determine changed files to decide if certain jobs can be skipped or not
  changed-files:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Determine changed files
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed PY files
        id: changed-py-files
        uses: tj-actions/changed-files@v45
        with:
          files: src/{,**/}*.py

      - name: Get changed requirements files
        id: changed-requirements
        uses: tj-actions/changed-files@v45
        with:
          files: requirements/*.txt

    outputs:
      changed-py-files: ${{ steps.changed-py-files.outputs.any_changed }}
      changed-requirements: ${{ steps.changed-requirements.outputs.any_changed }}

  # TODO: restore tests steps, see 148c4d2c44ee0414e7e9fbca6e6fde8d1429ce20

  store-reusable-workflow-vars:
    name: create values which can be passed through a reusable workflow
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image-name }}
      sphinx-ssl-conf: ${{ steps.sphinx-ssl-conf.outputs.sphinx-ssl-conf }}

    steps:
      - run: echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        name: 'Store the docker image name'
        id: image-name
      - run: echo "sphinx-ssl-conf=${{ github.workspace }}/docs/openssl.conf" >> $GITHUB_OUTPUT
        name: 'Store the sphinx openssl configuration path'
        id: sphinx-ssl-conf

  open-api-ci:
    uses: maykinmedia/open-api-workflows/.github/workflows/ci.yml@initial-setup
    # TODO: add tests to `needs`
    needs:
      - store-reusable-workflow-vars
    with:
      main-branch: 'main'
      python-version: '3.11'
      docker-image-name: ${{ needs.store-reusable-workflow-vars.outputs.image-name }}
      docs-ssl-conf: ${{ needs.store-reusable-workflow-vars.outputs.sphinx-ssl-conf }}
      repository-owner: 'open-zaak'
