name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# least privilege as default, should be overridden per job if necessary
permissions:
  contents: read

jobs:
  open-api-workflow-code-quality:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-quality.yml@31eaea25acd18bb681fe0d01b2452c3dd8d299b9 # v7.0.0
    with:
      apt-packages: "gdal-bin"
      python-version: "3.12"
      node-version: "24"
      postgres-image: "postgis/postgis:16-3.5"

      django-settings-module: "openzaak.conf.ci"
      django-secret-key: dummy

  # openzaak specific
  spdx:
    name: SPDX header check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: maykinmedia/setup-django-backend@4a6c5facc65bb1dd510cf06be20871db11a156b3 # v1.4.2
        with:
          apt-packages: "libxml2 libxmlsec1 libxmlsec1-openssl"
          python-version: "3.12"
          setup-node: false
      - name: Run check
        run: ./bin/check_spdx.py src

  type-checking:
    name: Type checking (Pyright)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install additional dependencies
        run: |
          pip install uv
          uv pip install \
            --system \
            -r requirements/type-checking.txt
      - uses: jakebailey/pyright-action@8ec14b5cfe41f26e5f41686a31eb6012758217ef # v3.0.2
        with:
          version: 1.1.407
          project: pyright.pyproject.toml
