name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  open-api-workflow-code-quality:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-quality.yml@0a5525c13f8eea10be40c8eaee5e535ea3a10721 # v6.4.1
    with:
      apt-packages: "libgdal-dev gdal-bin"
      python-version: "3.12"
      node-version: "24"
      postgres-image: "postgis/postgis:16-3.5"

      django-settings-module: "openzaak.conf.ci"
      django-secret-key: dummy

  # openzaak specific
  spdx:
    name: SPDX header check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: maykinmedia/setup-django-backend@4a6c5facc65bb1dd510cf06be20871db11a156b3 # v1.4.2
        with:
          apt-packages: "libxml2 libxmlsec1 libxmlsec1-openssl"
          python-version: "3.12"
          setup-node: false
      - name: Run check
        run: ./bin/check_spdx.py src
