name: check-oas

on:
  push:
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v5
    strategy:
      matrix:
        component:
          - autorisaties
          - besluiten
          - catalogi
          - documenten
          - zaken
    with:
      schema-path: 'src/openzaak/components/${{ matrix.component }}/openapi.yaml'
      schema-command: 'bin/generate_schema_for_component.sh'
      schema-options: "${{ matrix.component }} src/openzaak/components/${{ matrix.component }}/openapi.yaml"
      python-version: '3.11'
      django-settings-module: 'openzaak.conf.ci'
      apt-packages: 'libgdal-dev gdal-bin'
