name: check-oas

on:
  push:
    paths:
      - "src/openzaak/components/*/openapi.yaml"
      - .github/workflows/oas-check.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v1
    strategy:
      matrix:
        component:
          - autorisaties
          - besluiten
          - catalogi
          - documenten
          - zaken
    with:
      schema-path: 'src/openzaak/components/${{ matrix.component }}/openapi.yaml'
      schema-command: 'spectacular_for_component'
      schema-options: "--component ${{ matrix.component }}"
      python-version: '3.11'
      django-settings-module: 'openzaak.conf.ci'
      apt-packages: 'libgdal-dev gdal-bin'
