name: Quick Start

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

# least privilege as default, should be overridden per job if necessary
permissions:
  contents: read

jobs:
  open-api-workflow-quick-start:
    uses: maykinmedia/open-api-workflows/.github/workflows/quick-start.yml@v6
    with:
      service_name: web.local
